/**
 * Systemic Strategy Pathfinding Engine — tRPC Router
 */
import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import {
  selectStrategy,
  calculateSuccessProbability,
  generateStrategyPath,
  evaluatePatternsForStrategies,
  updateStepStatus,
  updatePathStatus,
  getStrategyDashboard,
  getStrategyPathDetail,
  getMissionControlStrategySummary,
} from "../systemic-strategy-engine";
import {
  triggerPaperworkForStep,
  triggerPaperworkForPath,
  getAutoGeneratedDocsForStep,
  getAutoGeneratedDocsForPath,
  getPaperworkTriggerStatus,
} from "../paperwork-trigger";

export const systemicStrategyRouter = router({
  /** Dashboard: list all strategy paths with joined strategy + pattern info */
  dashboard: protectedProcedure
    .input(
      z.object({
        status: z.string().optional(),
        strategyType: z.string().optional(),
        limit: z.number().optional(),
        offset: z.number().optional(),
      }).optional()
    )
    .query(async ({ input }) => {
      return getStrategyDashboard(input || undefined);
    }),

  /** Detail: full strategy path with steps, strategy info, pattern info */
  detail: protectedProcedure
    .input(z.object({ pathId: z.string() }))
    .query(async ({ input }) => {
      return getStrategyPathDetail(input.pathId);
    }),

  /** Select best strategy for a pattern based on type, trend, and pressure */
  selectStrategy: protectedProcedure
    .input(z.object({
      patternType: z.string(),
      trendClassification: z.string(),
      pressureIndex: z.number(),
    }))
    .query(async ({ input }) => {
      return selectStrategy(input.patternType, input.trendClassification, input.pressureIndex);
    }),

  /** Calculate success probability for a strategy */
  calculateProbability: protectedProcedure
    .input(z.object({
      historicalSuccessRate: z.number(),
      pressureIndex: z.number(),
      trendClassification: z.string(),
      signalCount: z.number(),
      geographicSpread: z.number(),
    }))
    .query(async ({ input }) => {
      const probability = calculateSuccessProbability(
        input.historicalSuccessRate,
        input.pressureIndex,
        input.trendClassification,
        input.signalCount,
        input.geographicSpread
      );
      return { probability };
    }),

  /** Generate a strategy path for a pattern */
  generatePath: protectedProcedure
    .input(z.object({
      patternId: z.string(),
      strategyId: z.string(),
      pathName: z.string(),
      pathDescription: z.string().optional(),
      trendClassification: z.string(),
      pressureIndex: z.number(),
      signalCount: z.number(),
      geographicScope: z.any().optional(),
      assignedLead: z.string().optional(),
    }))
    .mutation(async ({ input }) => {
      return generateStrategyPath(input);
    }),

  /** Evaluate all active patterns and generate strategy paths */
  evaluateAll: protectedProcedure.mutation(async () => {
    return evaluatePatternsForStrategies();
  }),

  /** Update a strategy step status — with automated paperwork trigger */
  updateStep: protectedProcedure
    .input(z.object({
      stepId: z.string(),
      status: z.string(),
      notes: z.string().optional(),
      caseId: z.number().optional(),
      patternId: z.string().optional(),
      strategyId: z.string().optional(),
      pathId: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      // 1. Update the step status
      const result = await updateStepStatus(input.stepId, input.status, input.notes);

      // 2. Auto-trigger paperwork if caseId is provided
      let paperworkResult = null;
      if (input.caseId && input.pathId) {
        try {
          paperworkResult = await triggerPaperworkForStep({
            stepId: input.stepId,
            pathId: input.pathId,
            newStatus: input.status,
            caseId: input.caseId,
            userId: ctx.user.id,
            patternId: input.patternId,
            strategyId: input.strategyId,
          });
        } catch (err) {
          console.error("[PaperworkTrigger] Error:", err);
          paperworkResult = { triggered: false, reason: "Trigger error" };
        }
      }

      return { ...result, paperwork: paperworkResult };
    }),

  /** Update a strategy path status */
  updatePathStatus: protectedProcedure
    .input(z.object({
      pathId: z.string(),
      status: z.string(),
      approvedBy: z.string().optional(),
    }))
    .mutation(async ({ input }) => {
      return updatePathStatus(input.pathId, input.status, input.approvedBy);
    }),

  /** Trigger paperwork for all eligible steps in a path */
  triggerPathPaperwork: protectedProcedure
    .input(z.object({
      pathId: z.string(),
      caseId: z.number(),
      patternId: z.string().optional(),
      strategyId: z.string().optional(),
      statusFilter: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      return triggerPaperworkForPath({
        ...input,
        userId: ctx.user.id,
      });
    }),

  /** Get auto-generated documents for a step */
  stepDocuments: protectedProcedure
    .input(z.object({ stepId: z.string() }))
    .query(async ({ input }) => {
      return getAutoGeneratedDocsForStep(input.stepId);
    }),

  /** Get auto-generated documents for a path */
  pathDocuments: protectedProcedure
    .input(z.object({ pathId: z.string() }))
    .query(async ({ input }) => {
      return getAutoGeneratedDocsForPath(input.pathId);
    }),

  /** Paperwork trigger status summary */
  paperworkTriggerStatus: protectedProcedure.query(async () => {
    return getPaperworkTriggerStatus();
  }),

  /** Mission Control summary widget */
  missionControlSummary: protectedProcedure.query(async () => {
    return getMissionControlStrategySummary();
  }),
});
