import { describe, expect, it, vi } from "vitest";

vi.mock("../db", () => ({
  getPool: vi.fn(),
  query_with_diagnostics: vi.fn(),
}));

import {
  SPINE_CONFIG_TABLE_SET,
  assert_spine_identifier,
  build_spine_create_table_statement,
  build_spine_post_create_statements,
  type spine_table_schema,
} from "./spine-postgres";

function schema(overrides: Partial<spine_table_schema> = {}): spine_table_schema {
  return {
    tableName: "example_registry",
    rowCount: 0,
    rowCountMode: "estimate",
    columns: [
      {
        columnName: "id",
        typeSql: "integer",
        notNull: true,
        defaultSql: "nextval('example_registry_id_seq'::regclass)",
        identity: "",
        generated: "",
      },
      {
        columnName: "name",
        typeSql: "text",
        notNull: true,
        defaultSql: null,
        identity: "",
        generated: "",
      },
    ],
    constraints: [
      {
        constraintName: "example_registry_pkey",
        constraintType: "p",
        definition: "PRIMARY KEY (id)",
      },
    ],
    indexes: [],
    createStatement: "",
    postCreateStatements: [],
    ...overrides,
  };
}

describe("Sovereign Spine PostgreSQL grammar", () => {
  it("converts source serial defaults to portable identity columns", () => {
    const statement = build_spine_create_table_statement(schema());
    expect(statement).toContain('"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(statement).toContain('CONSTRAINT "example_registry_pkey" PRIMARY KEY (id)');
    expect(statement).not.toContain("nextval");
  });

  it("defers foreign keys and standalone indexes until all tables exist", () => {
    const value = schema({
      constraints: [
        {
          constraintName: "example_parent_fk",
          constraintType: "f",
          definition: "FOREIGN KEY (id) REFERENCES parent_registry(id)",
        },
      ],
      indexes: [
        {
          indexName: "idx_example_name",
          definition: "CREATE INDEX idx_example_name ON public.example_registry USING btree (name)",
        },
      ],
    });
    const post = build_spine_post_create_statements(value);
    expect(post).toHaveLength(2);
    expect(post[0]).toContain("ALTER TABLE");
    expect(post[1]).toMatch(/^CREATE INDEX/i);
  });

  it("rejects identifier and SQL-fragment injection", () => {
    expect(() => assert_spine_identifier("public.users")).toThrow();
    expect(() =>
      build_spine_create_table_statement(
        schema({
          columns: [
            {
              columnName: "id",
              typeSql: "integer; drop table users",
              notNull: true,
              defaultSql: null,
              identity: "",
              generated: "",
            },
          ],
        }),
      ),
    ).toThrow();
  });

  it("limits full data restoration to the declared civic configuration universe", () => {
    expect(SPINE_CONFIG_TABLE_SET.has("engine_registry")).toBe(true);
    expect(SPINE_CONFIG_TABLE_SET.has("registry_programs")).toBe(true);
    expect(SPINE_CONFIG_TABLE_SET.has("users")).toBe(false);
    expect(SPINE_CONFIG_TABLE_SET.has("cases")).toBe(false);
  });
});
