import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ArrowLeft, ChevronDown, ChevronRight, Database, Eye, Loader2, RefreshCw, ShieldAlert, Zap } from "lucide-react";

type status_filter_value = "all" | "blocked" | "review_required" | "pending_bucket_content_scan" | "pending_docx_normalization" | "ready_for_review" | "docx_extraction_failed" | "candidates_created";
type visible_queue_row = { id:number; source_name:string|null; source_ext:string|null; storage_bucket:string|null; storage_path:string|null; storage_mode:string|null; target_hint:string|null; import_status:string|null; record_count_estimate:number|null; created_at:string|null; updated_at:string|null; raw_text_chars:number; normalized_text_chars?:number|null; has_payload:boolean; policy_class:string; dedupe_behavior:string; intended_destination:string; blocked_reason:string|null; next_action:string; worker_state?:string|null; attempt_count?:number|null; leased_by?:string|null; lease_expires_at?:string|null; last_error_code?:string|null };
type queue_row_detail = visible_queue_row & { raw_text_preview:string; payload:unknown|null };
type extract_diagnostic = { success:boolean; warning?:string; error?:string; message?:string; action?:string; dry_run?:boolean; queue_row_id?:number|null; runtime_ms?:number; state_changed?:boolean; command_failed?:boolean; command_extracted?:boolean; partial_success?:boolean; command_summary?:Record<string, unknown>|null; command_report?:string|null; command_csv?:string|null; stdout_preview?:string; stderr_preview?:string; row?:visible_queue_row; before_row?:visible_queue_row };
type lane_key = "extract" | "normalize" | "review" | "route" | "other";

function format_date(value:string|null|undefined){ if(!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
function extraction_has_failure(result:extract_diagnostic|null){ if(!result) return false; const failures = Number(result.command_summary?.docxExtractionFailures ?? 0); return result.success === false || (result.command_failed === true && !result.partial_success) || (failures > 0 && !result.partial_success); }
async function read_json_response<T>(response:Response):Promise<T>{ const content_type=response.headers.get("content-type") ?? ""; const text=await response.text(); if(!content_type.includes("application/json")) throw new Error(`server_returned_non_json status=${response.status} preview=${text.slice(0,240)}`); const parsed=text ? JSON.parse(text) : null; if(!response.ok) throw Object.assign(new Error(parsed?.message ?? parsed?.error ?? response.statusText), { diagnostic: parsed }); return parsed as T; }
function source_title(row:visible_queue_row){ return row.source_name ?? row.storage_path ?? "unnamed_source"; }
function pretty_stage(row:visible_queue_row){ if(row.import_status === "ready_for_review") return "Ready for review / normalized"; if(row.next_action === "extract_docx_queue_row") return "Waiting for extraction"; if(row.next_action === "normalize_docx_queue_row") return "Ready for normalization"; if(row.next_action === "route_corpus_queue_dry_run") return "Route dry-run only"; return row.import_status ?? "No queued action"; }
function row_status_kind(row:visible_queue_row){ if(row.import_status === "review_required" || row.policy_class === "review_required") return "review_required"; if(row.import_status === "docx_extraction_failed" || row.last_error_code) return "failed"; if(row.leased_by || row.worker_state === "leased") return "running"; if(row.next_action) return "waiting"; return "idle"; }
function StatusChip({row}:{row:visible_queue_row}){ const kind=row_status_kind(row); if(kind==="failed") return <Badge variant="destructive">failed</Badge>; if(kind==="review_required") return <Badge className="bg-amber-600 text-white">review_required</Badge>; if(kind==="running") return <Badge className="bg-cyan-600 text-white">leased</Badge>; if(kind==="waiting") return <Badge variant="secondary">waiting</Badge>; return <Badge variant="outline">idle</Badge>; }
function lane_for(row:visible_queue_row):lane_key{ if(row.import_status === "ready_for_review") return "review"; if(row.next_action === "extract_docx_queue_row") return "extract"; if(row.next_action === "normalize_docx_queue_row") return "normalize"; if(row.next_action === "route_corpus_queue_dry_run") return "route"; return "other"; }

export default function IngestionControl(){
  const [status_filter,set_status_filter]=useState<status_filter_value>("all");
  const [rows,set_rows]=useState<visible_queue_row[]>([]);
  const [selected_row,set_selected_row]=useState<queue_row_detail|null>(null);
  const [loading,set_loading]=useState(false);
  const [action_key,set_action_key]=useState<string|null>(null);
  const [action_message,set_action_message]=useState<string|null>(null);
  const [extract_diagnostic,set_extract_diagnostic]=useState<extract_diagnostic|null>(null);
  const [error_message,set_error_message]=useState<string|null>(null);
  const [open_lanes,set_open_lanes]=useState<Record<lane_key,boolean>>({extract:true,normalize:true,review:true,route:true,other:false});

  const load_queue=async()=>{ set_loading(true); set_error_message(null); try{ const params=new URLSearchParams({status_filter,limit:"100"}); const result=await read_json_response<{success:boolean;rows:visible_queue_row[];error?:string;message?:string}>(await fetch(`/api/ingestion-control/corpus-import-queue?${params.toString()}`,{credentials:"include",headers:{Accept:"application/json"}})); if(!result.success) throw new Error(result.message ?? result.error ?? "ingestion_control_queue_read_failed"); set_rows(result.rows ?? []); }catch(error:any){ set_error_message(error?.message ?? String(error)); set_rows([]); }finally{ set_loading(false); } };
  const load_row=async(id:number)=>{ set_error_message(null); try{ const result=await read_json_response<{success:boolean;row:queue_row_detail|null;error?:string;message?:string}>(await fetch(`/api/ingestion-control/corpus-import-queue/${id}`,{credentials:"include",headers:{Accept:"application/json"}})); if(!result.success || !result.row) throw new Error(result.message ?? result.error ?? "corpus_import_queue_row_not_found"); set_selected_row(result.row); }catch(error:any){ set_error_message(error?.message ?? String(error)); } };
  const run_extract=async(id:number,dry_run:boolean)=>{ set_action_key(`${id}:${dry_run?"dry":"apply"}`); set_action_message(null); set_extract_diagnostic(null); set_error_message(null); try{ const result=await read_json_response<extract_diagnostic>(await fetch(`/api/ingestion-control/corpus-import-queue/${id}/extract-docx`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({dry_run})})); set_extract_diagnostic(result); if(extraction_has_failure(result)) throw new Error(result.message ?? result.error ?? "extract_docx_command_reported_failure"); set_action_message(`${dry_run?"dry_run":"apply"}_extract_docx_queue_row complete for id_${id}`); await load_queue(); await load_row(id); }catch(error:any){ if(error?.diagnostic) set_extract_diagnostic(error.diagnostic); set_error_message(error?.message ?? String(error)); await load_queue(); await load_row(id); }finally{ set_action_key(null); } };
  const drain_extract=async()=>{ set_action_key("drain:apply"); set_action_message(null); set_extract_diagnostic(null); set_error_message(null); try{ const result=await read_json_response<extract_diagnostic>(await fetch(`/api/ingestion-control/corpus-import-queue/extract-docx-drain`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({dry_run:false})})); set_extract_diagnostic(result); if(extraction_has_failure(result)) throw new Error(result.message ?? result.error ?? "extract_docx_drain_reported_failure"); const extracted=Number(result.command_summary?.docxRowsExtracted ?? 0); const failures=Number(result.command_summary?.docxExtractionFailures ?? 0); set_action_message(result.partial_success ? `Extract all DOCX partial_success · extracted ${extracted} rows · ${failures} rows need review` : `Extract all DOCX complete · extracted ${extracted} rows`); await load_queue(); }catch(error:any){ if(error?.diagnostic) set_extract_diagnostic(error.diagnostic); set_error_message(error?.message ?? String(error)); await load_queue(); }finally{ set_action_key(null); } };
  const drain_normalize=async()=>{ set_action_key("normalize:drain"); set_action_message(null); set_extract_diagnostic(null); set_error_message(null); try{ const result=await read_json_response<{success:boolean;action:string;runtime_ms:number;summary?:{normalized_rows?:number|string;normalized_characters?:number|string};error?:string;message?:string}>(await fetch(`/api/ingestion-control/corpus-import-queue/normalize-docx-drain`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({})})); if(!result.success) throw new Error(result.message ?? result.error ?? "normalize_docx_drain_failed"); const normalized_rows=Number(result.summary?.normalized_rows ?? 0); const normalized_characters=Number(result.summary?.normalized_characters ?? 0); set_action_message(`Normalize all extracted DOCX complete · normalized_rows ${normalized_rows.toLocaleString()} · normalized_characters ${normalized_characters.toLocaleString()}`); await load_queue(); }catch(error:any){ set_error_message(error?.message ?? String(error)); await load_queue(); }finally{ set_action_key(null); } };

  useEffect(()=>{ load_queue(); },[status_filter]);
  const grouped=useMemo(()=>({ extract:rows.filter(row=>lane_for(row)==="extract"), normalize:rows.filter(row=>lane_for(row)==="normalize"), review:rows.filter(row=>lane_for(row)==="review"), route:rows.filter(row=>lane_for(row)==="route"), other:rows.filter(row=>lane_for(row)==="other") }),[rows]);
  const summary=useMemo(()=>({ total_visible_rows:rows.length, pending_bucket_content_scan:rows.filter(row=>row.import_status==="pending_bucket_content_scan").length, pending_docx_normalization:rows.filter(row=>row.import_status==="pending_docx_normalization").length, ready_for_review:rows.filter(row=>row.import_status==="ready_for_review").length, docx_extraction_failed:rows.filter(row=>row.import_status==="docx_extraction_failed").length, candidates_created:rows.filter(row=>row.import_status==="candidates_created").length, extractable_docx_rows:grouped.extract.length, normalization_rows:grouped.normalize.length }),[rows,grouped]);
  const diagnostic_failed=extraction_has_failure(extract_diagnostic);
  const toggle_lane=(key:lane_key)=>set_open_lanes(value=>({...value,[key]:!value[key]}));

  function FieldGrid({row}:{row:visible_queue_row}){ return <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-[11px] text-muted-foreground"><div><span className="text-foreground">storage_bucket:</span> {row.storage_bucket??"—"}</div><div><span className="text-foreground">storage_path:</span> {row.storage_path??"—"}</div><div><span className="text-foreground">target_hint:</span> {row.target_hint??"—"}</div><div><span className="text-foreground">intended_destination:</span> {row.intended_destination}</div><div><span className="text-foreground">storage_mode:</span> {row.storage_mode??"—"}</div><div><span className="text-foreground">raw_text_chars:</span> {row.raw_text_chars.toLocaleString()}</div><div><span className="text-foreground">normalized_text_chars:</span> {(row.normalized_text_chars??0).toLocaleString()}</div><div><span className="text-foreground">dedupe_behavior:</span> {row.dedupe_behavior}</div><div><span className="text-foreground">next_action:</span> {row.next_action}</div><div><span className="text-foreground">blocked_reason:</span> {row.blocked_reason??"—"}</div><div><span className="text-foreground">worker_state:</span> {row.worker_state??"—"}</div><div><span className="text-foreground">attempt_count:</span> {row.attempt_count??0}</div><div><span className="text-foreground">leased_by:</span> {row.leased_by??"—"}</div><div><span className="text-foreground">lease_expires_at:</span> {format_date(row.lease_expires_at)}</div><div><span className="text-foreground">last_error_code:</span> {row.last_error_code??"—"}</div><div><span className="text-foreground">updated_at:</span> {format_date(row.updated_at)}</div></div>; }
  function RowActions({row}:{row:visible_queue_row}){ return <div className="flex flex-wrap justify-end gap-2"><Button size="sm" variant="outline" onClick={()=>load_row(row.id)}><Eye className="h-3 w-3 mr-1"/> details</Button>{row.next_action==="extract_docx_queue_row"&&<><Button size="sm" variant="outline" onClick={()=>run_extract(row.id,true)} disabled={action_key===`${row.id}:dry`}>{action_key===`${row.id}:dry`?<Loader2 className="h-3 w-3 mr-1 animate-spin"/>:null}dry_run</Button><Button size="sm" variant="secondary" onClick={()=>run_extract(row.id,false)} disabled={action_key===`${row.id}:apply`}>{action_key===`${row.id}:apply`?<Loader2 className="h-3 w-3 mr-1 animate-spin"/>:null}apply</Button></>}</div>; }
  function Lane({lane_key,title,description,rows}:{lane_key:lane_key;title:string;description:string;rows:visible_queue_row[]}){ const open=open_lanes[lane_key]; const failed=rows.filter(row=>row_status_kind(row)==="failed").length; return <Card className="bg-card/50"><CardHeader className="p-4"><div className="flex items-start justify-between gap-4"><div><CardTitle className="text-base flex items-center gap-2">{title}<Badge variant="outline">{rows.length} rows</Badge>{failed>0&&<Badge variant="destructive">{failed} failed</Badge>}</CardTitle><p className="text-xs text-muted-foreground mt-1">{description}</p></div><Button size="sm" variant="ghost" onClick={()=>toggle_lane(lane_key)}>{open?<ChevronDown className="h-4 w-4 mr-1"/>:<ChevronRight className="h-4 w-4 mr-1"/>}{open?"collapse":"expand"}</Button></div></CardHeader>{open&&<CardContent className="p-0"><div className="divide-y divide-border">{rows.map(row=><article key={row.id} className="p-3 hover:bg-muted/20"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2 mb-1"><Badge variant="outline">id_{row.id}</Badge><StatusChip row={row}/><span className="text-sm font-medium truncate">{source_title(row)}</span></div><div className="text-[11px] text-muted-foreground truncate">{pretty_stage(row)} · {row.target_hint ?? row.intended_destination} · updated {format_date(row.updated_at)}</div><div className="mt-2"><FieldGrid row={row}/></div></div><RowActions row={row}/></div></article>)}{rows.length===0&&<div className="text-sm text-muted-foreground text-center py-8">no_rows_in_lane</div>}</div></CardContent>}</Card>; }

  return <div className="p-6 max-w-7xl mx-auto space-y-6">
    <div className="flex items-center justify-between gap-4"><div className="flex items-center gap-4"><Link href="/sovereign-control"><Button variant="outline" size="sm" className="gap-1.5"><ArrowLeft className="h-4 w-4"/>Sovereign Control</Button></Link><div><h1 className="text-2xl font-bold text-foreground flex items-center gap-2"><Database className="h-5 w-5 text-cyan-400"/>ingestion_control</h1><p className="text-sm text-muted-foreground">Server-backed queue viewer for bucket and corpus staging. No canonical promotion.</p></div></div><div className="flex gap-2"><Button variant="secondary" size="sm" onClick={drain_extract} disabled={Boolean(action_key)||summary.extractable_docx_rows===0}>{action_key==="drain:apply"?<Loader2 className="h-4 w-4 mr-2 animate-spin"/>:<Zap className="h-4 w-4 mr-2"/>}Extract all DOCX ({summary.extractable_docx_rows})</Button><Button variant="secondary" size="sm" onClick={drain_normalize} disabled={Boolean(action_key)||summary.normalization_rows===0}>{action_key==="normalize:drain"?<Loader2 className="h-4 w-4 mr-2 animate-spin"/>:<Zap className="h-4 w-4 mr-2"/>}Normalize all extracted DOCX ({summary.normalization_rows})</Button><Button variant="outline" size="sm" disabled>Create candidates from ready rows · Candidate creation endpoint not wired yet.</Button><Button variant="outline" size="sm" onClick={load_queue} disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin mr-2"/>:<RefreshCw className="h-4 w-4 mr-2"/>}refresh_queue</Button></div></div>
    <div className="grid grid-cols-2 md:grid-cols-6 gap-3"><Card className="bg-card/50"><CardContent className="p-3"><div className="text-xs text-muted-foreground">total visible rows</div><div className="text-xl font-bold">{summary.total_visible_rows}</div></CardContent></Card><Card className="bg-card/50"><CardContent className="p-3"><div className="text-xs text-muted-foreground">pending_bucket_content_scan</div><div className="text-xl font-bold text-cyan-400">{summary.pending_bucket_content_scan}</div></CardContent></Card><Card className="bg-card/50"><CardContent className="p-3"><div className="text-xs text-muted-foreground">pending_docx_normalization</div><div className="text-xl font-bold text-emerald-400">{summary.pending_docx_normalization}</div></CardContent></Card><Card className="bg-card/50"><CardContent className="p-3"><div className="text-xs text-muted-foreground">ready_for_review</div><div className="text-xl font-bold text-purple-400">{summary.ready_for_review}</div></CardContent></Card><Card className="bg-card/50"><CardContent className="p-3"><div className="text-xs text-muted-foreground">docx_extraction_failed</div><div className="text-xl font-bold text-red-400">{summary.docx_extraction_failed}</div></CardContent></Card><Card className="bg-card/50"><CardContent className="p-3"><div className="text-xs text-muted-foreground">candidates_created</div><div className="text-xl font-bold text-amber-400">{summary.candidates_created}</div></CardContent></Card></div>
    <Card className="border-cyan-500/20 bg-cyan-950/10"><CardHeader className="p-4 pb-2"><CardTitle className="text-sm flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-cyan-400"/> operator_posture</CardTitle></CardHeader><CardContent className="p-4 pt-0 text-xs text-muted-foreground">server_read_path · viewer_first · staging_only · no_canonical_promotion · no_freeform_shell · route_dry_run_only</CardContent></Card>
    <div className="flex items-center justify-between gap-3"><Select value={status_filter} onValueChange={(value)=>set_status_filter(value as status_filter_value)}><SelectTrigger className="w-[280px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">all</SelectItem><SelectItem value="blocked">blocked</SelectItem><SelectItem value="review_required">review_required</SelectItem><SelectItem value="pending_bucket_content_scan">pending_bucket_content_scan</SelectItem><SelectItem value="pending_docx_normalization">pending_docx_normalization</SelectItem><SelectItem value="ready_for_review">ready_for_review</SelectItem><SelectItem value="docx_extraction_failed">docx_extraction_failed</SelectItem><SelectItem value="candidates_created">candidates_created</SelectItem></SelectContent></Select></div>
    {action_message&&<Card className="border-green-500/30 bg-green-950/10"><CardContent className="p-3 text-sm text-green-300">{action_message}</CardContent></Card>}{error_message&&<Card className="border-red-500/30 bg-red-950/10"><CardContent className="p-3 text-sm text-red-300">{error_message}</CardContent></Card>}{extract_diagnostic&&<Card className={diagnostic_failed?"border-red-500/30 bg-red-950/10":"border-green-500/30 bg-green-950/10"}><CardContent className="p-3 space-y-2 text-xs"><div className="font-semibold">extract_diagnostic: {extract_diagnostic.error ?? (diagnostic_failed?"extract_docx_command_reported_failure":"success")}</div><div>state_changed: {String(extract_diagnostic.state_changed??false)} · command_failed: {String(extract_diagnostic.command_failed??false)} · command_extracted: {String(extract_diagnostic.command_extracted??false)} · dry_run: {String(extract_diagnostic.dry_run??false)} · runtime_ms: {extract_diagnostic.runtime_ms??"—"}</div>{extract_diagnostic.message&&<div>{extract_diagnostic.message}</div>}{extract_diagnostic.command_summary&&<pre className="text-[10px] whitespace-pre-wrap bg-muted/30 rounded p-2 max-h-40 overflow-auto">command_summary:{"\n"}{JSON.stringify(extract_diagnostic.command_summary,null,2)}</pre>}<pre className="text-[10px] whitespace-pre-wrap bg-muted/30 rounded p-2 max-h-40 overflow-auto">stdout_preview:{"\n"}{extract_diagnostic.stdout_preview||"—"}{"\n\n"}stderr_preview:{"\n"}{extract_diagnostic.stderr_preview||"—"}</pre></CardContent></Card>}
    <div className="space-y-4"><Lane lane_key="extract" title="Bucket scan / extraction queue" description="DOCX registry rows queued for Storage download and controlled WordprocessingML extraction. Safe staging transition." rows={grouped.extract}/><Lane lane_key="normalize" title="Ready to normalize" description="Rows with extracted raw text ready to normalize into review-ready registry text." rows={grouped.normalize}/><Lane lane_key="review" title="Ready for review / normalized" description="Normalized corpus import rows ready for candidate creation review." rows={grouped.review}/><Lane lane_key="route" title="Route dry-run review" description="SQL and ZIP artifacts stay plan-only while canonical promotion is disabled." rows={grouped.route}/>{grouped.other.length>0&&<Lane lane_key="other" title="Other queue rows" description="Rows without one of the three active ingestion actions." rows={grouped.other}/>}</div>
    {selected_row&&<Card className="border-cyan-500/30 bg-card"><CardHeader className="p-4 pb-2"><CardTitle className="text-sm flex items-center justify-between"><span>row_detail: id_{selected_row.id}</span><Button size="sm" variant="ghost" onClick={()=>set_selected_row(null)}>close</Button></CardTitle></CardHeader><CardContent className="p-4 pt-0 space-y-3"><FieldGrid row={selected_row}/><div><div className="text-xs font-semibold mb-1">raw_text_preview</div><pre className="text-[11px] whitespace-pre-wrap bg-muted/30 rounded p-2 max-h-60 overflow-auto">{selected_row.raw_text_preview||"no_raw_text"}</pre></div><div><div className="text-xs font-semibold mb-1">payload_preview</div><pre className="text-[10px] whitespace-pre-wrap bg-muted/30 rounded p-2 max-h-80 overflow-auto">{selected_row.payload?JSON.stringify(selected_row.payload,null,2):"no_payload"}</pre></div></CardContent></Card>}
  </div>;
}
