/* ═══════════════════════════════════════════════════════════════════════
   LUMINARI — ANOMALY VIEWFINDER — 56-JURISDICTION DATA
   All 50 states + DC + 5 US territories.
   All data sourced from the Luminari State Registry.
   ═══════════════════════════════════════════════════════════════════════ */

export interface StateData {
  name: string;
  fips: string;
  pop: string;
  exp: boolean;
  ui: number;
  uiWk: number;
  wage: number;
  tanf: number;
  wageSol: number;
  crSol: number;
  port: number;
  lgbtq: boolean;
  tribes: string[];
  flags: string[];
  alerts: string[];
}

export const STATES: StateData[] = [
  { name:'Alabama', fips:'01', pop:'5.1M', exp:false, ui:275, uiWk:20, wage:7.25, tanf:215, wageSol:2, crSol:180, port:50, lgbtq:false, tribes:['Poarch Creek'], flags:['No expansion','$275/wk UI','Short appeals','No LGBTQ+ protection'], alerts:['12-day UI appeal — one of shortest in registry','Medicaid not expanded — no coverage pathway for working adults','Alabama Black Belt: phone-only routing for 10 rural counties'] },
  { name:'Alaska', fips:'02', pop:'733K', exp:true, ui:370, uiWk:26, wage:11.73, tanf:923, wageSol:2, crSol:300, port:53, lgbtq:true, tribes:['229 Alaska Native Tribes'], flags:['229 tribes','75% off-road','PFD annual dividend','Lowest UI for expansion state'], alerts:['Permanent Fund Dividend (~$1,300/yr) — income for benefit eligibility in October','75% of communities accessible only by plane or boat — phone intake only','ANTHC replaces standard IHS routing for Alaska Native members'] },
  { name:'American Samoa', fips:'60', pop:'55K', exp:false, ui:150, uiWk:20, wage:7.25, tanf:200, wageSol:2, crSol:180, port:28, lgbtq:false, tribes:[], flags:['US nationals not citizens','No UI system','Smallest Medicaid block grant','Fa\'asamoa customary law'], alerts:['American Samoans are US NATIONALS not citizens — cannot vote even if they move to a state','No formal UI system — wage loss has no safety net; immediate SNAP/food assistance routing','Fa\'asamoa (Samoan Way) customary law governs land and family — Western legal frameworks may not apply'] },
  { name:'Arizona', fips:'04', pop:'7.4M', exp:true, ui:320, uiWk:26, wage:14.35, tanf:278, wageSol:1, crSol:300, port:56, lgbtq:true, tribes:['Navajo Nation','Tohono O\'odham','Salt River Pima-Maricopa'], flags:['1-yr wage SOL','Navajo Nation tri-state','Strong tribal presence'], alerts:['1-year wage SOL is shorter than FLSA 2-year — use federal pathway','Navajo Nation spans AZ/NM/UT — route to Window Rock programs first','Tohono O\'odham spans US-Mexico border — immigration complexity'] },
  { name:'Arkansas', fips:'05', pop:'3.1M', exp:true, ui:451, uiWk:16, wage:11, tanf:204, wageSol:2, crSol:180, port:53, lgbtq:false, tribes:[], flags:['16-wk UI','ARHOME private option','24-mo TANF limit','No LGBTQ+'], alerts:['16-week UI — shortest in nation; pair with SNAP immediately when filing','ARHOME is private-option Medicaid — verify network at intake','Marshallese COFA community in Springdale (~15,000) — COMPIE: 479-316-0050'] },
  { name:'California', fips:'06', pop:'39.5M', exp:true, ui:450, uiWk:52, wage:16, tanf:1106, wageSol:3, crSol:300, port:58, lgbtq:true, tribes:['109 tribes'], flags:['52-week UI','$1,106 TANF','Paid family leave','Strong labor law'], alerts:['CalWORKs TANF: $1,106/month — highest in registry for standard family of 3','SDI + PFL provide 60–70% wage replacement for illness/bonding — screen at every intake','109 federally recognized tribes — verify specific tribal program before routing'] },
  { name:'Colorado', fips:'08', pop:'5.8M', exp:true, ui:781, uiWk:26, wage:14.42, tanf:508, wageSol:3, crSol:180, port:58, lgbtq:true, tribes:['Ute Mountain Ute','Southern Ute'], flags:['Strong UI','3-yr wage SOL','LGBTQ+ covered'], alerts:['Colorado CCRD 180-day SOL — file simultaneously with EEOC','Colorado Pays Family and Medical Leave (FAMLI) launched 2024 — screen at every intake'] },
  { name:'Connecticut', fips:'09', pop:'3.6M', exp:true, ui:781, uiWk:26, wage:16.35, tanf:693, wageSol:2, crSol:300, port:57, lgbtq:true, tribes:['Mashantucket Pequot','Mohegan'], flags:['Highest min wage','Right to counsel eviction','Winter shutoff protection','HUSKY D for undocumented children'], alerts:['Right to counsel in eviction for qualifying income levels — file immediately','Winter shutoff moratorium Nov 1 – May 1','Danbury: 40% Latin American immigrant — Make the Road CT: 203-553-4340'] },
  { name:'Delaware', fips:'10', pop:'1.0M', exp:true, ui:400, uiWk:26, wage:13.25, tanf:338, wageSol:3, crSol:120, port:56, lgbtq:true, tribes:[], flags:['120-day civil rights SOL','Shortest in nation','3-yr wage SOL'], alerts:['DDOL 120-day SOL — SHORTEST IN REGISTRY — always file EEOC same day','Sussex County: large Haitian Creole and Latino poultry workforce (Perdue/Allen Harim)','10-day UI appeal from mailing — contact legal aid within 5 days'] },
  { name:'District of Columbia', fips:'11', pop:'689K', exp:true, ui:444, uiWk:26, wage:17.5, tanf:712, wageSol:3, crSol:365, port:60, lgbtq:true, tribes:[], flags:['Highest min wage $17.50','No voting representation in Congress','OHR 365-day SOL','Strongest tenant protections'], alerts:['DC OHR 365-day SOL — tied with WV for longest civil rights filing window in registry','No voting representation in Congress — DC residents pay federal taxes without full representation','DC TANF: $712/month with strong wraparound services — screen for all at intake'] },
  { name:'Florida', fips:'12', pop:'22.6M', exp:false, ui:275, uiWk:12, wage:13, tanf:303, wageSol:4, crSol:365, port:53, lgbtq:false, tribes:['Seminole Tribe of Florida','Miccosukee'], flags:['12-week UI','No expansion','4-yr wage SOL'], alerts:['12-week UI maximum — second shortest in nation after AR (16 wks) — apply for everything immediately','Medicaid not expanded — large uninsured working population','4-year wage SOL is stronger than FLSA — use FL statute for older claims'] },
  { name:'Georgia', fips:'13', pop:'11.0M', exp:false, ui:365, uiWk:20, wage:7.25, tanf:280, wageSol:2, crSol:180, port:50, lgbtq:false, tribes:['Eastern Band Cherokee (NC-based operations in GA)'], flags:['No expansion','Low TANF','Federal min wage','No LGBTQ+'], alerts:['Medicaid not expanded — large uninsured population in rural south Georgia','GECRC 180-day SOL — file EEOC simultaneously'] },
  { name:'Guam', fips:'66', pop:'170K', exp:false, ui:280, uiWk:26, wage:9.25, tanf:330, wageSol:2, crSol:180, port:42, lgbtq:false, tribes:['Chamorro'], flags:['No IHS for Chamorro','Military 27% land','Block-granted Medicaid','COFA migrants'], alerts:['Chamorro people have NO Indian Health Service access despite indigenous status — route to Guam Memorial Hospital','Military controls 27% of island land — housing market severely constrained','COFA migrants from FSM/Palau/RMI eligible for Medicaid post-2020 — verify enrollment'] },
  { name:'Hawaii', fips:'15', pop:'1.4M', exp:true, ui:793, uiWk:26, wage:14, tanf:827, wageSol:6, crSol:180, port:54, lgbtq:true, tribes:['Native Hawaiian (non-IHS)'], flags:['PHCA employer mandate','6-yr wage SOL','Non-IHS Native Hawaiians','High cost of living'], alerts:['Hawaii PHCA: employer must cover workers at 20+ hrs/wk — check before Medicaid routing','Native Hawaiians are NOT IHS-eligible — route to OHA (808-594-1888) and Lili\'uokalani Trust','6-year wage SOL — longest in registry; assess back 6 years at every wage intake'] },
  { name:'Idaho', fips:'16', pop:'2.0M', exp:true, ui:518, uiWk:26, wage:7.25, tanf:309, wageSol:3, crSol:365, port:55, lgbtq:false, tribes:['Nez Perce','Shoshone-Bannock','Coeur d\'Alene'], flags:['1-yr ICHR SOL','Boise housing crisis','Snake River ag corridor'], alerts:['ICHR 1-year SOL — file EEOC simultaneously','Boise-Nampa: one of fastest-growing metros, extreme housing cost surge since 2020','Snake River Plain dairy/potato corridor: Latino/Haitian workforce — Idaho Legal Aid Twin Falls: 208-733-2490'] },
  { name:'Illinois', fips:'17', pop:'12.6M', exp:true, ui:742, uiWk:26, wage:14, tanf:762, wageSol:3, crSol:300, port:58, lgbtq:true, tribes:[], flags:['Strong benefits','Chicago local min wage','IDHR 300-day SOL'], alerts:['Chicago min wage $15.80 — higher than state $14; verify location','Illinois Human Rights Act: broad protected classes including arrest record'] },
  { name:'Indiana', fips:'18', pop:'6.8M', exp:true, ui:390, uiWk:26, wage:7.25, tanf:288, wageSol:2, crSol:180, port:55, lgbtq:false, tribes:[], flags:['No LGBTQ+ protection','Federal min wage','ICRC 180-day SOL'], alerts:['ICRC 180-day SOL — file EEOC simultaneously','No state LGBTQ+ protection — federal EEOC Bostock is only pathway'] },
  { name:'Iowa', fips:'19', pop:'3.2M', exp:true, ui:650, uiWk:26, wage:7.25, tanf:426, wageSol:2, crSol:300, port:54, lgbtq:true, tribes:['Meskwaki Nation'], flags:['Preempts local min wage','Federal floor only','ICRC covers LGBTQ+'], alerts:['Iowa preempts local minimum wage ordinances — no city can set floor above $7.25','Meatpacking corridor: Somali, Sudanese, Latino workers in Waterloo, Storm Lake, Postville'] },
  { name:'Kansas', fips:'20', pop:'2.9M', exp:false, ui:488, uiWk:16, wage:7.25, tanf:429, wageSol:2, crSol:180, port:51, lgbtq:false, tribes:['Prairie Band Potawatomi','Kickapoo'], flags:['No expansion','16-wk UI','180-day KHRC SOL','No LGBTQ+'], alerts:['16-week UI — tied shortest in nation with AR','SW Kansas meatpacking: Somali, Burmese Karen, Latino workers in Garden City/Liberal/Dodge City','Medicaid not expanded — large uninsured meatpacking workforce'] },
  { name:'Kentucky', fips:'21', pop:'4.5M', exp:true, ui:618, uiWk:26, wage:7.25, tanf:262, wageSol:5, crSol:180, port:56, lgbtq:false, tribes:[], flags:['5-yr wage SOL','Medicaid expanded','No LGBTQ+'], alerts:['5-year KY wage SOL — tied longest in registry with MT — always calculate back 5 years','KCHR 180-day SOL — file EEOC simultaneously','Eastern Kentucky coalfields: poverty mirrors WV pattern — phone-first routing'] },
  { name:'Louisiana', fips:'22', pop:'4.6M', exp:true, ui:247, uiWk:26, wage:7.25, tanf:240, wageSol:3, crSol:180, port:52, lgbtq:false, tribes:['Chitimacha','Coushatta','Jena Choctaw','Tunica-Biloxi'], flags:['$247/wk UI','24-mo TANF limit','United Houma non-IHS','No LGBTQ+'], alerts:['$247/wk UI — second lowest in registry; pair with SNAP and food bank immediately','United Houma Nation is state-recognized only — NO IHS, no federal tribal programs (17,000 members)','24-month state TANF limit — shorter than federal 60-month'] },
  { name:'Maine', fips:'23', pop:'1.4M', exp:true, ui:445, uiWk:26, wage:14.15, tanf:485, wageSol:6, crSol:180, port:56, lgbtq:true, tribes:['Penobscot','Passamaquoddy','Maliseet','Micmac'], flags:['180-day MHRC SOL','Wabanaki MICSA constraint','6-yr contract wage SOL','Lewiston Somali community'], alerts:['MHRC 180-day SOL — shortest in New England — always file EEOC simultaneously','Wabanaki tribes under MICSA 1980: federally recognized but subject to Maine state law — constrained sovereignty unique in registry','6-year breach-of-contract wage SOL — assess at every wage intake'] },
  { name:'Maryland', fips:'24', pop:'6.2M', exp:true, ui:430, uiWk:26, wage:15, tanf:714, wageSol:3, crSol:180, port:58, lgbtq:true, tribes:[], flags:['$714 TANF','Treble wage damages','MCCR 180-day SOL','Rent escrow remedy'], alerts:['MWPCL treble damages for willful nonpayment — always assess private lawsuit','MCCR 180-day SOL — shorter than EEOC — file simultaneously','Rent escrow: tenant may pay rent into court until repairs made — powerful MD-specific remedy'] },
  { name:'Massachusetts', fips:'25', pop:'7.0M', exp:true, ui:1015, uiWk:30, wage:15, tanf:828, wageSol:3, crSol:300, port:55, lgbtq:true, tribes:['Mashpee Wampanoag','Aquinnah Wampanoag'], flags:['$1,015/wk UI','Mandatory treble damages','Shelter right for families','30-wk UI'], alerts:['MA Wage Act: MANDATORY 3× damages — not discretionary, not just for willful — strongest in registry','Right to emergency shelter for families with children — legally enforceable (GL c.23B)','Springfield: ~30% poverty, majority Puerto Rican — Hampden County Legal Aid: 413-781-7814'] },
  { name:'Michigan', fips:'26', pop:'10.0M', exp:true, ui:362, uiWk:20, wage:10.33, tanf:541, wageSol:6, crSol:300, port:54, lgbtq:true, tribes:['Little Traverse Bay Bands','Sault Ste. Marie Chippewa','Grand Traverse Band','12 total'], flags:['6-yr wage SOL','20-wk UI (shorter)','LGBTQ+ covered','12 tribes'], alerts:['Michigan WDCA 6-year wage SOL — longest contractual window; assess back 6 years','20-week UI is shorter than national standard — apply for all other supports immediately','Flint water crisis legacy: infrastructure rights ongoing — Genesee County routing'] },
  { name:'Minnesota', fips:'27', pop:'5.7M', exp:true, ui:857, uiWk:26, wage:10.85, tanf:532, wageSol:2, crSol:365, port:52, lgbtq:true, tribes:['Red Lake Nation','White Earth Nation','Leech Lake Band','11 total'], flags:['$857/wk UI','MDHR 1-year SOL','Strong tribal presence','Somali community Minneapolis'], alerts:['MDHR 365-day SOL — tied longest state civil rights window with WV','Minneapolis Somali community (~100,000) — largest outside East Africa — specialized routing required','11 federally recognized tribes — verify specific nation before routing'] },
  { name:'Mississippi', fips:'28', pop:'2.9M', exp:false, ui:235, uiWk:26, wage:7.25, tanf:170, wageSol:2, crSol:180, port:49, lgbtq:false, tribes:['Mississippi Band of Choctaw Indians'], flags:['Floor state','$235/wk UI','$170/mo TANF','No min wage law','No expansion','Jackson water crisis'], alerts:['FLOOR STATE — lowest benefit environment in entire registry','No state minimum wage law — WHD is the ONLY wage enforcement mechanism','Jackson water infrastructure crisis ongoing — ask about current water access status','Mississippi Delta: 30–45% poverty rates — phone-first routing; limited broadband'] },
  { name:'Missouri', fips:'29', pop:'6.2M', exp:true, ui:320, uiWk:20, wage:12.3, tanf:292, wageSol:2, crSol:180, port:58, lgbtq:false, tribes:[], flags:['Canonical reference state','58% portability','MHRA 180-day SOL'], alerts:['Missouri is the canonical portability baseline (58%) — the reference against which all other states are measured','MHRA 180-day SOL — file EEOC simultaneously','20-week UI — shorter than national standard; apply for other supports when filing'] },
  { name:'Montana', fips:'30', pop:'1.1M', exp:true, ui:552, uiWk:28, wage:10.3, tanf:502, wageSol:5, crSol:180, port:57, lgbtq:true, tribes:['Blackfeet','Crow','Fort Peck','Fort Belknap','Rocky Boy\'s','Northern Cheyenne','Confederated Salish and Kootenai'], flags:['5-yr wage SOL','7 tribes','28-wk UI','Hi-Line isolation'], alerts:['Montana Wage Act 5-year SOL — tied longest in registry — always calculate back 5 years','Hi-Line (US Route 2): extreme rural isolation — phone-first routing; confirm internet access','7 federally recognized tribes covering ~13% of state land area — verify specific tribe'] },
  { name:'Nebraska', fips:'31', pop:'2.0M', exp:true, ui:440, uiWk:20, wage:13.5, tanf:440, wageSol:3, crSol:300, port:54, lgbtq:false, tribes:['Omaha Tribe'], flags:['Expanded 2020','20-wk UI','Sudanese community Omaha','Meatpacking corridor'], alerts:['Omaha has one of largest per-capita South Sudanese refugee populations in US','Meatpacking corridor: JBS, Cargill, Tyson — Somali, Marshallese, Latino workers in Columbus/Lexington/Schuyler','NEOC 300-day SOL — file EEOC simultaneously'] },
  { name:'Nevada', fips:'32', pop:'3.2M', exp:true, ui:469, uiWk:26, wage:12, tanf:477, wageSol:2, crSol:300, port:55, lgbtq:true, tribes:['Walker River Paiute','Pyramid Lake Paiute','27 total'], flags:['Culinary Union 226','27 tribes','Undocumented hospitality workforce','NERC 300-day SOL'], alerts:['Culinary Workers Union Local 226 (702-385-2131) covers ~60,000 LV hospitality workers — check union membership before routing','27 federally recognized tribes dispersed across rural desert','11-day UI appeal — contact legal aid within 5 days of denial'] },
  { name:'New Hampshire', fips:'33', pop:'1.4M', exp:true, ui:427, uiWk:26, wage:7.25, tanf:675, wageSol:3, crSol:180, port:55, lgbtq:true, tribes:[], flags:['Politically fragile expansion','Federal min wage','Karen refugee community Manchester'], alerts:['NH Health Protection Program has been renewed multiple times — politically fragile; verify current status','Manchester Karen (Burmese) refugee community — specialized language routing required','Federal min wage $7.25 — no state increase'] },
  { name:'New Jersey', fips:'34', pop:'9.3M', exp:true, ui:875, uiWk:26, wage:15.49, tanf:424, wageSol:2, crSol:730, port:57, lgbtq:true, tribes:[], flags:['$875/wk UI','NJLAD 2-year SOL','No damages cap','TDI + FLI'], alerts:['NJLAD: 2-year SOL + no damages cap — strongest state civil rights law in registry','7-day UI appeal — tied shortest in registry — contact legal aid within 3 days of denial','NJ TDI (85% wages up to $1,025/wk) and FLI (12 weeks paid leave) — screen at every intake'] },
  { name:'New Mexico', fips:'35', pop:'2.1M', exp:true, ui:511, uiWk:26, wage:12, tanf:447, wageSol:3, crSol:300, port:55, lgbtq:true, tribes:['Navajo Nation','19 Pueblos','Jicarilla Apache','Mescalero Apache','23 total'], flags:['Highest poverty in registry (~19%)','23 tribes','Navajo Nation','Colonias (border communities)'], alerts:['~19% poverty rate — highest in registry, exceeds Mississippi','Navajo Nation: largest reservation by area, own government and IHS — route enrolled Diné members to tribal programs first','Colonias (Doña Ana/Hidalgo/Luna/Otero): unincorporated border communities lacking municipal water and sewage'] },
  { name:'New York', fips:'36', pop:'19.8M', exp:true, ui:504, uiWk:26, wage:16, tanf:789, wageSol:6, crSol:300, port:57, lgbtq:true, tribes:['Seneca Nation','Haudenosaunee Confederacy','8 total'], flags:['$16/hr min wage NYC area','6-yr wage SOL','NYSDHR 3-year SOL','Strong tenant protections'], alerts:['NYC areas $16/hr min wage — verify applicable local rate','NYSDHR has 3-year SOL for housing complaints — longer than EEOC','NY Good Cause Eviction (2024): many tenants now have just-cause protection statewide'] },
  { name:'North Carolina', fips:'37', pop:'10.7M', exp:true, ui:350, uiWk:20, wage:7.25, tanf:272, wageSol:2, crSol:180, port:51, lgbtq:false, tribes:['Eastern Band Cherokee Indians'], flags:['7-day UI appeal','Expanded 2023','Federal min wage','No LGBTQ+'], alerts:['7-day UI appeal — tied shortest in registry — contact legal aid within 3 days of denial','Medicaid expanded November 2023 — still maturing, verify provider networks','Eastern Band Cherokee has its own IHS-compacted health system — Qualla Boundary is tribal jurisdiction'] },
  { name:'North Dakota', fips:'38', pop:'780K', exp:false, ui:618, uiWk:26, wage:7.25, tanf:477, wageSol:3, crSol:300, port:52, lgbtq:false, tribes:['Standing Rock Sioux','MHA Nation (Three Affiliated)','Spirit Lake','Turtle Mountain Chippewa','Sisseton Wahpeton Oyate'], flags:['No expansion','5 tribes','MHA Nation oil disruption','Federal min wage'], alerts:['Medicaid not expanded — coverage gap for working adults','MHA Nation sits in Bakken oil field — oil disruption + human trafficking from man-camp culture affects reservation','NDHRC 300-day SOL — no state LGBTQ+ protection; file EEOC'] },
  { name:'Northern Mariana Islands', fips:'69', pop:'47K', exp:false, ui:200, uiWk:20, wage:7.25, tanf:250, wageSol:2, crSol:180, port:32, lgbtq:false, tribes:['Chamorro','Carolinian'], flags:['CNMI-only immigration system','CW-1 visa workers','Block-granted Medicaid','Smallest US jurisdiction'], alerts:['CNMI has its OWN immigration system separate from mainland US — CW-1 visa workers have unique vulnerabilities','Block-granted Medicaid with smallest per-capita allocation in registry','Post-Super Typhoon Yutu (2018) infrastructure still recovering in northern islands'] },
  { name:'Ohio', fips:'39', pop:'11.8M', exp:true, ui:583, uiWk:26, wage:10.45, tanf:434, wageSol:2, crSol:365, port:57, lgbtq:true, tribes:[], flags:['OCRC 1-year SOL','Appalachian SE Ohio','Strong UI'], alerts:['OCRC has 1-year SOL — 65 days longer than EEOC — meaningful backup window','SE Ohio Appalachian counties mirror WV poverty patterns — phone-first routing','Columbus Somali community (~50,000) — specialized routing required'] },
  { name:'Oklahoma', fips:'40', pop:'4.0M', exp:true, ui:539, uiWk:26, wage:7.25, tanf:292, wageSol:3, crSol:180, port:54, lgbtq:false, tribes:['Cherokee Nation','Choctaw Nation','Chickasaw Nation','Muscogee Creek','Seminole','34 more'], flags:['McGirt 2020 — half of eastern OK is Indian Country','39 tribes','SoonerCare expanded 2021','No LGBTQ+'], alerts:['McGirt v. Oklahoma (2020): half of eastern Oklahoma including most of Tulsa is Indian Country for enrolled tribal members — confirm tribal enrollment at intake','39 federally recognized tribes — most in continental US — IHS OKC Area: 405-951-3768','Tulsa Greenwood District: ongoing legacy of 1921 Race Massacre — specialized community routing'] },
  { name:'Oregon', fips:'41', pop:'4.3M', exp:true, ui:783, uiWk:26, wage:14.2, tanf:668, wageSol:6, crSol:365, port:57, lgbtq:true, tribes:['Confederated Tribes Warm Springs','Confederated Tribes Umatilla','9 total'], flags:['6-yr wage SOL','BOLI strong enforcement','$783/wk UI','1-year BOLI SOL'], alerts:['Oregon BOLI 1-year SOL plus 6-year wage SOL — strong combined enforcement pathway','Oregon Health Plan (Medicaid) has among most generous eligibility in registry','Portland homeless crisis: right-to-shelter ballot measure passed 2020 — enforcement ongoing'] },
  { name:'Pennsylvania', fips:'42', pop:'13.0M', exp:true, ui:561, uiWk:26, wage:7.25, tanf:428, wageSol:3, crSol:300, port:57, lgbtq:true, tribes:[], flags:['PHRA 300-day SOL','Philadelphia local min wage (city workers)','Strong legal aid infrastructure'], alerts:['Pennsylvania PHRA: 300-day SOL, broad protected classes, strong private action','Pittsburgh and rural PA have significantly different resource landscapes — confirm location','Federal min wage for private employees — Philadelphia and Pittsburgh had local floors struck down by court'] },
  { name:'Puerto Rico', fips:'72', pop:'3.2M', exp:true, ui:190, uiWk:26, wage:10.5, tanf:180, wageSol:3, crSol:300, port:38, lgbtq:true, tribes:[], flags:['Block-granted Medicaid','Post-hurricane infrastructure','Spanish-language primary','Lowest UI in registry'], alerts:['Block-granted Medicaid — federal funding cap creates coverage gaps not seen in states','Post-Maria/Fiona infrastructure still degraded in mountain municipalities — phone routing only','$190/wk UI maximum — lowest in entire registry; pair with SNAP/PAN immediately'] },
  { name:'Rhode Island', fips:'44', pop:'1.1M', exp:true, ui:770, uiWk:26, wage:14, tanf:554, wageSol:3, crSol:365, port:57, lgbtq:true, tribes:['Narragansett Indian Tribe'], flags:['RICHR 1-year SOL','$770/wk UI','Cold Weather Rule','Right-to-counsel pilot'], alerts:['RICHR 1-year SOL — 65 days longer than EEOC — meaningful backup window','Cold Weather Rule: no shutoff Nov 1 – Apr 15 for residential customers who apply for protected status','Central Falls: 83% Latino, ~35% poverty — highest poverty rate in RI'] },
  { name:'South Carolina', fips:'45', pop:'5.3M', exp:false, ui:326, uiWk:20, wage:7.25, tanf:270, wageSol:3, crSol:180, port:53, lgbtq:false, tribes:['Catawba Indian Nation'], flags:['7-day UI appeal','No expansion','Federal min wage','No LGBTQ+'], alerts:['7-day UI appeal — tied shortest in registry — contact legal aid within 3 days of denial','Medicaid not expanded — large uninsured population in rural counties','Catawba Nation 2016 federal recognition restored — verify IHS eligibility for enrolled members'] },
  { name:'South Dakota', fips:'46', pop:'910K', exp:true, ui:693, uiWk:26, wage:11.2, tanf:583, wageSol:3, crSol:180, port:53, lgbtq:false, tribes:['Oglala Sioux','Rosebud Sioux','Cheyenne River Sioux','Crow Creek','Lower Brule','Flandreau Santee','Sisseton Wahpeton Oyate'], flags:['Expanded July 2023 (maturing)','Pine Ridge = deepest poverty','7 Lakota tribes','SDDHR 180-day SOL'], alerts:['Oglala Lakota County (Pine Ridge) ~50% poverty rate — deepest concentrated poverty in entire registry','Medicaid expansion July 2023 — still maturing, provider networks still building out','7-day UI appeal: contact SD Legal Aid within 5 days of any denial'] },
  { name:'Tennessee', fips:'47', pop:'7.1M', exp:false, ui:275, uiWk:26, wage:7.25, tanf:185, wageSol:2, crSol:180, port:50, lgbtq:false, tribes:[], flags:['No expansion','$275/wk UI (tied lowest with AL)','Federal min wage','No LGBTQ+'], alerts:['Medicaid not expanded — coverage gap for large working population','$275/wk UI tied lowest with Alabama','THRA 180-day SOL — file EEOC simultaneously'] },
  { name:'Texas', fips:'48', pop:'30.0M', exp:false, ui:563, uiWk:26, wage:7.25, tanf:260, wageSol:2, crSol:180, port:53, lgbtq:false, tribes:['Alabama-Coushatta','Kickapoo Traditional Tribe','Ysleta del Sur Pueblo'], flags:['No expansion','Largest non-expansion state','Federal min wage','No LGBTQ+','3 tribes'], alerts:['Medicaid not expanded — largest coverage gap in registry by population (~5M uninsured working adults)','TCHR 180-day SOL — file EEOC simultaneously; no state LGBTQ+ protection','Rio Grande Valley colonias: unincorporated communities lacking basic infrastructure along TX-Mexico border'] },
  { name:'US Virgin Islands', fips:'78', pop:'87K', exp:false, ui:506, uiWk:26, wage:10.5, tanf:360, wageSol:2, crSol:180, port:40, lgbtq:true, tribes:[], flags:['Block-granted Medicaid','Post-hurricane recovery','Three-island jurisdiction','Danish colonial law remnants'], alerts:['Three separate islands (St. Thomas, St. Croix, St. John) — services differ by island; confirm location at intake','Block-granted Medicaid — federal funding cap creates coverage gaps','Post-Irma/Maria recovery still ongoing — infrastructure fragile in rural St. Croix'] },
  { name:'Utah', fips:'49', pop:'3.4M', exp:true, ui:660, uiWk:26, wage:7.25, tanf:493, wageSol:2, crSol:180, port:56, lgbtq:true, tribes:['Navajo Nation (San Juan County)','Ute Indian Tribe (Uintah)'], flags:['LGBTQ+ covered (2015)','San Juan County: Navajo Nation 50% population','Tongan/Pacific Islander community SLC'], alerts:['San Juan County: ~50% enrolled Navajo Nation — most isolated territory in registry; assume no internet, limited cell','Ute Indian Tribe: oil revenue supplements tribal services — Fort Duchesne: 435-722-5141','UADD 180-day SOL — file EEOC simultaneously'] },
  { name:'Vermont', fips:'50', pop:'648K', exp:true, ui:583, uiWk:26, wage:13.67, tanf:693, wageSol:6, crSol:365, port:57, lgbtq:true, tribes:['Abenaki (state-recognized, not federal)'], flags:['6-yr contract wage SOL','Dr. Dynasaur (children regardless of immigration status)','Most rural state in registry','VHRC 1-year SOL'], alerts:['Dr. Dynasaur: children up to 18 covered regardless of immigration status — always check for children in family','6-year breach-of-contract wage SOL tied longest in registry with HI','Vermont is most rural state by proportion — phone intake essential for all non-Burlington clients'] },
  { name:'Virginia', fips:'51', pop:'8.7M', exp:true, ui:378, uiWk:26, wage:12, tanf:389, wageSol:3, crSol:300, port:56, lgbtq:true, tribes:['Pamunkey Nation','Chickahominy','Monacan Nation','11 total'], flags:['Virginia Values Act','VCHR 300-day SOL','Northern VA wealth gap vs. SW VA poverty'], alerts:['Virginia Values Act: strong state LGBTQ+ protections since 2020','SW Virginia Appalachian counties share WV poverty patterns — phone-first routing','11 state-recognized tribes; Pamunkey Nation received federal recognition 2015'] },
  { name:'Washington', fips:'53', pop:'7.8M', exp:true, ui:929, uiWk:26, wage:16.28, tanf:1180, wageSol:3, crSol:300, port:58, lgbtq:true, tribes:['29 federally recognized tribes','Quinault','Lummi','Tulalip','Puyallup'], flags:['$1,180 TANF highest in registry','$929/wk UI','$16.28 min wage','Paid family leave'], alerts:['WA TANF: $1,180/month — highest in registry for standard family of 3','WA Paid Family and Medical Leave: up to 90% wages, 12–18 weeks — screen at every intake','29 federally recognized tribes — Columbia River treaty fishing rights have separate enforcement pathway'] },
  { name:'West Virginia', fips:'54', pop:'1.8M', exp:true, ui:521, uiWk:26, wage:8.75, tanf:397, wageSol:3, crSol:365, port:57, lgbtq:true, tribes:[], flags:['WVHRC 365-day SOL — longest in registry','Highest per-capita overdose rate US','3-yr wage SOL','Southern coalfields poverty'], alerts:['WVHRC 365-day SOL — LONGEST STATE CIVIL RIGHTS WINDOW IN REGISTRY — 65 days after EEOC closes','Highest per-capita opioid overdose death rate in US — screen SUD at every intake in southern WV','Southern coalfields (McDowell, Mingo, Logan, Wyoming) 20–35% poverty — phone-first routing'] },
  { name:'Wisconsin', fips:'55', pop:'5.9M', exp:true, ui:370, uiWk:26, wage:7.25, tanf:658, wageSol:2, crSol:300, port:56, lgbtq:true, tribes:['Bad River Band','Red Cliff Band','Menominee','Ho-Chunk Nation','11 total'], flags:['DEWS 300-day SOL','Federal min wage','11 tribes','Strong Hmong/Latino communities'], alerts:['Milwaukee Hmong community (~50,000) — specialized language routing required','11 federally recognized tribes — Menominee County is county with highest tribal population fraction in registry','Federal min wage $7.25 — no state increase'] },
  { name:'Wyoming', fips:'56', pop:'584K', exp:false, ui:508, uiWk:26, wage:7.25, tanf:572, wageSol:8, crSol:180, port:52, lgbtq:false, tribes:['Eastern Shoshone','Northern Arapaho (Wind River)'], flags:['Least populous state','No expansion','10-day UI appeal','Two separate tribes on one reservation'], alerts:['Wind River Reservation: TWO separate federally recognized tribes — Eastern Shoshone and Northern Arapaho — confirm which tribe before routing','Wyoming Legal Services (800-442-6170) is ONLY statewide legal aid — extremely limited capacity','10-day UI appeal — contact Wyoming Legal Services within 5 days of any denial'] },
];

/* ── ANOMALY CARDS ── */
export interface AnomalyCard {
  severity: 'critical' | 'warning' | 'info' | 'notable';
  type: string;
  title: string;
  body: string;
  tags: { label: string; bold?: string }[];
}

export const ANOMALIES: AnomalyCard[] = [
  { severity:'critical', type:'Critical Trap', title:"Delaware's 120-day civil rights deadline is the shortest in the nation", body:"While federal law gives workers 300 days to file a discrimination complaint, Delaware state law allows only 120 days. Miss it, and the state remedy is permanently gone \u2014 the federal clock is still running, but you've lost the state option. Most people don't know there are two separate deadlines until it's too late.", tags:[{bold:'DE',label:'120 days'},{bold:'Federal',label:'300 days'},{bold:'NJ',label:'2 years'},{label:'Same region \u00b7 6\u00d7 gap'}] },
  { severity:'critical', type:'Critical Trap', title:'Unemployment appeals in some states must be filed in 7 days', body:"New Jersey, South Carolina, and North Carolina require unemployment appeals within 7 days of mailing \u2014 before most people have even processed the denial, found legal aid, or gotten a callback. Massachusetts allows 10 days, Montana 20, most states 14\u201321. The same denial, radically different survival windows depending on zip code.", tags:[{bold:'NJ/SC/NC',label:'7 days'},{bold:'Most states',label:'14\u201321 days'},{bold:'CT',label:'21 days'}] },
  { severity:'critical', type:'Coverage Gap', title:'10 states still have no Medicaid expansion \u2014 adults fall into a coverage gap with no pathway', body:"In non-expansion states, adults who earn too much for traditional Medicaid but too little for marketplace subsidies are simply uninsured with no remedy. The ACA was designed assuming all states would expand \u2014 when they didn't, a gap was created that Congress never fixed. Mississippi is the most acute example: parents must earn below ~29% of the federal poverty level to qualify.", tags:[{bold:'MS',label:'parents <29% FPL only'},{bold:'10 states',label:'non-expansion'},{bold:'40 states',label:'expanded'}] },
  { severity:'critical', type:'Income Floor', title:"Mississippi unemployment pays $235/week \u2014 less than a studio apartment in most US cities", body:"Mississippi's maximum unemployment benefit is $235/week \u2014 the lowest in the nation. New Jersey's maximum is $1,015/week. A laid-off worker in Mississippi receives 23 cents for every dollar their New Jersey counterpart receives, performing the same job search, facing the same rent, buying the same groceries. The same federal program, but entirely state-controlled benefit levels.", tags:[{bold:'MS',label:'$235/week'},{bold:'NJ',label:'$1,015/week + dependents'},{bold:'Ratio',label:'23\u00a2 per dollar'}] },
  { severity:'warning', type:'Structural Anomaly', title:'Iowa preempts all local minimum wage ordinances \u2014 no city can set a higher floor', body:"Several states have passed preemption laws that prevent cities and counties from enacting higher minimum wages. Iowa is a clear example: despite being an expansion state with otherwise moderate policies, state law explicitly preempts local wage ordinances. A worker in Des Moines has the same $7.25/hr floor as rural areas, unlike Illinois where Chicago sets $15.80. Same state, zero local option.", tags:[{bold:'Iowa',label:'$7.25 (preemption)'},{bold:'Chicago IL',label:'$15.80'},{bold:'Portland OR',label:'higher than state'}] },
  { severity:'warning', type:'Structural Anomaly', title:'Arkansas UI runs out after 16 weeks \u2014 shortest duration in the nation', body:"Arkansas maximum unemployment duration is 16 weeks \u2014 tied with Kansas for the shortest in the country. The federal extended benefit trigger rarely activates in low-unemployment periods. The average job search in the US takes 5\u20136 months. In Arkansas, the clock runs out before most people find work, with no state bridge. The same is true in Kansas \u2014 both non-expansion states with below-average minimum wages.", tags:[{bold:'AR/KS',label:'16 weeks'},{bold:'National avg',label:'26 weeks'},{bold:'MA',label:'30 weeks'}] },
  { severity:'warning', type:'Structural Anomaly', title:"Maine's Wabanaki tribes have federal recognition but are subject to state law under a 1980 settlement", body:"The Maine Indian Claims Settlement Act (1980) required that four federally recognized Wabanaki tribes accept Maine state law jurisdiction as a condition of their land claim settlement. This is almost unique in federal Indian law \u2014 most federally recognized tribes have tribal sovereignty that supersedes state law in many civil matters. Maine Wabanaki members have tribal social services but significantly constrained sovereignty compared to tribes in every other state in the registry.", tags:[{bold:'ME',label:'MICSA 1980 constraint'},{bold:'Federal recognition',label:'without full sovereignty'},{label:'Nationally unique structure'}] },
  { severity:'warning', type:'Structural Anomaly', title:"Oklahoma's McGirt ruling created tribal jurisdiction over half the state overnight", body:"The Supreme Court's McGirt v. Oklahoma decision (2020) held that the Muscogee (Creek) Nation reservation was never legally disestablished \u2014 making approximately half of eastern Oklahoma, including most of Tulsa, Indian Country for criminal and civil jurisdictional purposes for enrolled tribal members. Subsequent decisions extended this to the Cherokee, Choctaw, Chickasaw, and Seminole Nations. No other state in the registry has this level of unresolved jurisdictional shift.", tags:[{bold:'McGirt 2020',label:'reservation intact'},{bold:'~3M acres',label:'per nation'},{bold:'Tulsa',label:'largely Indian Country'}] },
  { severity:'info', type:'Notable Provision', title:'Massachusetts wage theft law mandates triple damages \u2014 not discretionary', body:"Massachusetts Wage Act mandates treble (3\u00d7) damages for any wage violation \u2014 the court has no discretion to reduce them. If an employer owes $10,000, the judgment must be $30,000. This is the strongest wage theft deterrent in the registry. Most states allow courts to discretionarily award multiplied damages only for willful violations. West Virginia, Maryland, and New Jersey have strong wage laws but none mandate automatic trebling.", tags:[{bold:'MA',label:'mandatory 3\u00d7'},{bold:'MD',label:'treble for willful'},{bold:'NJ',label:'no damages cap'},{bold:'Most states',label:'1\u00d7 or 2\u00d7'}] },
  { severity:'info', type:'Notable Provision', title:'Hawaii requires employer health coverage for workers at 20+ hours per week \u2014 since 1974', body:"The Hawaii Prepaid Health Care Act (1974) requires employers to provide health insurance to any employee working 20 or more hours per week. This predated the ACA by 36 years and effectively created near-universal employment-based coverage. No other state in the registry has this requirement. It means that Hawaii's Medicaid is genuinely a last resort rather than the primary safety net, as it functions in most other states.", tags:[{bold:'HI PHCA',label:'since 1974'},{bold:'Threshold',label:'20+ hrs/week'},{label:'No other state equivalent'}] },
  { severity:'info', type:'Notable Provision', title:'Alaska pays residents an annual dividend just for living there', body:"Alaska's Permanent Fund Dividend pays every eligible Alaska resident approximately $1,000\u2013$2,000 per year from oil revenue \u2014 a form of universal basic income that has existed since 1982. For a family of four, this represents $4,000\u2013$8,000 in annual income, delivered in a single October payment. No other state in the registry has anything comparable. It is income for benefit eligibility purposes, which can temporarily affect SNAP and Medicaid calculations in the month of receipt.", tags:[{bold:'AK PFD',label:'~$1,300/year (2023)'},{bold:'Since',label:'1982'},{label:'Unique in US'}] },
  { severity:'info', type:'Notable Provision', title:"New Jersey's civil rights law has no damages cap and a 2-year filing window", body:"The New Jersey Law Against Discrimination (NJLAD) has a 2-year statute of limitations \u2014 the longest state civil rights SOL in the registry \u2014 and no cap on compensatory damages. In Delaware, the window is 120 days. In Mississippi, there is no state LGBTQ+ protection at all. In New Jersey, a discrimination victim has 730 days to file and can recover full compensatory damages without a statutory ceiling. The same federal workplace, two states apart, produces radically different legal remedies.", tags:[{bold:'NJLAD',label:'2 years'},{bold:'No cap',label:'on compensatory damages'},{bold:'DE',label:'120 days \u00b7 same region'}] },
];

/* ── HIDDEN PATTERNS ── */
export interface PatternRow {
  num: string;
  headline: string;
  body: string;
  category: string;
}

export const PATTERNS: PatternRow[] = [
  { num:'01', headline:'The United States has approximately five distinct benefit systems, not one', body:'The registry reveals six consistent governance ecosystems: <b>Deep South non-expansion</b> (MS, AL, LA, TN, GA), <b>Transitional South</b> (NC, VA, AR), <b>Conservative Expansion</b> (IN, KY, WY), <b>Moderate Expansion</b> (CO, MN, MI, WI), <b>Northeast Protection</b> (NJ, CT, MA, MD), and <b>Mountain West / Tribal Complexity</b> (MT, NM, UT, AK). A worker laid off in Mississippi and a worker laid off in Massachusetts are technically in the same federal system \u2014 practically, they are in entirely different countries.', category:'Structure' },
  { num:'02', headline:'Benefit amounts cluster by region \u2014 and the gaps have widened over decades', body:'TANF (cash assistance) ranges from <b>$170/month in Mississippi</b> to <b>$828/month in Massachusetts</b> for the same family of three. Unemployment ranges from <b>$235/week in Mississippi</b> to <b>$1,015/week in Massachusetts</b>. These gaps are not random \u2014 they trace the historic contours of Reconstruction-era labor policy, where Southern states deliberately set low benefit floors to preserve cheap agricultural and domestic labor. Those floors were never raised to parity.', category:'History' },
  { num:'03', headline:"States that didn't expand Medicaid also tend to have shorter UI, lower wages, and fewer civil rights protections", body:'Non-expansion is not an isolated policy choice \u2014 it correlates strongly with the entire benefit architecture. Of the 10 non-expansion states, <b>9 have the federal minimum wage</b>, <b>8 have UI maximums below $500/week</b>, and <b>7 have civil rights SOLs of 180 days or fewer with no LGBTQ+ state protection</b>. The decision not to expand Medicaid appears to be one expression of a broader governing philosophy about what the state owes its residents.', category:'Policy' },
  { num:'04', headline:'The same person in two different states can have access to radically different legal remedies for the exact same harm', body:'A worker whose employer stole wages has a <b>2-year window in most states</b>, a <b>3-year window in Maryland with treble damages</b>, a <b>5-year window in Montana and Kentucky</b>, and a <b>6-year window in Vermont and Hawaii</b>. A discrimination victim in New Jersey has 2 years and unlimited damages. The same victim in Mississippi has 180 days and no LGBTQ+ protection at all. Federal floors exist, but state law determines whether justice is practically accessible.', category:'Legal' },
  { num:'05', headline:'Tribal governance operates across three distinct tiers, and which tier a nation falls into determines most of what their members can access', body:'<b>Tier 1: Casino-funded sovereign systems</b> (Mashantucket Pequot, Mississippi Choctaw, Poarch Creek, Mohegan) \u2014 gaming revenue funds comprehensive social services independent of federal program adequacy. <b>Tier 2: IHS compact systems</b> (Cherokee, Navajo, Montana tribes) \u2014 federal program funding with tribal delivery. <b>Tier 3: State-recognized or non-recognized</b> (United Houma Nation of Louisiana, Virginia Tribal Nations pre-2018) \u2014 no IHS, no federal tribal programs, no gaming revenue. Tier 3 nations are invisible to the federal benefit system.', category:'Sovereignty' },
  { num:'06', headline:'Legal aid deserts are predictable \u2014 they follow the same geography as poverty', body:'Wyoming has one statewide legal aid organization. Mississippi\'s legal aid covers all 82 counties but is severely under-resourced. Alabama\'s Black Belt counties \u2014 the poorest in the state \u2014 are served almost exclusively by one number (Legal Services Alabama: 866-456-4995). The registry reveals that legal aid capacity is inversely correlated with need \u2014 the places with the most complex, high-stakes legal situations have the fewest attorneys per capita. Meanwhile, Connecticut introduced <b>right to counsel in eviction</b> statewide in 2022.', category:'Access' },
  { num:'07', headline:'Roughly 50\u201358% of every state\'s benefit navigation system is portable \u2014 the rest is state-specific', body:'After building 50 state registries from a single Missouri template, the same ~50\u201358% portability rate emerged in every state \u2014 from Massachusetts (55%) to Mississippi (49%). This means that about half of the knowledge needed to navigate any state\'s system can be pre-loaded from a universal base. The remaining half requires state-specific calibration: the right deadlines, the right contacts, the right anomalies. This finding has direct implications for how navigation systems should be built \u2014 modular, not monolithic.', category:'Architecture' },
  { num:'08', headline:'Meatpacking corridors create concentrated, high-risk worker populations that fall outside standard routing', body:'Kansas, Nebraska, Iowa, Arkansas, North Carolina, and Maryland all have meatpacking plant corridors employing Somali, South Sudanese, Marshallese, Guatemalan, and Mexican workers \u2014 often through labor staffing agencies that add a layer of liability insulation. These corridors share a pattern: workers with limited English, unstable immigration status, living in employer-adjacent housing, performing dangerous work, with wages controlled by a contractor rather than the plant. Standard benefit navigation doesn\'t reach them. The registry identifies <b>11 states</b> with significant meatpacking workforce communities requiring specialized routing.', category:'Community' },
  { num:'09', headline:'Geographic isolation is a policy problem \u2014 and it\'s concentrated in predictable places', body:'Alaska (75% of communities off the road system), rural Montana (Hi-Line corridor), Wyoming (Fremont County / Wind River), northeastern Maine (Aroostook County \u2014 the largest county east of the Mississippi), New Mexico\'s Navajo Nation territory, and South Dakota\'s Pine Ridge Reservation all share the same structural feature: residents are geographically isolated from the services they are legally entitled to. The legal right exists. The physical access does not. This gap is not an accident \u2014 it is the cumulative result of infrastructure investment decisions made over generations.', category:'Geography' },
  { num:'10', headline:'Benefit programs are designed assuming multiple supports work simultaneously \u2014 but most people only know about one at a time', body:'SNAP alone is insufficient for food security. TANF alone is insufficient for housing stability. UI alone rarely covers rent. Every state registry reveals that programs are calibrated assuming a household will layer SNAP + Medicaid + LIHEAP + local food bank + emergency rental assistance + legal aid simultaneously. The system was not designed for any single program to suffice. Yet most people navigate one program at a time, often because they don\'t know the others exist, miss deadlines for simultaneous applications, or encounter intake workers who specialize in only one program.', category:'Design' },
];
