import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Workflow, AlertTriangle, Scale, Lightbulb, FileText } from 'lucide-react';
import type { PipelineRun, ProceduralOutput, AuthorityConflict, NarrativeBiasFlag, AlternativeInterpretation } from '@/lib/types';

interface PipelineTabProps {
  pipelineRuns: PipelineRun[];
  proceduralOutputs: ProceduralOutput[];
  authorityConflicts: AuthorityConflict[];
  biasFlags: NarrativeBiasFlag[];
  altInterpretations: AlternativeInterpretation[];
}

export default function PipelineTab({
  pipelineRuns,
  proceduralOutputs,
  authorityConflicts,
  biasFlags,
  altInterpretations,
}: PipelineTabProps) {
  const hasAnyData = pipelineRuns.length > 0 || proceduralOutputs.length > 0 ||
    authorityConflicts.length > 0 || biasFlags.length > 0 || altInterpretations.length > 0;

  if (!hasAnyData) {
    return (
      <Card className="border-dashed">
        <CardContent className="flex flex-col items-center justify-center py-16">
          <Workflow className="w-10 h-10 text-muted-foreground mb-3" />
          <p className="text-sm text-muted-foreground">No pipeline analysis available yet.</p>
          <p className="text-xs text-muted-foreground mt-1">
            Pipeline outputs are generated by the backend analysis system.
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Pipeline Runs */}
      {pipelineRuns.length > 0 && (
        <section>
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-3">
            Pipeline Runs
          </h3>
          <div className="space-y-2">
            {pipelineRuns.map((run) => (
              <Card key={run.run_id}>
                <CardContent className="p-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <Workflow className="w-4 h-4 text-primary" />
                      <div>
                        <p className="text-sm font-medium text-foreground">
                          Pipeline v{run.pipeline_version}
                        </p>
                        <p className="text-xs text-muted-foreground">
                          {new Date(run.started_at).toLocaleString()}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline" className="text-xs capitalize">
                        {run.status}
                      </Badge>
                      <Badge variant="outline" className="text-xs">
                        Confidence: {run.overall_confidence}
                      </Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}

      {/* Procedural Outputs */}
      {proceduralOutputs.length > 0 && (
        <section>
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-3">
            Procedural Outputs
          </h3>
          <div className="space-y-2">
            {proceduralOutputs.map((output) => (
              <Card key={output.procedural_output_id}>
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <FileText className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="text-sm font-medium text-foreground">{output.title}</h4>
                        <Badge variant="outline" className="text-xs capitalize">{output.output_type}</Badge>
                        <Badge variant="outline" className="text-xs">
                          {output.confidence}
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground whitespace-pre-wrap">{output.content}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}

      {/* Authority Conflicts */}
      {authorityConflicts.length > 0 && (
        <section>
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-3">
            Authority Conflicts
          </h3>
          <div className="space-y-2">
            {authorityConflicts.map((conflict) => (
              <Card key={conflict.authority_conflict_id} className="border-amber-500/20">
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <Scale className="w-4 h-4 text-amber-400 mt-0.5 shrink-0" />
                    <div>
                      <p className="text-sm text-foreground">{conflict.description}</p>
                      {conflict.block_causal_inference && (
                        <p className="text-xs text-amber-400 mt-1">⚠ Blocks causal inference</p>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}

      {/* Narrative Bias Flags */}
      {biasFlags.length > 0 && (
        <section>
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-3">
            Narrative Bias Flags
          </h3>
          <div className="space-y-2">
            {biasFlags.map((flag) => (
              <Card key={flag.narrative_bias_flag_id} className="border-orange-500/20">
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <AlertTriangle className="w-4 h-4 text-orange-400 mt-0.5 shrink-0" />
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <Badge variant="outline" className="text-xs capitalize">{flag.bias_risk} risk</Badge>
                        {flag.dominant_source_type && (
                          <span className="text-xs text-muted-foreground">
                            Dominant: {flag.dominant_source_type} ({flag.dominant_source_percentage}%)
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-foreground">{flag.description}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}

      {/* Alternative Interpretations */}
      {altInterpretations.length > 0 && (
        <section>
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-3">
            Alternative Interpretations
          </h3>
          <div className="space-y-2">
            {altInterpretations.map((interp) => (
              <Card key={interp.alternative_interpretation_id}>
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <Lightbulb className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                    <div>
                      <p className="text-sm text-foreground">{interp.description}</p>
                      {Array.isArray(interp.interpretations) && interp.interpretations.length > 0 && (
                        <ul className="mt-2 space-y-1">
                          {(interp.interpretations as Array<{ text?: string }>).map((item, i) => (
                            <li key={i} className="text-xs text-muted-foreground">
                              • {typeof item === 'string' ? item : item.text || JSON.stringify(item)}
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
