/**
 * Phoenix Collision Test - Tight Execution
 * 
 * Forces a real collision:
 * Entity A: Renaissance 21 Childcare (UBI: f7e163b99a2c1, Debt: $2.2M)
 * Entity B: Renaissance Rising Childcare LLC (SAME UBI, SAME agent, Active)
 * 
 * Expected: Phoenix signal detecting entity resurrection
 * 
 * Run with: pnpm tsx server/phoenix-collision-test.ts
 */

import { injectForensicMetadata, queryForensicMetadata } from './forensic-db';

const TEST_CASE_ID = 8888;
const TEST_UBI = 'f7e163b99a2c1';
const TEST_AGENT = 'R. Doe';

async function phoenixCollisionTest() {
  console.log('\n🔴 PHOENIX COLLISION TEST - TIGHT EXECUTION\n');
  console.log('Forcing collision: Renaissance 21 → Renaissance Rising (shared UBI)\n');

  try {
    // STEP 1: Inject Entity A (Suspended)
    console.log('📋 STEP 1: Injecting Entity A (Renaissance 21 - Suspended)...');
    await injectForensicMetadata('forensic_entities', {
      case_id: TEST_CASE_ID,
      entity_value: 'Renaissance 21 Childcare',
      category: 'ORGANIZATION',
      ubi: TEST_UBI,
      status: 'Suspended',
      debt: 2200000,
      agent: TEST_AGENT,
      created_at: Date.now(),
    });
    console.log(`✅ Entity A injected\n`);

    // STEP 2: Inject Entity B (Active - SAME UBI)
    console.log('📋 STEP 2: Injecting Entity B (Renaissance Rising - Active, SAME UBI)...');
    await injectForensicMetadata('forensic_entities', {
      case_id: TEST_CASE_ID,
      entity_value: 'Renaissance Rising Childcare LLC',
      category: 'ORGANIZATION',
      ubi: TEST_UBI,  // ← COLLISION: Same UBI
      status: 'Active',
      agent: TEST_AGENT,  // ← COLLISION: Same agent
      created_at: Date.now(),
    });
    console.log(`✅ Entity B injected\n`);

    // STEP 3: Inject Agent (Shared)
    console.log('📋 STEP 3: Injecting Shared Agent...');
    await injectForensicMetadata('forensic_entities', {
      case_id: TEST_CASE_ID,
      entity_value: TEST_AGENT,
      category: 'PERSON',
      role: 'Registered Agent',
      created_at: Date.now(),
    });
    console.log(`✅ Agent injected\n`);

    // STEP 4: Query entities (HARD CHECK)
    console.log('📊 STEP 4: Querying entities (HARD CHECK)...\n');
    const entityQuery = `
      SELECT entity_value, category, ubi, status, agent
      FROM forensic_entities
      WHERE case_id = ?
      ORDER BY created_at DESC
    `;
    const entities = await queryForensicMetadata(entityQuery, [TEST_CASE_ID]);
    
    console.log(`Entity Count: ${entities.length}`);
    if (entities.length === 0) {
      console.error('❌ FAIL: No entities found');
      process.exit(1);
    }
    
    console.log('\nEntities:');
    (entities as any[]).forEach((e: any, i: number) => {
      console.log(`  ${i + 1}. ${e.entity_value}`);
      if (e.ubi) console.log(`     UBI: ${e.ubi}`);
      if (e.status) console.log(`     Status: ${e.status}`);
      if (e.agent) console.log(`     Agent: ${e.agent}`);
    });
    console.log();

    // STEP 5: Verify collision markers
    console.log('🔗 STEP 5: Verifying collision markers...\n');
    const ubiMatches = (entities as any[]).filter((e: any) => e.ubi === TEST_UBI);
    const agentMatches = (entities as any[]).filter((e: any) => e.agent === TEST_AGENT);
    
    console.log(`Shared UBI (${TEST_UBI}): ${ubiMatches.length} entities`);
    console.log(`Shared Agent (${TEST_AGENT}): ${agentMatches.length} entities`);
    
    if (ubiMatches.length < 2) {
      console.error('❌ FAIL: UBI collision not detected');
      process.exit(1);
    }
    console.log(`✅ Collision markers verified\n`);

    // STEP 6: Query relationships
    console.log('🔗 STEP 6: Querying relationships...\n');
    const relationshipQuery = `
      SELECT entity_a, entity_b, relationship_type, match_reason
      FROM entity_relationships
      WHERE case_id = ?
      ORDER BY created_at DESC
    `;
    
    try {
      const relationships = await queryForensicMetadata(relationshipQuery, [TEST_CASE_ID]);
      console.log(`Relationship Count: ${relationships.length}`);
      
      if (relationships.length > 0) {
        console.log('\nRelationships:');
        (relationships as any[]).forEach((r: any, i: number) => {
          console.log(`  ${i + 1}. ${r.entity_a} ↔ ${r.entity_b}`);
          console.log(`     Type: ${r.relationship_type}`);
          console.log(`     Reason: ${r.match_reason}`);
        });
      } else {
        console.log('⚠️  No relationships found (may be auto-generated by Phoenix)');
      }
      console.log();
    } catch (error: any) {
      console.log(`⚠️  Relationships table not available: ${error.message}\n`);
    }

    // STEP 7: Query signals
    console.log('📡 STEP 7: Querying signals...\n');
    const signalQuery = `
      SELECT signal_type, confidence_score, created_at, payload
      FROM signals
      WHERE case_id = ?
      ORDER BY created_at DESC
      LIMIT 5
    `;
    
    try {
      const signals = await queryForensicMetadata(signalQuery, [TEST_CASE_ID]);
      console.log(`Signal Count: ${signals.length}`);
      
      if (signals.length === 0) {
        console.warn('⚠️  No signals found yet (Phoenix may not have run)');
      } else {
        console.log('\nSignals:');
        (signals as any[]).forEach((s: any, i: number) => {
          console.log(`  ${i + 1}. ${s.signal_type}`);
          console.log(`     Confidence: ${s.confidence_score}`);
          console.log(`     Created: ${new Date(s.created_at).toISOString()}`);
          
          if (s.payload) {
            try {
              const payload = typeof s.payload === 'string' ? JSON.parse(s.payload) : s.payload;
              console.log(`     Payload: ${JSON.stringify(payload, null, 6).split('\n').slice(0, 5).join('\n')}...`);
            } catch (e) {
              console.log(`     Payload: ${s.payload}`);
            }
          }
        });
      }
      console.log();
    } catch (error: any) {
      console.log(`⚠️  Signals table not available: ${error.message}\n`);
    }

    // STEP 8: Summary
    console.log('📋 SUMMARY\n');
    console.log(`Case ID: ${TEST_CASE_ID}`);
    console.log(`Entities: ${entities.length}`);
    console.log(`Collision Type: Shared UBI + Shared Agent`);
    console.log(`Expected Signal: PHOENIX_ENTITY`);
    console.log(`Access Level: SYSTEM`);
    console.log('\n✅ TEST COMPLETE\n');

  } catch (error: any) {
    console.error('❌ Test failed:', error.message);
    console.error(error);
    process.exit(1);
  }
}

// Run the test
phoenixCollisionTest().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
