services:
  - type: web
    name: esquire
    runtime: static
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./dist/public
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://eombkfyeymqqjanlunal.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvbWJrZnlleW1xcWphbmx1bmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5ODE5MzAsImV4cCI6MjA5MjU1NzkzMH0.wtZkf1Un3vXRRTkPLULYY0Uew-K_Q9Nc5bS3euOjT8A
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
