"""Exercise the migration's pattern conversion on synthetic PostgreSQL fixtures.

Only a loopback database named lighthouse_runtime_contract_test is accepted.
Every fixture rolls back. No production rows or credentials are required.
"""

from pathlib import Path
import os
import subprocess
from urllib.parse import urlsplit


database_url = os.environ["PATTERN_TEST_DATABASE_URL"]
target = urlsplit(database_url)
if target.hostname not in {"localhost", "127.0.0.1", "::1"} or target.path != "/lighthouse_runtime_contract_test":
    raise SystemExit("Pattern regression requires the dedicated loopback test database")

migration = Path("supabase/migrations/20260909143000_lighthouse_runtime_postgres_contract_v1.sql").read_text()
helpers = migration.split("-- Ingestion and canonical registry contracts", 1)[0]
pattern_section = migration.split("-- Canonical pattern backbone", 1)[1].split(
    "-- Governed pattern/trend/strategy read projections", 1
)[0]

source_fixture = """
create table public.pattern_source_fixture as
select n::integer as id, null::integer as case_id,
       case when n <= 55 then 'weak_joint' else 'fixture_' || n::text end as pattern_type,
       'Synthetic preservation fixture ' || n::text as description,
       1770000000000::bigint + n * 60000::bigint as created_at,
       1770000000000::bigint + n * 60000::bigint + 10000 as updated_at
from generate_series(1,173) n;
"""

view_fixture = """
create view public.patterns as
select id, case_id, pattern_type, description,
       to_timestamp(created_at::double precision / 1000)::text as created_at,
       null::integer as pattern_type_id, pattern_type as signature,
       created_at as first_seen_at, updated_at as last_seen_at,
       1::integer as occurrence_count
from pattern_source_fixture;
"""

table_fixture = """
create table public.patterns (
  id bigint generated by default as identity primary key,
  pattern_type text, description text, signature text,
  created_at bigint, first_seen_at bigint, last_seen_at bigint,
  occurrence_count integer
);
insert into public.patterns
  (id,pattern_type,description,signature,created_at,first_seen_at,last_seen_at,occurrence_count)
select id,pattern_type,description,pattern_type,created_at,created_at,updated_at,1
from pattern_source_fixture;
"""

assert_preservation = """
do $$
begin
  if (select count(*) from public.patterns) <> 173
     or (select count(distinct signature) from public.patterns) <> 173
     or (select count(distinct pattern_key) from public.patterns) <> 173 then
    raise exception 'Pattern rows or unique runtime identities were not preserved';
  end if;
  if exists (
    select 1 from pattern_source_fixture s
    left join public.patterns p on p.id = s.id
    where p.id is null
       or p.pattern_type is distinct from s.pattern_type
       or p.description is distinct from s.description
       or p.created_at is distinct from s.created_at
       or p.first_seen_at is distinct from s.created_at
       or p.last_seen_at is distinct from s.updated_at
       or p.occurrence_count <> 1
  ) then
    raise exception 'Original pattern content, identity, or timestamps changed';
  end if;
  if (select count(*) from public.patterns where source_signature = 'weak_joint') <> 55 then
    raise exception 'Duplicate signature provenance was not preserved';
  end if;
end;
$$;
"""

assert_view_dates = """
do $$
begin
  if exists (
    select 1 from public.patterns p join pattern_source_fixture s on s.id=p.id
    where p.source_created_at is distinct from to_timestamp(s.created_at::double precision / 1000)::text
       or p.updated_at is distinct from s.updated_at
  ) then
    raise exception 'Original view creation or update date was not preserved';
  end if;
end;
$$;
"""

for fixture_name, fixture_sql in [("production_view", view_fixture), ("legacy_table", table_fixture)]:
    query = "\n".join([
        "begin; set local timezone = 'UTC';",
        "do $$ begin if to_regclass('public.patterns') is not null then raise exception 'Test database is not empty'; end if; end $$;",
        source_fixture, fixture_sql, helpers, pattern_section,
        assert_preservation,
        assert_view_dates if fixture_name == "production_view" else "",
        "create temporary table first_pass as select * from public.patterns;",
        pattern_section,
        assert_preservation,
        """do $$ begin
          if exists ((select * from public.patterns except select * from first_pass)
                     union all
                     (select * from first_pass except select * from public.patterns)) then
            raise exception 'Second migration run changed preserved pattern rows';
          end if;
        end $$;""",
        "rollback;",
    ])
    result = subprocess.run(
        ["psql", "--no-psqlrc", "--set=ON_ERROR_STOP=1", "--quiet", "--dbname", database_url],
        input=query, text=True, capture_output=True, timeout=60,
    )
    if result.returncode:
        raise SystemExit(f"{fixture_name}: FAIL\n{result.stderr}")
    print(f"{fixture_name}: PASS — 173 rows, 55 duplicate source signatures, original dates, idempotent replay")
