-- Restore the two World Index tables that predate their checked-in metadata
-- repair. The following production migration owns the metadata columns.

create table if not exists public.agencies_registry (
  id text primary key,
  agency_name text,
  jurisdiction text,
  domain text,
  agency_type text,
  website text,
  contact_methods text,
  official_status text,
  notes timestamptz,
  created_at bigint,
  updated_at bigint
);

create table if not exists public.workflow_steps (
  id integer generated by default as identity primary key,
  workflow_id integer,
  step_number integer,
  action_type text,
  action_description text,
  deadline_days integer,
  created_at bigint,
  updated_at bigint,
  step_order integer,
  title text,
  description text,
  required_inputs text,
  decision_logic text,
  next_step_on_success text,
  next_step_on_failure text,
  estimated_days integer,
  deadline_rule text,
  warnings text,
  step_type text
);

alter table public.agencies_registry enable row level security;
alter table public.workflow_steps enable row level security;

drop policy if exists public_read_agencies_registry on public.agencies_registry;
drop policy if exists authenticated_all_access_workflow_steps on public.workflow_steps;
drop policy if exists service_role_all_workflow_steps_46e1ab5b on public.workflow_steps;

create policy public_read_agencies_registry
  on public.agencies_registry for select to anon, authenticated using (true);
create policy authenticated_all_access_workflow_steps
  on public.workflow_steps for select to authenticated using (true);
create policy service_role_all_workflow_steps_46e1ab5b
  on public.workflow_steps for all to service_role using (true) with check (true);

revoke all on table public.agencies_registry, public.workflow_steps
  from public, anon, authenticated;
grant select on table public.agencies_registry to anon, authenticated;
grant select on table public.workflow_steps to authenticated;
grant all on table public.agencies_registry, public.workflow_steps to service_role;

revoke all on sequence public.workflow_steps_id_seq
  from public, anon, authenticated;
grant usage, select on sequence public.workflow_steps_id_seq to service_role;
