
-- ============================================================
-- MIGRATION 015: Seed Engine Registry
-- All 50 engines from exhaustive extraction
-- ============================================================

INSERT INTO engine_registry_v2 (
  engine_name, file_path, router_export, approuter_key,
  layer, family, status,
  tables_used, llm_calls, notes,
  has_warning, warning_codes, confirmed_live, source_files,
  created_at, updated_at
) VALUES

-- ─── FULLY IMPLEMENTED — CONFIRMED ─────────────────────────

('Intake Router',
  'server/routers.ts (intakeRouter)',
  'export const intakeRouter = router({...})',
  'intake: intakeRouter',
  'L0', 'Intake', 'fully_implemented',
  ARRAY['cases','pipeline_events'],
  '1 LLM per message',
  'Guided intake and direct case creation. 51 pipeline types. Conversational chat entrypoint. Confirmed active V3.0 Session 7.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Analysis Pipeline (Document Worker)',
  'server/analysis-pipeline.ts',
  NULL, NULL,
  'L1-L5', 'Ingestion / Extraction / Evidence', 'fully_implemented',
  ARRAY['documents','corpus_snapshots','extracted_entities','extracted_events','document_quotes','claims','findings','document_correlations','signal_flags','extraction_runs'],
  '1 LLM/doc (Pass1) + 1 LLM/doc (Pass2) + 1 LLM/case (Pass3)',
  'Three-pass LLM pipeline. In-memory queue loses state on container restart. Three enqueueDocument() calls missing snapshotId (Gate 1.5 fix pending — 3-line change). Dequeue-time fallback masks gap but breaks audit trail.',
  TRUE, ARRAY['WARNING-02'],
  TRUE, ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md','Luminari_Spine___Final_Cohesion_Lockdown_Analysis_.pdf'],
  0, 0),

('Upload Route',
  'server/upload-route.ts',
  NULL, NULL,
  'L1', 'Ingestion', 'fully_implemented',
  ARRAY['documents','corpus_snapshots'],
  'none (deterministic)',
  'Creates document record with snapshotId and SHA-256 hash. Normal path does NOT call enqueueDocument(). Override path (duplicate replacement) correctly calls with snapshotId. Asymmetry documented in Spine Lockdown — not a bug.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari_Spine___Final_Cohesion_Lockdown_Analysis_.pdf'],
  0, 0),

('Gap Detection Engine',
  'server/gap-detection.ts + server/domain-rules.ts',
  NULL, NULL,
  'L5', 'Evidence', 'fully_implemented',
  ARRAY['missing_records','documents','claims','domain_registry'],
  'none (deterministic)',
  'Zero LLM. Active domain rule sets: policemisconduct, icwa, insurance, elderabuse (+ nursing and guardianship as aliases). All other 45 pipeline types skip gap detection. Output feeds AKB lookup and FOIA generation.',
  TRUE, ARRAY['WARNING-08'],
  TRUE, ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('FOIA Generator',
  'server/foia-generator.ts + server/akb-lookup.ts',
  NULL, NULL,
  'L8', 'Procedural / Action', 'fully_implemented',
  ARRAY['foia_requests','missing_records','agency_directory','foia_registry'],
  '1 LLM per request letter',
  'AKB coverage Washington State only. 11-status lifecycle: draft → ready → sent → acknowledged → processing → partial_response → completed | denied → appeal_filed → appeal_completed | expired.',
  TRUE, ARRAY['WARNING-08'],
  TRUE, ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Pattern Detection Engine',
  'server/pattern-detection.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'fully_implemented',
  ARRAY['patterns','pattern_occurrences','signal_flags','extracted_entities','findings','missing_records','claims'],
  'none (deterministic)',
  'Zero LLM. 6 pattern types: entity_recurrence, agency_behavior, denial_language_pattern, foia_denial_pattern, record_gap_pattern, temporal_anomaly. Cross-case. SHA-256 signature per pattern. Session 7 addition.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Narrative Generator',
  'server/narrative-generator.ts',
  NULL, NULL,
  'L9', 'Export / Assembly', 'fully_implemented',
  ARRAY['cases','documents','claims','findings','extracted_events','document_quotes','foia_requests'],
  '1 LLM per generation',
  'Chronological Statement of Facts with source references. Session 6 addition. Visible at /narrative.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('CDA Pipeline (Claim Denial Analysis)',
  'server/cda-pipeline.ts + server/cda-bundle.ts + server/cda-bundle-zip.ts',
  'export const cdaRouter = router({...}) (implied)',
  'cda: cdaRouter',
  'L2-L5', 'Parsing / Evidence / Intelligence', 'fully_implemented',
  ARRAY['cda_runs','cda_documents','cda_quotes','cda_denial_reasons','cda_policy_clauses','cda_claim_ledger','cda_comparison_matrix','cda_contradictions','cda_evidence_gaps','patterns'],
  'up to 9 LLM calls per run',
  'Independent 9-stage sub-pipeline T1-T9. PATCH3: T6 heading-overlap mapping table (deterministic). T7: controlled judgment layer. Output: comparison matrix, claim ledger, contradiction report, evidence gap analysis, ZIP. Spec v1.0-PATCH3 validated against TV3. Visible at /cda and /cda/:id.',
  FALSE, NULL, TRUE,
  ARRAY['CDA_v1_0_Model_Layer_Spec_6.pdf','CDA_v1_0-PATCH3___Targeted_T6_T7_Re-run_Against_TV.pdf'],
  0, 0),

('Phase 2 Analysis Engine',
  'server/phase2-analysis.ts',
  NULL, NULL,
  'L5-L6', 'Evidence / Intelligence', 'partial',
  ARRAY['corpus_snapshots','findings','claims','extracted_entities','extracted_events'],
  '1 LLM per run (orchestration)',
  'Triggered from sealed snapshot. Results in Spine Viewer. Requires SEALED gate. Deterministic detection — zero LLM for individual passes. Details not fully documented.',
  FALSE, NULL, FALSE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Snapshot Management (Gate System)',
  'server/gate-schema.ts + server/gate-helpers.ts',
  NULL, NULL,
  'L1', 'Control', 'fully_implemented',
  ARRAY['corpus_snapshots'],
  'none (deterministic)',
  '6 gate stages: EXTRACTION, CLAIM_BUILD, CORRELATION, FINDINGS, READY_TO_SEAL, SEALED. 10 gated actions. assertActionAllowed() called inside every gated router procedure. Risk Zone C and B documented.',
  TRUE, ARRAY['WARNING-04','WARNING-05'],
  TRUE, ARRAY['Luminari_Spine___Final_Cohesion_Lockdown_Analysis_.pdf'],
  0, 0),

('Cryptographic Signing',
  'server/crypto-signing.ts + server/export-manifest.ts',
  NULL, NULL,
  'L10', 'Oversight / Control', 'fully_implemented',
  ARRAY['corpus_snapshots'],
  'none (deterministic)',
  'Ed25519 signing of sealed snapshots. Tamper detection confirmed live — corruption detected at exact break point. All 12 governance log fields verified.',
  FALSE, NULL, TRUE,
  ARRAY['Governance_Validation_Report___Luminari_Forensic_E__1_.md'],
  0, 0),

('Export System',
  'server/export-streaming.ts + server/cda-bundle.ts + server/cda-bundle-zip.ts',
  NULL, NULL,
  'L9', 'Export / Assembly', 'fully_implemented',
  ARRAY['corpus_snapshots','cases','documents','claims','findings','extracted_entities','document_quotes','cda_runs'],
  'none (deterministic)',
  'Outputs: JSON export, HTML bundle, CDA ZIP. Risk Zone A: export-streaming.ts uses getLatestSnapshot() fallback — could export wrong snapshot. SpineViewer uses explicit snapshotId correctly.',
  TRUE, ARRAY['WARNING-03'],
  TRUE, ARRAY['Luminari_Spine___Final_Cohesion_Lockdown_Analysis_.pdf'],
  0, 0),

('Collaboration Router',
  'server/routers.ts (collaborationRouter)',
  'export const collaborationRouter = router({...})',
  'collaboration: collaborationRouter',
  'L11', 'Admin / Oversight', 'fully_implemented',
  ARRAY['case_collaborators','cases','users'],
  'none (deterministic)',
  'READ_ONLY / WRITE access levels. Case sharing between users.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Share Router',
  'server/routers.ts (shareRouter)',
  'export const shareRouter = router({...})',
  'share: shareRouter',
  'L11', 'Admin / Oversight', 'fully_implemented',
  ARRAY['share_links','cases'],
  'none (deterministic)',
  'Public read-only case sharing via token links.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Action Path Generator',
  'server/routers.ts (generateActionPath procedure)',
  'procedure within existing router',
  'generateActionPath',
  'L8', 'Procedural / Action', 'fully_implemented',
  ARRAY['cases','findings','claims','missing_records'],
  '1 LLM per case',
  'Produces recommended next steps based on findings. Embedded procedure, not standalone router export.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Tone Validator',
  'server/tone-validator.ts',
  NULL, NULL,
  'L2-L7', 'Control / Validation', 'fully_implemented',
  NULL,
  'none (deterministic)',
  'Ensures AI outputs maintain neutral forensic language. Confirmed: rationale validation caught word "test" and rejected with clear error.',
  FALSE, NULL, TRUE,
  ARRAY['Governance_Validation_Report___Luminari_Forensic_E__1_.md'],
  0, 0),

('Entity Dedup',
  'server/entity-dedup.ts',
  NULL, NULL,
  'L4', 'Validation / Normalization', 'fully_implemented',
  ARRAY['extracted_entities','case_entities'],
  'none (deterministic)',
  'Fuzzy matching to merge duplicate entities across documents.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Entity Filter',
  'server/entity-filter.ts',
  NULL, NULL,
  'L4', 'Validation / Normalization', 'fully_implemented',
  ARRAY['extracted_entities'],
  'none (deterministic)',
  'Filters noise entities (dates, numbers, generic terms).',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Quote Filter',
  'server/quote-filter.ts',
  NULL, NULL,
  'L4', 'Validation / Normalization', 'fully_implemented',
  ARRAY['document_quotes'],
  'none (deterministic)',
  'Filters low-value quotes (headers, footers, boilerplate).',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Date Normalizer',
  'server/date-normalizer.ts',
  NULL, NULL,
  'L4', 'Validation / Normalization', 'fully_implemented',
  ARRAY['extracted_dates','extracted_events'],
  'none (deterministic)',
  'Normalizes date formats for consistent sorting.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Relationship Type Validator',
  'server/relationship-type-validator.ts',
  NULL, NULL,
  'L4', 'Validation / Normalization', 'fully_implemented',
  ARRAY['extracted_entities'],
  'none (deterministic)',
  'Validates and reclassifies relationship types. Prevents invalid relationship_type enum values.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Document Checklists',
  'server/document-checklists.ts',
  NULL, NULL,
  'L0', 'Intake', 'fully_implemented',
  NULL,
  'none (deterministic)',
  'Domain-specific document requirement checklists. Static domain-keyed output. Consumed by DocumentChecklist UI component.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Remediation Classification',
  'server/remediation-classification.ts',
  NULL, NULL,
  'L1', 'Ingestion', 'fully_implemented',
  ARRAY['documents'],
  'none (deterministic)',
  'Classifies failed documents for recovery path. Feeds extraction recovery logic.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Extraction Recovery',
  'server/extraction-recovery.ts',
  NULL, NULL,
  'L1', 'Ingestion', 'fully_implemented',
  ARRAY['documents'],
  'none (deterministic)',
  'Auto-retry with exponential backoff for failed extractions.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Batch Rerun',
  'server/batch-rerun.ts',
  NULL, NULL,
  'L5', 'Evidence', 'fully_implemented',
  ARRAY['findings','documents'],
  '1 LLM per finding',
  'Bulk re-analysis of all findings with updated prompts. Manual trigger only.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Claim Backfill',
  'server/claim-backfill.ts',
  NULL, NULL,
  'L5', 'Evidence', 'fully_implemented',
  ARRAY['claims','documents'],
  'none (deterministic)',
  'Backfills missing document references in claims. Corrective maintenance utility.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Hard Delete',
  'server/hard-delete-canonical.ts',
  NULL, NULL,
  'L10', 'Oversight / Control', 'fully_implemented',
  ARRAY['cases','documents','extracted_entities','claims','findings'],
  'none (deterministic)',
  'Cascade deletion with S3 cleanup and reference counting. Canonical implementation — no other delete paths should exist.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Storage Spine',
  'server/storage-spine.ts',
  NULL, NULL,
  'L1', 'Ingestion', 'fully_implemented',
  ARRAY['documents'],
  'none (deterministic)',
  'S3 storage abstraction layer. All file storage ops must go through this.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Notification System',
  'server/db.ts (createNotification)',
  NULL, NULL,
  'L10', 'Oversight / Control', 'fully_implemented',
  ARRAY['notifications'],
  'none (deterministic)',
  '9 notification types: share_accessed, extraction_complete, new_findings, case_status, feedback_response, share_expiring, foia_deadline_approaching, foia_overdue, foia_status_update.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Audit Trail',
  'server/db.ts (logAudit)',
  NULL, NULL,
  'L10', 'Oversight / Control', 'fully_implemented',
  ARRAY['audit_trail','admin_change_log'],
  'none (deterministic)',
  'Complete action logging for every mutation. Append-only per Founding Law 10. No-op writes are logged without rejection — design decision confirmed in Governance Validation Report.',
  FALSE, NULL, TRUE,
  ARRAY['Governance_Validation_Report___Luminari_Forensic_E__1_.md'],
  0, 0),

('Pipeline Events',
  'drizzle/schema.ts (pipeline_events table)',
  NULL, NULL,
  'L0-L9', 'Control', 'fully_implemented',
  ARRAY['pipeline_events'],
  'none (deterministic)',
  'Lifecycle event tracking: intake_start → case_completed. Persistent event log table — not a router or engine.',
  FALSE, NULL, TRUE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0),

('Governance Log (Sovereign Oversight)',
  'server/admin-sovereign-control.ts + server/governance-router.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'fully_implemented',
  ARRAY['governance_log'],
  'none (deterministic)',
  'Confirmed live. Hash chain cryptographically linked (SHA-256). All 12 fields present. Operations confirmed: governedDataStreamToggle, governedThresholdUpdate, governedSignalSuppression. Rationale validation enforced.',
  FALSE, NULL, TRUE,
  ARRAY['Governance_Validation_Report___Luminari_Forensic_E__1_.md'],
  0, 0),

-- ─── SCAFFOLDED ─────────────────────────────────────────────

('Interpretation Service',
  'server/services/interpretation-service.ts',
  NULL,
  'interpretation: interpretationRouter',
  'L7', 'Interpretation', 'scaffolded',
  ARRAY['claims','findings','missing_records','patterns','signal_flags','doctrine_registry','legal_statutes','remedy_templates','corpus_snapshots'],
  'none — READ ONLY, no LLM calls, no writes',
  'THE TRUST CORE. ONE AND ONLY ONE INSTANCE. Does not write. Does not call LLMs. Does not infer new truth. Read-only projection only. Same snapshot MUST produce same interpretation. Output: CaseInterpretation { snapshotHash, claimLedger, comparisonMatrix, evidenceGaps, contradictions, patterns, availableActions }.',
  TRUE, ARRAY['WARNING-07'],
  FALSE,
  ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md','Luminari___Neutral_Forensic_Engine_3.0___Complete_.md'],
  0, 0),

-- ─── BROKEN ─────────────────────────────────────────────────

('Session / V3-V4 Routers',
  'server/session-router.ts + server/session76-router.ts + server/engines-v3-router.ts + server/engines-v4-router.ts',
  'unknown — exports exist but names not confirmed',
  NULL,
  'unknown', 'unknown', 'broken',
  NULL,
  'unknown',
  'KNOWN BROKEN: 96 TypeScript compile errors from Zod v4 breaking change. Every z.record(z.unknown()) must be changed to z.record(z.string(), z.unknown()). Non-compiling. Must be fixed before any build that includes them.',
  TRUE, ARRAY['WARNING-01'],
  FALSE,
  ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

-- ─── UNKNOWN — FROM DIAGNOSTIC-ENGINES.MD ───────────────────

('Sunam Executor',
  'server/sunam-executor.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'unknown',
  NULL, NULL,
  'Main decision engine — interprets natural language commands and routes to tools. No router export, table usage, or appRouter key confirmed. engineRegistry registration not confirmed.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('System Copilot (Sunam)',
  'server/system-copilot-sunam.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'unknown',
  NULL, NULL,
  'Conversational AI interface for Sunam. No confirmed wiring.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Data Stream Manager',
  'server/data-stream-manager.ts',
  NULL, NULL,
  'L1', 'Ingestion', 'unknown',
  ARRAY['stream_status','ingestion_health_metrics'],
  NULL,
  'Manages data ingestion schedules. governedDataStreamToggle confirmed live in Governance Validation Report (CFPB stream toggled, seqNo=1 produced). Live connection confirmed.',
  TRUE, ARRAY['WARNING-06'],
  TRUE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md','Governance_Validation_Report___Luminari_Forensic_E__1_.md'],
  0, 0),

('Admin Sovereign Control',
  'server/admin-sovereign-control.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'unknown',
  ARRAY['governance_log','sunam_thresholds'],
  NULL,
  'governedThresholdUpdate and governedSignalSuppression confirmed live. Hash chain fully validated (4 entries, VALID after corruption/restoration test).',
  TRUE, ARRAY['WARNING-06'],
  TRUE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md','Governance_Validation_Report___Luminari_Forensic_E__1_.md'],
  0, 0),

('Export Spine Engine',
  'server/export-spine-engine.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'unknown',
  NULL, NULL,
  'Exports entire system state for portability. No confirmed router wiring.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Restore Spine Engine',
  'server/restore-spine-engine.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'unknown',
  NULL, NULL,
  'Restores system from exported state. No confirmed router wiring.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Entity Intelligence',
  'server/entity-intelligence.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['extracted_entities','actor_fingerprints','patterns'],
  NULL,
  'Analyzes entity behavior patterns and anomalies. withEngineTracking() wrapping not confirmed. engineRegistry registration not confirmed.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Entity Evidence Threshold',
  'server/entity-evidence-threshold.ts',
  NULL, NULL,
  'L5', 'Evidence', 'unknown',
  ARRAY['extracted_entities','claims','evidence_requirements'],
  NULL,
  'Determines evidence sufficiency for entity claims.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Entity Transparency',
  'server/entity-transparency.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['extracted_entities','actor_fingerprints'],
  NULL,
  'Exposes entity relationships and connections.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Litigation Correlation Service',
  'server/litigation-correlation-service.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['extracted_entities','patterns'],
  NULL,
  'Correlates entities with litigation history.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Problem Interpreter Service',
  'server/problem-interpreter-service.ts',
  NULL, NULL,
  'L0', 'Intake', 'unknown',
  ARRAY['cases','domain_registry'],
  NULL,
  'Interprets user problems into system categories. MUST NOT be confused with interpretation-service.ts (L7). Different layer, different function.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Evidence Dossier',
  'server/evidence-dossier.ts',
  NULL, NULL,
  'L5', 'Evidence', 'unknown',
  ARRAY['claims','findings','patterns','extracted_entities','document_quotes'],
  NULL,
  'Compiles evidence for each detected pattern.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Investigative Query Engine',
  'server/investigative-query-engine.ts',
  NULL, NULL,
  'L10', 'Oversight / Intelligence', 'unknown',
  NULL,
  NULL,
  'Allows complex queries across all data. Cross-system.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Systemic Intelligence Map',
  'server/systemic-intelligence-map.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['patterns','signal_registry','civic_map_signals','actor_fingerprints'],
  NULL,
  'Maps systemic patterns and structural issues.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Institutional Accountability',
  'server/institutional-accountability.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['patterns','actor_fingerprints','agency_directory'],
  NULL,
  'Tracks institutional responsibility for patterns.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Regulatory Capture',
  'server/regulatory-capture.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['patterns','actor_fingerprints'],
  NULL,
  'Detects regulatory capture and conflicts of interest.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Crisis Prediction',
  'server/crisis-prediction.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['signal_registry','patterns','signal_occurrences'],
  NULL,
  'Predicts imminent crises based on patterns.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Harm Index Service',
  'server/harm-index-service.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['patterns','financial_impact_records'],
  NULL,
  'Quantifies harm to individuals and communities.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Harm Map Service',
  'server/harm-map-service.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['civic_map_signals','patterns'],
  NULL,
  'Geographic and demographic mapping of harm.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Risk Forecast Service',
  'server/risk-forecast-service.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['signal_registry','patterns'],
  NULL,
  'Forecasts future risk based on current patterns.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Systemic Risk Forecast',
  'server/systemic-risk-forecast.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  ARRAY['signal_registry','patterns','civic_map_signals'],
  NULL,
  'Forecasts systemic-level risks.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Systemic Simulation',
  'server/systemic-simulation.ts',
  NULL, NULL,
  'L6', 'Pattern / Signal', 'unknown',
  NULL,
  NULL,
  'Simulates outcomes of policy and intervention changes. No table writes confirmed — simulation output likely ephemeral.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Attorney Match Service',
  'server/attorney-match-service.ts',
  NULL, NULL,
  'L8', 'Procedural / Action', 'unknown',
  ARRAY['resource_registry','agency_directory'],
  NULL,
  'Matches users with appropriate legal representation.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Case Link Service',
  'server/case-link-service.ts',
  NULL, NULL,
  'L8', 'Procedural / Action', 'unknown',
  ARRAY['cases','patterns'],
  NULL,
  'Links user situations to relevant cases.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Intervention Timeline Engine',
  'server/intervention-timeline-engine.ts',
  NULL, NULL,
  'L8', 'Procedural / Action', 'unknown',
  ARRAY['deadline_instances','case_actions'],
  NULL,
  'Plans intervention timelines and deadlines.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Time Travel Engine',
  'server/time-travel-engine.ts',
  NULL, NULL,
  'L5', 'Evidence / Intelligence', 'unknown',
  ARRAY['corpus_snapshots','timeline_events'],
  NULL,
  'Analyzes historical precedent and counterfactuals.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Public Alerting',
  'server/public-alerting.ts',
  NULL, NULL,
  'L10', 'Oversight / Public', 'unknown',
  ARRAY['response_visibility_events','civic_map_signals'],
  NULL,
  'Alerts public about systemic issues.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Public Transparency',
  'server/public-transparency.ts',
  NULL, NULL,
  'L10', 'Oversight / Public', 'unknown',
  ARRAY['patterns','signal_registry'],
  NULL,
  'Exposes findings to public.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('External Collaboration',
  'server/external-collaboration.ts',
  NULL, NULL,
  'L10', 'Oversight / Public', 'unknown',
  NULL, NULL,
  'Coordinates with external organizations.',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Executor Service',
  'server/executor-service.ts',
  NULL, NULL,
  'L10', 'Control / Oversight', 'unknown',
  ARRAY['engine_runs','worker_runs'],
  NULL,
  'Generic execution framework. engine_runs table confirmed in SKILL.md enum (engineRunStatus: pending, running, success, failed, unknown, superseded).',
  TRUE, ARRAY['WARNING-06'],
  FALSE, ARRAY['LUMINARI-DIAGNOSTIC-ENGINES.md'],
  0, 0),

('Presentations Router',
  'server/routers.ts (presentationsRouter)',
  'export const presentationsRouter = router({...})',
  'presentations: presentationsRouter',
  'L9', 'Export / Assembly', 'unknown',
  ARRAY['cases','findings','claims','extracted_entities'],
  NULL,
  'Slide deck generation from case data. No further detail in available docs.',
  FALSE, NULL, FALSE,
  ARRAY['Luminari___Neutral_Forensic_Engine_3.0.md'],
  0, 0);

