
-- Drop old constraint, add richer columns, reload all 330 tables
ALTER TABLE schema_table_registry
  DROP CONSTRAINT IF EXISTS schema_table_registry_table_group_check,
  ADD COLUMN IF NOT EXISTS purpose TEXT,
  ADD COLUMN IF NOT EXISTS layer VARCHAR(16),
  ADD COLUMN IF NOT EXISTS engine_family VARCHAR(64),
  ADD COLUMN IF NOT EXISTS source VARCHAR(64) DEFAULT 'manus_schema_ts',
  ADD COLUMN IF NOT EXISTS created_at BIGINT DEFAULT 0;

ALTER TABLE schema_table_registry
  ALTER COLUMN table_group TYPE TEXT;

TRUNCATE schema_table_registry;

INSERT INTO schema_table_registry (table_name, table_group, confirmed, purpose, layer, engine_family, notes) VALUES
('users','core',TRUE,'User auth + role management','L0','Infrastructure','camelCase: users'),
('cases','core',TRUE,'Investigation workspaces','L0','Intake','camelCase: cases; pipelineType field = 51 types'),
('corpus_snapshots','core',TRUE,'Versioned case snapshots, Ed25519 signed','L0','Control','camelCase: corpusSnapshots'),
('documents','core',TRUE,'Uploaded docs + extracted text + S3','L1','Intake','camelCase: documents'),
('upload_sessions','core',TRUE,'Document upload session tracking','L1','Intake','camelCase: uploadSessions'),
('entities','core',TRUE,'Extracted named entities','L2','Extraction','camelCase: entities'),
('entity_relationships','core',TRUE,'Entity relationship graph','L2','Extraction','camelCase: entityRelationships'),
('entity_roles','core',TRUE,'Entity role classification','L2','Extraction','camelCase: entityRoles'),
('entity_aliases','core',TRUE,'Entity alias merge tracking','L2','Extraction','camelCase: entityAliases'),
('quotes','core',TRUE,'Extracted quotes with statement origin','L2','Extraction','camelCase: quotes'),
('events','core',TRUE,'Extracted timeline events','L2','Extraction','camelCase: events'),
('claims','core',TRUE,'Legal claims per document','L2','Extraction','camelCase: claims'),
('relationships','core',TRUE,'Cross-entity relationships','L2','Extraction','camelCase: relationships'),
('findings','core',TRUE,'Analytical findings per case','L5','Evidence','camelCase: findings'),
('document_correlations','core',TRUE,'Cross-document correlation results','L5','Evidence','camelCase: documentCorrelations'),
('signal_flags','signals',TRUE,'Signal flags per claim (pre-gate)','L6','Signal','camelCase: signalFlags'),
('signal_registry','signals',TRUE,'Canonical signal registry','L6','Signal','camelCase: signalRegistry'),
('detected_signals','signals',TRUE,'Gate-governed detected signals','L6','Signal','gate_decision_id FK to sunam_gate_log'),
('live_signals','signals',TRUE,'Pre-gate live signals','L6','Signal','camelCase: liveSignals'),
('signal_extractions','signals',TRUE,'Signal extraction run records','L6','Signal','camelCase: signalExtractions'),
('signal_explanations_extended','signals',TRUE,'Extended signal explanations','L6','Signal','template-based explanations'),
('signal_generation_log','signals',TRUE,'Signal generation audit log','L6','Signal','camelCase: signalGenerationLog'),
('historical_signals','signals',TRUE,'Historical signal archive','L6','Signal','camelCase: historicalSignals'),
('confidence_factors','signals',TRUE,'Confidence factor weights','L6','Signal','camelCase: confidenceFactors'),
('sunam_gate_log','governance',TRUE,'Sunam gate decisions, hash-chained','L11','Sovereign','camelCase: sunamGateLog'),
('sunam_thresholds','governance',TRUE,'Sunam threshold configuration','L11','Sovereign','camelCase: sunamThresholds'),
('governance_log','governance',TRUE,'Full audit trail, SHA-256 hash chain','L11','Governance','4 live entries confirmed VALID'),
('governance_snapshots','governance',TRUE,'Governance state snapshots','L11','Governance','camelCase: governanceSnapshots'),
('audit_trail','governance',TRUE,'System-wide mutation audit','L10','Oversight','camelCase: auditTrail'),
('admin_change_log','governance',TRUE,'Admin operation log','L10','Oversight','camelCase: adminChangeLog'),
('chain_verification_log','governance',TRUE,'Hash chain verification history','L10','Oversight','camelCase: chainVerificationLog'),
('pattern_registry','patterns',TRUE,'Extended pattern registry','L6','Pattern','NOT pattern_signatures — V3 name deprecated'),
('pattern_metadata','patterns',TRUE,'Pattern confidence + metadata','L6','Pattern','camelCase: patternMetadata'),
('pattern_occurrences','patterns',TRUE,'Pattern occurrence tracking','L6','Pattern','camelCase: patternOccurrences'),
('pattern_feedback_loop','patterns',TRUE,'CORE LOOP — never been written to','L6','Pattern','PAT-557 WA wage_theft test case'),
('pattern_systemic_inferences','patterns',TRUE,'Systemic inference records','L6','Pattern','feeds feedback loop step 1'),
('pattern_candidates','patterns',TRUE,'Pattern candidates pending confirm','L6','Pattern','camelCase: patternCandidates'),
('pattern_case_links','patterns',TRUE,'Case-to-pattern bridge','L6','Pattern','camelCase: patternCaseLinks'),
('pattern_signal_links','patterns',TRUE,'Signal-to-pattern links','L6','Pattern','camelCase: patternSignalLinks'),
('pattern_entity_clusters','patterns',TRUE,'Entity clustering per pattern','L6','Pattern','camelCase: patternEntityClusters'),
('pattern_institution_links','patterns',TRUE,'Institution-to-pattern linkage','L6','Pattern','camelCase: patternInstitutionLinks'),
('pattern_conduct_clusters','patterns',TRUE,'Conduct cluster groupings','L6','Pattern','camelCase: patternConductClusters'),
('pattern_geographic_hotspots','patterns',TRUE,'Geographic hotspot mapping','L6','Pattern','feeds civic map'),
('pattern_evidence_correlations','patterns',TRUE,'Pattern evidence correlations','L6','Pattern','camelCase: patternEvidenceCorrelations'),
('pattern_intervention_routes','patterns',TRUE,'Intervention routes per pattern','L6','Pattern','camelCase: patternInterventionRoutes'),
('pattern_defense_strategies','patterns',TRUE,'Defense strategies per pattern','L6','Pattern','camelCase: patternDefenseStrategies'),
('pattern_outcome_analytics','patterns',TRUE,'Outcome analytics per pattern','L6','Pattern','camelCase: patternOutcomeAnalytics'),
('pattern_outcome_divergence','patterns',TRUE,'Outcome divergence tracking','L6','Pattern','camelCase: patternOutcomeDivergence'),
('pattern_evolution','patterns',TRUE,'Pattern evolution over time','L6','Pattern','camelCase: patternEvolution'),
('pattern_temporal_trends','patterns',TRUE,'Temporal trend analysis','L6','Pattern','camelCase: patternTemporalTrends'),
('pattern_timeline_events','patterns',TRUE,'Timeline events linked to patterns','L6','Pattern','camelCase: patternTimelineEvents'),
('pattern_entity_summary','patterns',TRUE,'Entity summary per pattern','L6','Pattern','camelCase: patternEntitySummary'),
('pattern_responsible_agencies','patterns',TRUE,'Agencies responsible per pattern','L6','Pattern','camelCase: patternResponsibleAgencies'),
('pattern_confidence_factors','patterns',TRUE,'Confidence factor weights','L6','Pattern','camelCase: patternConfidenceFactors'),
('pattern_creation_thresholds','patterns',TRUE,'Pattern creation thresholds','L6','Pattern','camelCase: patternCreationThresholds'),
('pattern_decay_rules','patterns',TRUE,'Pattern decay/expiration rules','L6','Pattern','camelCase: patternDecayRules'),
('pattern_types','patterns',TRUE,'Canonical pattern type registry','L6','Pattern','camelCase: patternTypes'),
('pattern_relationships','patterns',TRUE,'Inter-pattern relationship graph','L6','Pattern','camelCase: patternRelationships'),
('pattern_aggregation_runs','patterns',TRUE,'Aggregation run history','L6','Pattern','camelCase: patternAggregationRuns'),
('pattern_industry_profiles','patterns',TRUE,'Industry-level pattern profiles','L6','Pattern','camelCase: patternIndustryProfiles'),
('dossier_packages','cda',TRUE,'CDA run metadata — was cda_runs in V3','L5','CDA','CRITICAL: do not use cda_runs'),
('dossier_sections','cda',TRUE,'Document sections per dossier','L5','CDA','camelCase: dossierSections'),
('dossier_shares','cda',TRUE,'Dossier sharing records','L5','CDA','camelCase: dossierShares'),
('dossier_redactions','cda',TRUE,'Dossier redaction tracking','L5','CDA','camelCase: dossierRedactions'),
('dossier_exports','cda',TRUE,'Dossier export records','L5','CDA','camelCase: dossierExports'),
('strategy_matter_profile','strategy',TRUE,'Matter profile per case','L8','Strategy','camelCase: strategyMatterProfile'),
('strategy_fact_matrix','strategy',TRUE,'Fact matrix per case','L8','Strategy','camelCase: strategyFactMatrix'),
('strategy_claim_catalog','strategy',TRUE,'Canonical claim catalog — 97 types','L8','Strategy','camelCase: strategyClaimCatalog'),
('strategy_claim_candidates','strategy',TRUE,'Claim candidates per case — 0 rows','L8','Strategy','strategy engine never run'),
('strategy_viability_assessment','strategy',TRUE,'Viability assessments — 0 rows','L8','Strategy','strategy engine never run'),
('strategy_deadline_engine','strategy',TRUE,'Computed deadlines per case','L8','Strategy','camelCase: strategyDeadlineEngine'),
('strategy_element_fact_links','strategy',TRUE,'Element-to-fact links','L8','Strategy','camelCase: strategyElementFactLinks'),
('strategy_missing_evidence_tasks','strategy',TRUE,'Missing evidence task queue','L8','Strategy','camelCase: strategyMissingEvidenceTasks'),
('strategy_forum_rules','strategy',TRUE,'Forum selection rules','L8','Strategy','camelCase: strategyForumRules'),
('strategy_paths','strategy',TRUE,'Strategy paths per case','L8','Strategy','camelCase: strategyPaths'),
('strategy_registry','strategy',TRUE,'Strategy registry','L8','Strategy','camelCase: strategyRegistry'),
('strategy_selection_rules','strategy',TRUE,'Strategy selection rules','L8','Strategy','camelCase: strategySelectionRules'),
('strategy_steps','strategy',TRUE,'Strategy execution steps','L8','Strategy','camelCase: strategySteps'),
('strategy_success_rates','strategy',TRUE,'Strategy success rates','L8','Strategy','camelCase: strategySuccessRates'),
('strategy_effectiveness','strategy',TRUE,'Strategy effectiveness metrics','L8','Strategy','camelCase: strategyEffectiveness'),
('sys_strategy_paths','strategy',TRUE,'System-level strategy paths','L8','Strategy','camelCase: sysStrategyPaths'),
('data_stream_registry','streams',TRUE,'Stream registry — was data_streams in V3','L1','Stream','CRITICAL: do not use data_streams'),
('dataset_registry','streams',TRUE,'Dataset registry','L1','Stream','camelCase: datasetRegistry'),
('dataset_provenance','streams',TRUE,'Dataset provenance tracking','L1','Stream','camelCase: datasetProvenance'),
('ingest_runs','streams',TRUE,'Ingestion run tracking','L1','Stream','camelCase: ingestRuns'),
('ingested_records','streams',TRUE,'Ingested records staging','L1','Stream','camelCase: ingestedRecords'),
('extraction_staging','streams',TRUE,'Extraction staging table','L1','Stream','camelCase: extractionStaging'),
('cross_stream_correlations','streams',TRUE,'Cross-stream correlations','L1','Stream','camelCase: crossStreamCorrelations'),
('lobbying_activity','streams',TRUE,'Lobbying activity stream','L1','Stream','camelCase: lobbyingActivity'),
('administrative_decisions','streams',TRUE,'Administrative decisions stream','L1','Stream','camelCase: administrativeDecisions'),
('litigation_registry','streams',TRUE,'Litigation case registry','L1','Stream','camelCase: litigationRegistry'),
('litigation_cases','streams',TRUE,'Litigation case records','L1','Stream','camelCase: litigationCases'),
('federal_litigation_cases','streams',TRUE,'Federal court cases','L1','Stream','camelCase: federalLitigationCases'),
('investigative_reports','streams',TRUE,'Investigative report stream','L1','Stream','camelCase: investigativeReports'),
('investigative_queries','streams',TRUE,'Investigative query records','L1','Stream','camelCase: investigativeQueries'),
('investigative_results','streams',TRUE,'Investigative query results','L1','Stream','camelCase: investigativeResults'),
('verified_reports','streams',TRUE,'Verified report stream','L1','Stream','camelCase: verifiedReports'),
('oversight_reports','streams',TRUE,'Oversight report stream','L1','Stream','camelCase: oversightReports'),
('foia_requests','foia',TRUE,'FOIA tracking, 11-status lifecycle','L8','FOIA','camelCase: foiaRequests; WA AKB only'),
('foia_agencies','foia',TRUE,'FOIA agency directory','L3','FOIA','camelCase: foiaAgencies'),
('foia_agency_records','foia',TRUE,'FOIA agency record types','L3','FOIA','camelCase: foiaAgencyRecords'),
('foia_record_types','foia',TRUE,'FOIA record type registry','L3','FOIA','camelCase: foiaRecordTypes'),
('foia_statutes','foia',TRUE,'FOIA statute reference','L3','FOIA','camelCase: foiaStatutes'),
('knowledge_entries','knowledge',TRUE,'Knowledge backbone entries — 4008 records','L3','Knowledge','camelCase: knowledgeEntries'),
('knowledge_modules','knowledge',TRUE,'Knowledge module registry','L3','Knowledge','camelCase: knowledgeModules'),
('knowledge_cross_refs','knowledge',TRUE,'Cross-reference links','L3','Knowledge','camelCase: knowledgeCrossRefs'),
('knowledge_freshness','knowledge',TRUE,'Freshness tracking per module','L3','Knowledge','camelCase: knowledgeFreshness'),
('knowledge_coverage_metrics','knowledge',TRUE,'Coverage metrics per jurisdiction','L3','Knowledge','camelCase: knowledgeCoverageMetrics'),
('enforcement_penalties','enforcement',TRUE,'Enforcement penalty registry','L3','Enforcement','camelCase: enforcementPenalties'),
('enforcement_priority_index','enforcement',TRUE,'Agency priority index','L3','Enforcement','camelCase: enforcementPriorityIndex'),
('enforcement_trends','enforcement',TRUE,'Enforcement trend tracking','L3','Enforcement','camelCase: enforcementTrends'),
('enforcement_viability_rules','enforcement',TRUE,'Enforcement viability rules','L3','Enforcement','camelCase: enforcementViabilityRules'),
('legal_statutes','legal',TRUE,'Legal statute registry','L3','Legal','camelCase: legalStatutes'),
('legal_case_law','legal',TRUE,'Case law registry — 357 planned','L3','Legal','camelCase: legalCaseLaw'),
('legal_contradictions','legal',TRUE,'Legal contradiction tracking','L3','Legal','camelCase: legalContradictions'),
('legal_enforcement_records','legal',TRUE,'Legal enforcement record archive','L3','Legal','camelCase: legalEnforcementRecords'),
('legal_statute_clauses','legal',TRUE,'Statute clause breakdown','L3','Legal','camelCase: legalStatuteClauses'),
('legal_weak_joints','legal',TRUE,'Legal weak joint analysis','L3','Legal','camelCase: legalWeakJoints'),
('doctrine_registry','legal',TRUE,'Legal doctrine registry','L3','Legal','camelCase: doctrineRegistry'),
('doctrine_graph_edges','legal',TRUE,'Doctrine graph edges','L3','Legal','camelCase: doctrineGraphEdges'),
('litigation_barriers','legal',TRUE,'Litigation barrier analysis','L3','Legal','camelCase: litigationBarriers'),
('proof_frameworks','legal',TRUE,'Proof framework templates','L3','Legal','camelCase: proofFrameworks'),
('claim_element_matrix','legal',TRUE,'Claim element matrix','L3','Legal','camelCase: claimElementMatrix'),
('claim_detection_results','legal',TRUE,'Claim detection results — 0 rows','L3','Legal','viability engine never run'),
('claim_detection_rules','legal',TRUE,'Claim detection rule engine','L3','Legal','camelCase: claimDetectionRules'),
('claim_viability','legal',TRUE,'Claim viability assessments — 0 rows','L3','Legal','viability engine never run'),
('investigation_guidance','legal',TRUE,'Investigation guidance templates','L3','Legal','camelCase: investigationGuidance'),
('filing_generator','legal',TRUE,'Filing generator templates','L3','Legal','camelCase: filingGenerator'),
('checklist_items','legal',TRUE,'Checklist item library','L3','Legal','camelCase: checklistItems'),
('narrative_templates','legal',TRUE,'Narrative template library','L9','Assembly','camelCase: narrativeTemplates'),
('contradiction_templates','legal',TRUE,'Contradiction template library','L3','Legal','camelCase: contradictionTemplates'),
('interp_category_interpretations','interpretation',TRUE,'Category interpretation rules','L7','Interpretation','camelCase: interpCategoryInterpretations'),
('interp_entity_signal_rules','interpretation',TRUE,'Entity signal interpretation rules','L7','Interpretation','camelCase: interpEntitySignalRules'),
('interp_geographic_signal_rules','interpretation',TRUE,'Geographic signal rules','L7','Interpretation','camelCase: interpGeographicSignalRules'),
('interp_harm_mappings','interpretation',TRUE,'Harm domain mapping rules','L7','Interpretation','camelCase: interpHarmMappings'),
('interp_jurisdiction_guidance','interpretation',TRUE,'Jurisdiction guidance rules','L7','Interpretation','camelCase: interpJurisdictionGuidance'),
('interp_signal_templates','interpretation',TRUE,'Signal interpretation templates','L7','Interpretation','camelCase: interpSignalTemplates'),
('interp_status_interpretations','interpretation',TRUE,'Status interpretation rules','L7','Interpretation','camelCase: interpStatusInterpretations'),
('interp_timeline_expectations','interpretation',TRUE,'Timeline expectation rules','L7','Interpretation','camelCase: interpTimelineExpectations'),
('interpreter_claim_matches','interpretation',TRUE,'Interpreter claim match records','L7','Interpretation','camelCase: interpreterClaimMatches'),
('interpreter_evidence_guidance','interpretation',TRUE,'Evidence guidance from interpreter','L7','Interpretation','camelCase: interpreterEvidenceGuidance'),
('interpreter_question_flow','interpretation',TRUE,'Interpreter question flow','L7','Interpretation','camelCase: interpreterQuestionFlow'),
('policy_events','interpretation',TRUE,'Policy event registry — 24 PE events','L7','Interpretation','camelCase: policyEvents'),
('policy_pattern_impacts','interpretation',TRUE,'Policy impact on patterns','L7','Interpretation','camelCase: policyPatternImpacts'),
('remedy_templates','remedy',TRUE,'Remedy template library — 95+ planned','L8','Remedy','1 seeded: LS_WAGE_001_FED'),
('remedy_paths','remedy',TRUE,'Remedy paths per case','L8','Remedy','camelCase: remedyPaths'),
('remedy_steps','remedy',TRUE,'Remedy step tracking','L8','Remedy','camelCase: remedySteps'),
('remedy_doc_requirements','remedy',TRUE,'Document requirements per remedy','L8','Remedy','camelCase: remedyDocRequirements'),
('remedy_outcome_tracking','remedy',TRUE,'Outcome tracking per remedy','L8','Remedy','camelCase: remedyOutcomeTracking'),
('generated_remedy_docs','remedy',TRUE,'Generated remedy documents','L8','Remedy','camelCase: generatedRemedyDocs'),
('settlement_calculations','remedy',TRUE,'Settlement calculation records','L8','Remedy','8 formulas seeded'),
('settlement_formulas','remedy',TRUE,'Settlement formula registry','L8','Remedy','camelCase: settlementFormulas'),
('formula_version_history','remedy',TRUE,'Formula version history','L8','Remedy','camelCase: formulaVersionHistory'),
('damages_matrix','remedy',TRUE,'Damages matrix — 24 entries seeded','L8','Remedy','camelCase: damagesMatrix'),
('calculation_audit_log','remedy',TRUE,'Calculation audit trail','L8','Remedy','camelCase: calculationAuditLog'),
('assembly_document_templates','assembly',TRUE,'Document templates for packets','L9','Assembly','camelCase: assemblyDocumentTemplates'),
('assembly_section_library','assembly',TRUE,'Reusable section library','L9','Assembly','camelCase: assemblySectionLibrary'),
('assembly_exhibit_index','assembly',TRUE,'Exhibit index per packet','L9','Assembly','camelCase: assemblyExhibitIndex'),
('assembly_filing_packets','assembly',TRUE,'Generated filing packets','L9','Assembly','camelCase: assemblyFilingPackets'),
('assembly_generated_sections','assembly',TRUE,'Generated sections per packet','L9','Assembly','camelCase: assemblyGeneratedSections'),
('assembly_citation_index','assembly',TRUE,'Citation index per packet','L9','Assembly','camelCase: assemblyCitationIndex'),
('assembly_fact_narrative_blocks','assembly',TRUE,'Fact narrative blocks','L9','Assembly','camelCase: assemblyFactNarrativeBlocks'),
('assembly_legal_argument_blocks','assembly',TRUE,'Legal argument blocks','L9','Assembly','camelCase: assemblyLegalArgumentBlocks'),
('assembly_relief_requests','assembly',TRUE,'Relief request blocks','L9','Assembly','camelCase: assemblyReliefRequests'),
('assembly_party_designations','assembly',TRUE,'Party designations','L9','Assembly','camelCase: assemblyPartyDesignations'),
('assembly_compliance_checklist','assembly',TRUE,'Compliance checklist per packet','L9','Assembly','camelCase: assemblyComplianceChecklist'),
('assembly_version_history','assembly',TRUE,'Version history per packet','L9','Assembly','camelCase: assemblyVersionHistory'),
('assembly_output_registry','assembly',TRUE,'Output registry for all packets','L9','Assembly','camelCase: assemblyOutputRegistry'),
('lumensend_drafts','lumensend',TRUE,'LumenSend outbound drafts','L9','LumenSend','camelCase: lumensendDrafts'),
('lumensend_templates','lumensend',TRUE,'LumenSend template library','L9','LumenSend','camelCase: lumensendTemplates'),
('paperwork_templates','lumensend',TRUE,'Paperwork template registry','L9','LumenSend','camelCase: paperworkTemplates'),
('generated_documents','lumensend',TRUE,'Generated document archive','L9','LumenSend','camelCase: generatedDocuments'),
('doc_generation_queue','lumensend',TRUE,'Document generation queue','L9','LumenSend','camelCase: docGenerationQueue'),
('lighthouse_events','lighthouse',TRUE,'Civic transparency events','L10','Lighthouse','camelCase: lighthouseEvents'),
('lighthouse_jobs','lighthouse',TRUE,'Lighthouse background jobs','L10','Lighthouse','camelCase: lighthouseJobs'),
('lighthouse_posts','lighthouse',TRUE,'Lighthouse public posts','L10','Lighthouse','camelCase: lighthousePosts'),
('lighthouse_spotlight','lighthouse',TRUE,'Lighthouse spotlight features','L10','Lighthouse','camelCase: lighthouseSpotlight'),
('lighthouse_suggestions','lighthouse',TRUE,'Community suggestions','L10','Lighthouse','camelCase: lighthouseSuggestions'),
('lighthouse_suggestion_votes','lighthouse',TRUE,'Suggestion voting records','L10','Lighthouse','camelCase: lighthouseSuggestionVotes'),
('public_reports','lighthouse',TRUE,'Public report records','L10','Lighthouse','camelCase: publicReports'),
('public_report_sections','lighthouse',TRUE,'Public report sections','L10','Lighthouse','camelCase: publicReportSections'),
('public_report_exports','lighthouse',TRUE,'Public report exports','L10','Lighthouse','camelCase: publicReportExports'),
('alert_events','lighthouse',TRUE,'Alert event records','L10','Lighthouse','camelCase: alertEvents'),
('alert_subscriptions','lighthouse',TRUE,'Alert subscriptions','L10','Lighthouse','camelCase: alertSubscriptions'),
('alert_delivery_log','lighthouse',TRUE,'Alert delivery log','L10','Lighthouse','camelCase: alertDeliveryLog'),
('attorney_registry','attorneys',TRUE,'Attorney and legal aid registry','L5','Attorney','camelCase: attorneyRegistry'),
('attorney_case_match','attorneys',TRUE,'Attorney-to-case match records','L5','Attorney','camelCase: attorneyCaseMatch'),
('attorney_outcomes','attorneys',TRUE,'Attorney outcome tracking','L5','Attorney','camelCase: attorneyOutcomes'),
('harm_index_scores','risk',TRUE,'Harm index per case','L7','Risk','camelCase: harmIndexScores'),
('harm_index_entities','risk',TRUE,'Entities linked to harm index','L7','Risk','camelCase: harmIndexEntities'),
('harm_index_history','risk',TRUE,'Harm index history','L7','Risk','camelCase: harmIndexHistory'),
('harm_map_nodes','risk',TRUE,'Harm map geographic nodes','L7','Risk','camelCase: harmMapNodes'),
('harm_map_edges','risk',TRUE,'Harm map edges','L7','Risk','camelCase: harmMapEdges'),
('harm_map_snapshots','risk',TRUE,'Harm map state snapshots','L7','Risk','camelCase: harmMapSnapshots'),
('risk_forecasts','risk',TRUE,'Risk forecast records','L7','Risk','camelCase: riskForecasts'),
('risk_forecast_history','risk',TRUE,'Risk forecast history','L7','Risk','camelCase: riskForecastHistory'),
('systemic_risk_forecasts','risk',TRUE,'Systemic risk forecasts','L7','Risk','camelCase: systemicRiskForecasts'),
('crisis_predictions','risk',TRUE,'Crisis prediction records','L7','Risk','camelCase: crisisPredictions'),
('element_strength','risk',TRUE,'Element strength scoring','L5','Risk','camelCase: elementStrength'),
('forecast_inputs','risk',TRUE,'Forecast input records','L7','Risk','camelCase: forecastInputs'),
('institution_registry','accountability',TRUE,'Institution registry','L6','Accountability','camelCase: institutionRegistry'),
('institution_risk_profiles','accountability',TRUE,'Institution risk profiles','L6','Accountability','camelCase: institutionRiskProfiles'),
('institution_timeline','accountability',TRUE,'Institution activity timeline','L6','Accountability','camelCase: institutionTimeline'),
('institution_activity','accountability',TRUE,'Institution activity records','L6','Accountability','camelCase: institutionActivity'),
('institution_annotations','accountability',TRUE,'Institution annotations','L6','Accountability','camelCase: institutionAnnotations'),
('institution_pattern_links','accountability',TRUE,'Institution-to-pattern links','L6','Accountability','camelCase: institutionPatternLinks'),
('regulatory_capture_patterns','accountability',TRUE,'Regulatory capture patterns','L6','Accountability','camelCase: regulatoryCapturePatterns'),
('regulatory_capture_signals','accountability',TRUE,'Regulatory capture signals','L6','Accountability','camelCase: regulatoryCaptureSignals'),
('regulatory_capture_metrics','accountability',TRUE,'Regulatory capture metrics','L6','Accountability','camelCase: regulatoryCaptureMetrics'),
('simulation_runs','simulation',TRUE,'Simulation run records','L7','Simulation','camelCase: simulationRuns'),
('simulation_results','simulation',TRUE,'Simulation results','L7','Simulation','camelCase: simulationResults'),
('simulation_assumptions','simulation',TRUE,'Simulation assumptions','L7','Simulation','camelCase: simulationAssumptions'),
('counterfactual_parameters','simulation',TRUE,'Counterfactual parameter sets','L7','Simulation','camelCase: counterfactualParameters'),
('time_travel_runs','timeline',TRUE,'Time travel run records','L7','TimeTravl','camelCase: timeTravelRuns'),
('timeline_events','timeline',TRUE,'Timeline events — 26 confirmed','L7','Timeline','camelCase: timelineEvents'),
('timeline_edges','timeline',TRUE,'Timeline edge graph','L7','Timeline','camelCase: timelineEdges'),
('timeline_rules','timeline',TRUE,'Timeline rule engine','L7','Timeline','camelCase: timelineRules'),
('timeline_signals','timeline',TRUE,'Timeline signal links','L7','Timeline','camelCase: timelineSignals'),
('node_timeline','timeline',TRUE,'Node-level timeline records','L7','Timeline','camelCase: nodeTimeline'),
('pipeline_events','pipeline',TRUE,'Pipeline lifecycle event tracking','L0','Pipeline','camelCase: pipelineEvents'),
('pipeline_intake_enrichments','pipeline',TRUE,'Pipeline intake enrichment records','L0','Pipeline','camelCase: pipelineIntakeEnrichments'),
('pipeline_intelligence_map','pipeline',TRUE,'Pipeline intelligence map','L0','Pipeline','camelCase: pipelineIntelligenceMap'),
('evidence_items','evidence',TRUE,'Evidence item records','L5','Evidence','camelCase: evidenceItems'),
('evidence_proof_links','evidence',TRUE,'Evidence-to-proof links','L5','Evidence','camelCase: evidenceProofLinks'),
('evidence_event_links','evidence',TRUE,'Evidence-to-event links','L5','Evidence','camelCase: evidenceEventLinks'),
('evidence_graph_edges','evidence',TRUE,'Evidence graph edges','L5','Evidence','camelCase: evidenceGraphEdges'),
('evidence_records','evidence',TRUE,'Evidence record archive','L5','Evidence','camelCase: evidenceRecords'),
('evidence_sources','evidence',TRUE,'Evidence source registry','L5','Evidence','camelCase: evidenceSources'),
('evidence_profiles','evidence',TRUE,'Evidence profile records','L5','Evidence','camelCase: evidenceProfiles'),
('batch_rerun_runs','evidence',TRUE,'Batch rerun tracking','L2','Evidence','camelCase: batchRerunRuns'),
('entity_evidence_scores','evidence',TRUE,'Entity evidence scores','L5','Evidence','camelCase: entityEvidenceScores'),
('missing_records','gaps',TRUE,'Missing record tracking (gap detection)','L4','Gap','camelCase: missingRecords'),
('deadline_rules','gaps',TRUE,'Deadline rule engine','L4','Gap','camelCase: deadlineRules'),
('weak_joint_hits','gaps',TRUE,'Legal weak joint hits','L4','Gap','camelCase: weakJointHits'),
('weak_joint_triggers','gaps',TRUE,'Weak joint triggers','L4','Gap','camelCase: weakJointTriggers'),
('copilot_conversations','sunam',TRUE,'Sunam copilot conversations','L11','Sunam','camelCase: copilotConversations'),
('copilot_messages','sunam',TRUE,'Copilot message records','L11','Sunam','camelCase: copilotMessages'),
('copilot_artifacts','sunam',TRUE,'Copilot artifact records','L11','Sunam','camelCase: copilotArtifacts'),
('copilot_executions','sunam',TRUE,'Copilot execution records','L11','Sunam','camelCase: copilotExecutions'),
('copilot_impact_analyses','sunam',TRUE,'Copilot impact analyses','L11','Sunam','camelCase: copilotImpactAnalyses'),
('copilot_system_context','sunam',TRUE,'Copilot system context','L11','Sunam','camelCase: copilotSystemContext'),
('session_log','sunam',TRUE,'Session execution log','L11','Sunam','camelCase: sessionLog'),
('export_spine_runs','spine',TRUE,'Export spine run records','L11','Spine','camelCase: exportSpineRuns'),
('restore_spine_runs','spine',TRUE,'Restore spine run records','L11','Spine','camelCase: restoreSpineRuns'),
('advocacy_organizations','advocacy',TRUE,'Advocacy org registry (Luminari)','L10','Advocacy','seeded — 46 orgs'),
('advocacy_reports','advocacy',TRUE,'Advocacy report records','L10','Advocacy','camelCase: advocacyReports'),
('legislator_contacts','advocacy',TRUE,'Legislator contacts (Luminari)','L10','Advocacy','seeded — 28 legislators'),
('external_partners','collaboration',TRUE,'External partner registry','L10','Collaboration','camelCase: externalPartners'),
('external_comments','collaboration',TRUE,'External comments on dossiers','L10','Collaboration','camelCase: externalComments'),
('case_collaborators','sharing',TRUE,'Case collaborator records','L11','Sharing','camelCase: caseCollaborators'),
('case_share_permissions','sharing',TRUE,'Case share permissions','L11','Sharing','camelCase: caseSharePermissions'),
('share_links','sharing',TRUE,'Share link records','L11','Sharing','camelCase: shareLinks'),
('case_signals','sharing',TRUE,'Case signal mappings','L6','Sharing','camelCase: caseSignals'),
('case_narratives','assembly',TRUE,'Case narrative records','L9','Assembly','camelCase: caseNarratives'),
('case_pattern_links','patterns',TRUE,'Case-to-pattern link records','L6','Patterns','camelCase: casePatternLinks'),
('case_fact_patterns','evidence',TRUE,'Case fact pattern records','L5','Evidence','camelCase: caseFactPatterns'),
('engine_registry','infrastructure',TRUE,'Engine registry','L0','Infrastructure','camelCase: engineRegistry'),
('engine_runs','infrastructure',TRUE,'Engine execution run tracking','L0','Infrastructure','camelCase: engineRuns'),
('system_map_nodes','infrastructure',TRUE,'System map nodes','L0','Infrastructure','camelCase: systemMapNodes'),
('system_map_edges','infrastructure',TRUE,'System map edges','L0','Infrastructure','camelCase: systemMapEdges'),
('system_references','infrastructure',TRUE,'System reference registry','L0','Infrastructure','camelCase: systemReferences'),
('map_annotations','infrastructure',TRUE,'Map annotation records','L0','Infrastructure','camelCase: mapAnnotations'),
('geocode_cache','infrastructure',TRUE,'Geocoding cache','L0','Infrastructure','camelCase: geocodeCache'),
('notifications','ui',TRUE,'User notification records','L10','UI','camelCase: notifications'),
('presentations','ui',TRUE,'Presentation slide records','L9','UI','camelCase: presentations'),
('user_feedback','ui',TRUE,'User feedback records','L0','UI','camelCase: userFeedback'),
('benefit_applications','benefits',TRUE,'Benefit application records','L8','Benefits','camelCase: benefitApplications'),
('court_directory','legal',TRUE,'Court directory','L3','Legal','camelCase: courtDirectory'),
('jurisdiction_hierarchy','legal',TRUE,'Jurisdiction hierarchy','L3','Legal','camelCase: jurisdictionHierarchy'),
('jurisdiction_rules','legal',TRUE,'Jurisdiction-specific rules','L3','Legal','camelCase: jurisdictionRules'),
('escalation_routes','escalation',TRUE,'Escalation route registry','L8','Escalation','camelCase: escalationRoutes'),
('escalation_thresholds','escalation',TRUE,'Escalation threshold config','L8','Escalation','camelCase: escalationThresholds'),
('intervention_endpoints','intervention',TRUE,'Intervention endpoint registry','L8','Intervention','camelCase: interventionEndpoints'),
('intervention_escalation_rules','intervention',TRUE,'Intervention escalation rules','L8','Intervention','camelCase: interventionEscalationRules'),
('intervention_submissions','intervention',TRUE,'Intervention submission records','L8','Intervention','camelCase: interventionSubmissions'),
('provenance_audit_logs','governance',TRUE,'Provenance audit logs','L10','Oversight','camelCase: provenanceAuditLogs'),
('provenance_alert_events','governance',TRUE,'Provenance alert events','L10','Oversight','camelCase: provenanceAlertEvents'),
('trend_registry','trends',TRUE,'Trend registry','L6','Trend','camelCase: trendRegistry'),
('trend_forecasts','trends',TRUE,'Trend forecast records','L6','Trend','camelCase: trendForecasts'),
('trend_snapshots','trends',TRUE,'Trend state snapshots','L6','Trend','camelCase: trendSnapshots'),
('trend_pressure_metrics','trends',TRUE,'Pressure metric tracking','L6','Trend','camelCase: trendPressureMetrics'),
('historical_patterns','trends',TRUE,'Historical pattern archive','L6','Trend','camelCase: historicalPatterns'),
('historical_trends','trends',TRUE,'Historical trend archive','L6','Trend','camelCase: historicalTrends'),
('agency_forms','registry',TRUE,'Agency form registry','L3','Registry','camelCase: agencyForms'),
('agency_authority_map','registry',TRUE,'Agency authority mapping','L3','Registry','camelCase: agencyAuthorityMap'),
('agency_coordination_matrix','registry',TRUE,'Inter-agency coordination matrix','L3','Registry','camelCase: agencyCoordinationMatrix'),
('agency_intake_rules','registry',TRUE,'Agency intake rules','L3','Registry','camelCase: agencyIntakeRules'),
('agency_performance_metrics','registry',TRUE,'Agency performance metrics','L3','Registry','camelCase: agencyPerformanceMetrics'),
('interagency_referrals','registry',TRUE,'Interagency referral tracking','L3','Registry','camelCase: interagencyReferrals'),
('phase2_runs','phase2',TRUE,'Phase 2 analysis run records','L5','Phase2','camelCase: phase2Runs'),
('phase2_evidence_requirements','phase2',TRUE,'Phase 2 evidence requirements','L5','Phase2','camelCase: phase2EvidenceRequirements'),
('phase2_structured_notes','phase2',TRUE,'Phase 2 structured notes','L5','Phase2','camelCase: phase2StructuredNotes');

