
-- ============================================================
-- MIGRATION 011: North Carolina, Maryland, Arkansas programs
-- ============================================================

INSERT INTO programs (
  program_key, name, resource_type, provider_type,
  state_code, is_national, situation_tags, population_tags,
  income_threshold, turnaround, is_emergency,
  phone, application_url, website,
  eligibility, cost, languages,
  source_url, last_verified, created_at, updated_at
) VALUES

-- ─── NORTH CAROLINA ────────────────────────────────────────

('nc-snap', 'North Carolina SNAP / Food and Nutrition Services (DHHS)',
  'food', 'state', 'NC', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '919-527-6800', 'https://epass.nc.gov', 'https://epass.nc.gov',
  'Income < 130% FPL — 100 county DSS offices. ABAWD work requirements active.',
  'Free', ARRAY['English','Spanish'],
  'https://epass.nc.gov', '2026-04', 0, 0),

('nc-wic', 'WIC North Carolina',
  'food', 'state', 'NC', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  '919-707-5900', 'https://nutritionnc.com', 'https://nutritionnc.com',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL. Spanish services available.',
  'Free', ARRAY['English','Spanish'],
  'https://nutritionnc.com', '2026-04', 0, 0),

('nc-food-bank-central', 'Food Bank of Central and Eastern NC (Raleigh)',
  'food', 'nonprofit', 'NC', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '919-875-0707', 'https://foodbankcenc.org', 'https://foodbankcenc.org',
  '34-county central and eastern NC service area.',
  'Free', ARRAY['English','Spanish'],
  'https://foodbankcenc.org', '2026-04', 0, 0),

('nc-medicaid', 'NC Medicaid (Expanded December 2023)',
  'healthcare', 'state', 'NC', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '888-245-0179', 'https://epass.nc.gov', 'https://medicaid.ncdhhs.gov',
  'Adults 19–64 to 138% FPL — expanded Dec 2023. Enrollment still maturing. Verify managed care plan.',
  'Free', ARRAY['English','Spanish'],
  'https://medicaid.ncdhhs.gov', '2026-04', 0, 0),

('nc-fqhc-ncchca', 'NC Community Health Center Association (FQHCs)',
  'healthcare', 'fqhc', 'NC', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','farmworkers','all'],
  TRUE, '1_week', FALSE,
  '919-469-5701', 'https://ncchca.org', 'https://ncchca.org',
  'Anyone regardless of insurance — 40+ FQHCs statewide; sliding scale. Includes NC Farmworker Health Program.',
  'Sliding scale', ARRAY['English','Spanish'],
  'https://ncchca.org', '2026-04', 0, 0),

('nc-legal-aid', 'Legal Aid of North Carolina (Statewide)',
  'legal_aid', 'legal_aid_org', 'NC', FALSE,
  ARRAY['any','eviction','housing','benefits','dv','employment'], ARRAY['low_income','farmworkers','all'],
  TRUE, '1_week', FALSE,
  '919-856-2564', 'https://legalaidnc.org', 'https://legalaidnc.org',
  'All NC counties — housing, family, benefits, DV, consumer, immigration. Farmworker Unit (919-856-2180) is specialized.',
  'Free', ARRAY['English','Spanish'],
  'https://legalaidnc.org', '2026-04', 0, 0),

('nc-legal-aid-farmworker', 'Legal Aid of NC — Farmworker Unit',
  'legal_aid', 'legal_aid_org', 'NC', FALSE,
  ARRAY['employment','housing','benefits','immigration','any'], ARRAY['farmworkers','immigrants'],
  TRUE, '1_week', FALSE,
  '919-856-2180', 'https://legalaidnc.org/get-help/farmworker-unit', 'https://legalaidnc.org',
  'NC farmworkers — wage theft, housing conditions, workers comp, OSHA, immigration. Specialized capacity.',
  'Free', ARRAY['English','Spanish'],
  'https://legalaidnc.org', '2026-04', 0, 0),

('nc-housing-nchfa', 'NC Housing Finance Agency (NCHFA)',
  'rental_assistance', 'state', 'NC', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '919-877-5700', 'https://nchfa.com', 'https://nchfa.com',
  'Low-income NC renters — Section 8/HCV, HOME, rental assistance, homelessness prevention.',
  'Free', ARRAY['English','Spanish'],
  'https://nchfa.com', '2026-04', 0, 0),

-- ─── MARYLAND ──────────────────────────────────────────────

('md-snap', 'Maryland SNAP / Food Supplement Program (DHR)',
  'food', 'state', 'MD', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '800-332-6347', 'https://mydhhr.org', 'https://mydhhr.org',
  'Income < 130% FPL — 24 county DSS offices + Baltimore City DSS.',
  'Free', ARRAY['English','Spanish','Amharic','French'],
  'https://mydhhr.org', '2026-04', 0, 0),

('md-wic', 'Maryland WIC',
  'food', 'state', 'MD', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  '410-767-6980', 'https://phpa.health.maryland.gov/wic', 'https://phpa.health.maryland.gov/wic',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL.',
  'Free', ARRAY['English','Spanish','Amharic'],
  'https://phpa.health.maryland.gov/wic', '2026-04', 0, 0),

('md-food-bank', 'Maryland Food Bank (Baltimore / Central MD)',
  'food', 'nonprofit', 'MD', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '410-737-8282', 'https://mdfoodbank.org', 'https://mdfoodbank.org',
  'Central Maryland and statewide — 21-county service area.',
  'Free', ARRAY['English','Spanish'],
  'https://mdfoodbank.org', '2026-04', 0, 0),

('md-medicaid', 'Maryland Medicaid / HealthChoice (Expanded 2014)',
  'healthcare', 'state', 'MD', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '800-492-5231', 'https://mydhhr.org', 'https://mmcp.health.maryland.gov',
  'Adults 19–64 to 138% FPL (expanded 2014). HealthChoice managed care — verify MCO assignment.',
  'Free', ARRAY['English','Spanish','Amharic'],
  'https://mmcp.health.maryland.gov', '2026-04', 0, 0),

('md-fqhc', 'Maryland Community Health Centers (FQHCs)',
  'healthcare', 'fqhc', 'MD', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '410-383-8300', 'https://mchcmd.org', 'https://mchcmd.org',
  'Anyone regardless of insurance — 30+ FQHCs statewide; sliding scale.',
  'Sliding scale', ARRAY['English','Spanish','Amharic','French'],
  'https://mchcmd.org', '2026-04', 0, 0),

('md-legal-aid', 'Maryland Legal Aid (Statewide)',
  'legal_aid', 'legal_aid_org', 'MD', FALSE,
  ARRAY['any','eviction','housing','benefits','dv','employment'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '800-999-8904', 'https://mdlab.org', 'https://mdlab.org',
  'Statewide — housing (eviction triage), family, benefits, DV, consumer, immigration. Eastern Shore, Western MD offices.',
  'Free', ARRAY['English','Spanish'],
  'https://mdlab.org', '2026-04', 0, 0),

('md-casa', 'CASA (Immigrant Services — MD/DC/VA)',
  'immigration', 'nonprofit', 'MD', FALSE,
  ARRAY['immigration','benefits','housing','employment','any'], ARRAY['immigrants','latinos'],
  FALSE, '1_week', FALSE,
  '301-431-4185', 'https://wearecasa.org', 'https://wearecasa.org',
  'Immigrants and Latinos in MD — legal, social, employment services. PG County and statewide.',
  'Free to sliding scale', ARRAY['English','Spanish'],
  'https://wearecasa.org', '2026-04', 0, 0),

('md-housing-dhcd', 'Maryland DHCD (Housing and Community Development)',
  'rental_assistance', 'state', 'MD', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '301-429-7400', 'https://dhcd.maryland.gov', 'https://dhcd.maryland.gov',
  'Low-income MD renters — Section 8/HCV, HOME, emergency rental assistance, homelessness prevention.',
  'Free', ARRAY['English','Spanish'],
  'https://dhcd.maryland.gov', '2026-04', 0, 0),

('md-tanf', 'Maryland TCA (Temporary Cash Assistance / TANF)',
  'emergency_cash', 'state', 'MD', FALSE,
  ARRAY['benefits','any'], ARRAY['low_income','families','children'],
  TRUE, '1_week', FALSE,
  '800-332-6347', 'https://mydhhr.org', 'https://mydhhr.org',
  'Families with children — up to $714/month for family of 3. 60-month federal limit.',
  'Free', ARRAY['English','Spanish'],
  'https://mydhhr.org', '2026-04', 0, 0),

-- ─── ARKANSAS ──────────────────────────────────────────────

('ar-snap', 'Arkansas SNAP / Food Assistance (DHS)',
  'food', 'state', 'AR', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '501-682-8375', 'https://access.arkansas.gov', 'https://access.arkansas.gov',
  'Income < 130% FPL — county DHS offices. ABAWD active.',
  'Free', ARRAY['English','Spanish'],
  'https://access.arkansas.gov', '2026-04', 0, 0),

('ar-wic', 'WIC Arkansas',
  'food', 'state', 'AR', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  '501-661-2169', 'https://healthy.arkansas.gov', 'https://healthy.arkansas.gov',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL.',
  'Free', ARRAY['English','Spanish'],
  'https://healthy.arkansas.gov', '2026-04', 0, 0),

('ar-food-bank', 'Arkansas Food Bank (Little Rock / Central AR)',
  'food', 'nonprofit', 'AR', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '501-565-8121', 'https://arkansasfoodbank.org', 'https://arkansasfoodbank.org',
  'Central and east Arkansas — 33-county service area.',
  'Free', ARRAY['English','Spanish'],
  'https://arkansasfoodbank.org', '2026-04', 0, 0),

('ar-medicaid-arhome', 'ARHOME / Arkansas Medicaid (Private Option — Expanded)',
  'healthcare', 'state', 'AR', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '888-987-1200', 'https://access.arkansas.gov', 'https://medicaid.mmis.state.ar.us',
  'Adults 19–64 to 138% FPL (expanded via ARHOME Private Option). Enrolls in private plans. Marshallese COFA residents: verify eligibility.',
  'Free', ARRAY['English','Spanish'],
  'https://medicaid.mmis.state.ar.us', '2026-04', 0, 0),

('ar-fqhc-arpca', 'Arkansas Primary Care Association (FQHCs)',
  'healthcare', 'fqhc', 'AR', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '501-664-0836', 'https://arpca.com', 'https://arpca.com',
  'Anyone regardless of insurance — 12+ FQHCs statewide; sliding scale.',
  'Sliding scale', ARRAY['English','Spanish','Marshallese'],
  'https://arpca.com', '2026-04', 0, 0),

('ar-legal-services-cals', 'Center for Arkansas Legal Services (CALS)',
  'legal_aid', 'legal_aid_org', 'AR', FALSE,
  ARRAY['any','eviction','housing','benefits','dv','immigration'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '501-376-3423', 'https://arlegalservices.org', 'https://arlegalservices.org',
  'Central and west Arkansas — housing, family, benefits, DV, consumer, immigration. Fayetteville office for NW AR.',
  'Free', ARRAY['English','Spanish'],
  'https://arlegalservices.org', '2026-04', 0, 0),

('ar-legal-aid-northeast', 'Legal Aid of Arkansas (Northeast / Delta)',
  'legal_aid', 'legal_aid_org', 'AR', FALSE,
  ARRAY['any','eviction','housing','benefits','dv'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '870-793-4565', 'https://arlegalaid.org', 'https://arlegalaid.org',
  'Northeast Arkansas and Delta counties — housing, family, benefits, DV, consumer.',
  'Free', ARRAY['English','Spanish'],
  'https://arlegalaid.org', '2026-04', 0, 0),

('ar-compie', 'COMPIE — Center for Marshallese and Pacific Islander Excellence',
  'benefits_navigation', 'nonprofit', 'AR', FALSE,
  ARRAY['immigration','benefits','healthcare','any'], ARRAY['immigrants','marshallese'],
  FALSE, '1_week', FALSE,
  '479-316-0050', NULL, NULL,
  'Springdale AR — Marshallese and Pacific Islander community. Largest Marshallese population outside Pacific.',
  'Free', ARRAY['English','Marshallese'],
  NULL, '2026-04', 0, 0),

('ar-housing-adfa', 'Arkansas Development Finance Authority (ADFA)',
  'rental_assistance', 'state', 'AR', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '501-682-5900', 'https://arkansasfinance.com', 'https://arkansasfinance.com',
  'Low-income AR renters — Section 8/HCV, HOME, rental assistance.',
  'Free', ARRAY['English','Spanish'],
  'https://arkansasfinance.com', '2026-04', 0, 0);
