
-- ============================================================
-- MIGRATION 018: Seed Engine Registry V3
-- Strict extraction — nothing invented
-- ============================================================

INSERT INTO engine_registry_v3 (
  engine_name, file_path, router_export, approuter_key,
  layer, family, status,
  tables_used, llm_calls, notes,
  has_warning, warning_codes, confirmed_live,
  created_at, updated_at
) VALUES

-- ─── FULLY IMPLEMENTED — CONFIRMED LIVE ────────────────────

('intakeRouter',
  'server/routers.ts',
  'export const intakeRouter = router({...})',
  'intake: intakeRouter',
  'L0', 'Intake', 'fully_implemented',
  ARRAY['cases','pipeline_events','audit_trail','notifications'],
  '1 LLM per user message',
  'Guided intake (LLM conversational) and direct case creation. Sets pipelineType, description, domain context. Also hosts generateActionPath endpoint (1 LLM per case). 51 pipeline types.',
  FALSE, NULL, TRUE, 0, 0),

('upload-route',
  'server/upload-route.ts',
  'Express route — not tRPC', NULL,
  'L1', 'Ingestion', 'fully_implemented',
  ARRAY['documents','corpus_snapshots','audit_trail'],
  'none (deterministic)',
  'Creates document records with S3 storage and SHA-256 hash. Normal path does NOT call enqueueDocument. Override path (duplicate replacement) correctly calls enqueueDocument inline. Three enqueueDocument() calls in routers.ts (~lines 180, 201, 267) do not propagate snapshotId — Gate 2.5 fix pending.',
  TRUE, ARRAY['WARNING-01'], TRUE, 0, 0),

('analysis-pipeline',
  'server/analysis-pipeline.ts',
  NULL, NULL,
  'L2', 'Parsing / Extraction', 'fully_implemented',
  ARRAY['documents','entities','quotes','events','claims','relationships','signal_flags','corpus_snapshots','pipeline_events','audit_trail'],
  '1 LLM/doc (Pass1: entities+metadata) + 1 LLM/doc (Pass2: events+claims) + 1 LLM/case (Pass3: correlation)',
  'In-memory processingQueue. Pass1=entities+metadata, Pass2=events+claims, Pass3=cross-doc correlation. Dequeue-time fallback resolves snapshotId via getLatestSnapshot when not propagated. Docker restart loses queue — startup recovery sweep recommended but not implemented.',
  TRUE, ARRAY['WARNING-01','WARNING-02'], TRUE, 0, 0),

('gap-detection',
  'server/gap-detection.ts',
  NULL, NULL,
  'L4', 'Validation', 'fully_implemented',
  ARRAY['missing_records','claims','corpus_snapshots','audit_trail'],
  'none (deterministic)',
  'Zero LLM. Triggered automatically after Pass 3. Active domain rule sets: policemisconduct, icwa, insurance, elderabuse/nursing/guardianship. All other pipeline types skip gap detection.',
  FALSE, NULL, TRUE, 0, 0),

('domain-rules',
  'server/domain-rules.ts',
  NULL, NULL,
  'L4', 'Validation', 'fully_implemented',
  NULL,
  'none (deterministic)',
  '4 active rule sets + 2 aliases. Covers 6 of 51 pipeline types. 45 pipeline types have no domain rules — gap detection skipped for those.',
  FALSE, NULL, TRUE, 0, 0),

('akb-lookup',
  'server/akb-lookup.ts',
  NULL, NULL,
  'L3', 'Registry/Knowledge', 'fully_implemented',
  ARRAY['missing_records','foia_requests'],
  'none (deterministic)',
  'AKB coverage Washington State only as of Session 7 / March 2026. Zero LLM. Resolves agency from missing record type for FOIA letter generation.',
  TRUE, ARRAY['WARNING-07'], TRUE, 0, 0),

('foia-generator',
  'server/foia-generator.ts',
  NULL, NULL,
  'L8', 'Procedural/Action', 'fully_implemented',
  ARRAY['foia_requests','missing_records','cases','audit_trail'],
  '1 LLM per request letter',
  'Triggered from main router — gated (requires sealed snapshot). 11-status lifecycle: draft → ready → sent → acknowledged → processing → partial_response → completed | denied → appeal_filed → appeal_completed | expired.',
  TRUE, ARRAY['WARNING-07'], TRUE, 0, 0),

('pattern-detection',
  'server/pattern-detection.ts',
  NULL, NULL,
  'L6', 'Pattern/Signal', 'fully_implemented',
  ARRAY['pattern_signatures','pattern_occurrences','entities','findings','audit_trail'],
  'none (deterministic)',
  'Zero LLM. Manual trigger (scan button). 6 pattern types: entity_recurrence, agency_behavior, denial_language_pattern, foia_denial_pattern, record_gap_pattern, temporal_anomaly. SHA-256 signature generation. Cross-case. Visible at /patterns.',
  FALSE, NULL, TRUE, 0, 0),

('narrative-generator',
  'server/narrative-generator.ts',
  NULL, NULL,
  'L9', 'Export/Assembly', 'fully_implemented',
  ARRAY['narratives','events','quotes','claims','findings','foia_requests','corpus_snapshots','audit_trail'],
  '1 LLM per generation',
  'Manual trigger. Chronological Statement of Facts with source references. Timeline assembly → chronological grouping → LLM narrative → source map → persistence. Visible at /narrative.',
  FALSE, NULL, TRUE, 0, 0),

('collaborationRouter',
  'server/routers.ts',
  'export const collaborationRouter = router({...})',
  'collaboration: collaborationRouter',
  'L10', 'Oversight', 'fully_implemented',
  ARRAY['collaborators','cases','audit_trail','notifications'],
  'none (deterministic)',
  'Case sharing with READ_ONLY/WRITE access levels.',
  FALSE, NULL, TRUE, 0, 0),

('shareRouter',
  'server/routers.ts',
  'export const shareRouter = router({...})',
  'share: shareRouter',
  'L10', 'Oversight', 'fully_implemented',
  ARRAY['share_links','cases','audit_trail'],
  'none (deterministic)',
  'Public read-only case sharing via token links. Notifications: share_accessed, share_expiring.',
  FALSE, NULL, TRUE, 0, 0),

('presentationsRouter',
  'server/routers.ts',
  'export const presentationsRouter = router({...})',
  'presentations: presentationsRouter',
  'L9', 'Export/Assembly', 'fully_implemented',
  ARRAY['presentations','cases','findings','audit_trail'],
  NULL,
  'Slide deck generation from case data.',
  FALSE, NULL, TRUE, 0, 0),

('CDA Pipeline (cdaRouter)',
  'server/routers.ts + server/cda-bundle.ts + server/cda-bundle-zip.ts',
  'sub-router within routers.ts — exact export name unconfirmed',
  'cda: cdaRouter (assumed)',
  'L5', 'Evidence', 'fully_implemented',
  ARRAY['cda_runs','cda_documents','cda_quotes','cda_denial_reasons','cda_policy_clauses','cda_claim_ledger','cda_comparison_matrix','cda_contradictions','cda_evidence_gaps','pattern_occurrences'],
  'up to 9 LLM calls per run',
  'Independent 9-stage pipeline T1-T9. Spec v1.0-PATCH3 — T6 heading-overlap mapping table deterministic, T7 controlled judgment. Gate: runCDA independent of main pipeline. Visible at /cda and /cda/:id.',
  FALSE, NULL, TRUE, 0, 0),

('Phase 2 Analysis Pipeline',
  'server/routers.ts (trigger surface) + sub-modules unnamed in thread',
  'runPhase2Analysis endpoint within main router',
  'embedded in main router',
  'L7', 'Interpretation', 'fully_implemented',
  ARRAY['corpus_snapshots','findings','audit_trail'],
  '1 LLM per sealed snapshot (orchestration only)',
  'Requires sealed snapshot. Sub-modules: Evidence Detection, Structured Notes Detection, Temporal Anchors, Temporal Gap Detection, Temporal Ordering, Full Orchestration. Results in Spine Viewer. All detection rules deterministic — zero LLM except orchestration.',
  FALSE, NULL, TRUE, 0, 0),

('gate-helpers / gate-schema',
  'server/gate-helpers.ts + server/gate-schema.ts',
  NULL, NULL,
  'L4', 'Validation / Control', 'fully_implemented',
  ARRAY['corpus_snapshots'],
  'none (deterministic)',
  'assertActionAllowed() enforces gate progression. Stages: EXTRACTION → CLAIM_BUILD → CORRELATION → FINDINGS → READY_TO_SEAL → SEALED. Three enqueueDocument() calls use assertActionAllowed correctly but fail to propagate snapshotId downstream — Gate 2.5 pending.',
  TRUE, ARRAY['WARNING-01'], TRUE, 0, 0),

('crypto-signing / export-manifest',
  'server/crypto-signing.ts + server/export-manifest.ts',
  NULL, NULL,
  'L9', 'Export/Assembly', 'fully_implemented',
  ARRAY['corpus_snapshots','audit_trail'],
  'none (deterministic)',
  'Ed25519 signing of sealed snapshots for tamper detection. Zero LLM.',
  FALSE, NULL, TRUE, 0, 0),

('export-streaming',
  'server/export-streaming.ts',
  NULL, NULL,
  'L9', 'Export/Assembly', 'fully_implemented',
  ARRAY['corpus_snapshots','documents','entities','quotes','events','claims','relationships','findings','foia_requests','audit_trail'],
  'none (deterministic)',
  'JSON export. Risk Zone A: line 331 falls back to getLatestSnapshot when no explicit snapshotId passed. SpineViewer uses explicit snapshotId correctly — export route should enforce same. Impact: low-medium.',
  TRUE, ARRAY['WARNING-02'], TRUE, 0, 0),

('hard-delete-canonical',
  'server/hard-delete-canonical.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'fully_implemented',
  ARRAY['cases','documents','entities','quotes','events','claims','relationships','signal_flags','findings','corpus_snapshots','audit_trail'],
  'none (deterministic)',
  'Cascade deletion with S3 cleanup and reference counting. Canonical — no other delete paths should exist.',
  FALSE, NULL, TRUE, 0, 0),

('storage-spine',
  'server/storage-spine.ts',
  NULL, NULL,
  'L1', 'Ingestion', 'fully_implemented',
  ARRAY['documents'],
  'none (deterministic)',
  'S3 storage abstraction layer.',
  FALSE, NULL, TRUE, 0, 0),

('tone-validator',
  'server/tone-validator.ts',
  NULL, NULL,
  'L4', 'Validation', 'fully_implemented',
  NULL,
  'none (deterministic)',
  'Ensures AI outputs maintain neutral forensic language. Zero LLM. In-process only.',
  FALSE, NULL, TRUE, 0, 0),

('entity-dedup',
  'server/entity-dedup.ts',
  NULL, NULL,
  'L2', 'Extraction', 'fully_implemented',
  ARRAY['entities'],
  'none (deterministic)',
  'Fuzzy matching to merge duplicate entities. Zero LLM.',
  FALSE, NULL, TRUE, 0, 0),

('entity-filter',
  'server/entity-filter.ts',
  NULL, NULL,
  'L2', 'Extraction', 'fully_implemented',
  ARRAY['entities'],
  'none (deterministic)',
  'Filters noise entities (dates, numbers, generic terms). Zero LLM.',
  FALSE, NULL, TRUE, 0, 0),

('quote-filter',
  'server/quote-filter.ts',
  NULL, NULL,
  'L2', 'Extraction', 'fully_implemented',
  ARRAY['quotes'],
  'none (deterministic)',
  'Filters low-value quotes (headers, footers, boilerplate). Zero LLM.',
  FALSE, NULL, TRUE, 0, 0),

('date-normalizer',
  'server/date-normalizer.ts',
  NULL, NULL,
  'L2', 'Extraction', 'fully_implemented',
  ARRAY['events','claims'],
  'none (deterministic)',
  'Normalizes date formats for consistent sorting. Zero LLM.',
  FALSE, NULL, TRUE, 0, 0),

('relationship-type-validator',
  'server/relationship-type-validator.ts',
  NULL, NULL,
  'L4', 'Validation', 'fully_implemented',
  ARRAY['relationships'],
  'none (deterministic)',
  'Validates and reclassifies relationship types.',
  FALSE, NULL, TRUE, 0, 0),

('document-checklists',
  'server/document-checklists.ts',
  NULL, NULL,
  'L4', 'Validation', 'fully_implemented',
  ARRAY['documents','missing_records'],
  'none (deterministic)',
  'Domain-specific document requirement checklists.',
  FALSE, NULL, TRUE, 0, 0),

('remediation-classification',
  'server/remediation-classification.ts',
  NULL, NULL,
  'L4', 'Validation', 'fully_implemented',
  ARRAY['documents'],
  'none (deterministic)',
  'Classifies failed documents for recovery path.',
  FALSE, NULL, TRUE, 0, 0),

('extraction-recovery',
  'server/extraction-recovery.ts',
  NULL, NULL,
  'L2', 'Extraction', 'fully_implemented',
  ARRAY['documents','audit_trail'],
  'none (deterministic)',
  'Auto-retry with exponential backoff for failed extractions. Zero LLM.',
  FALSE, NULL, TRUE, 0, 0),

('batch-rerun',
  'server/batch-rerun.ts',
  NULL, NULL,
  'L5', 'Evidence', 'fully_implemented',
  ARRAY['findings','documents','audit_trail'],
  '1 LLM per finding',
  'Bulk re-analysis of all findings with updated prompts. Manual trigger.',
  FALSE, NULL, TRUE, 0, 0),

('claim-backfill',
  'server/claim-backfill.ts',
  NULL, NULL,
  'L5', 'Evidence', 'fully_implemented',
  ARRAY['claims','documents'],
  'none (deterministic)',
  'Backfills missing document references in claims.',
  FALSE, NULL, TRUE, 0, 0),

('Governance Layer',
  'server/routers.ts (governance endpoints)',
  'endpoints within main router',
  'embedded in main router',
  'L11', 'Sovereign Control', 'fully_implemented',
  ARRAY['governance_log','data_streams','sunam_thresholds','signals'],
  'none (deterministic)',
  'Validated live: 4 governed events confirmed, hash chain verified, corruption detection confirmed. Operations: governedDataStreamToggle, governedThresholdUpdate, governedSignalSuppression. SHA-256 hash chain, 12 required fields per entry. actorId stored as hash only. Rationale validation rejects "test". No-op writes logged without rejection (design decision).',
  TRUE, ARRAY['WARNING-06'], TRUE, 0, 0),

-- ─── PARTIAL / SCAFFOLDED ────────────────────────────────────

('Sunam Executor',
  'server/sunam-executor.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'partial',
  ARRAY['audit_trail','sunam_thresholds','engine_registry'],
  NULL,
  'Main decision engine — interprets natural language commands and routes to tools. governedThresholdUpdate confirmed live (passThreshold updated, seqNo=2). Not confirmed fully wired to routers.',
  TRUE, ARRAY['WARNING-05'], TRUE, 0, 0),

('data-stream-manager',
  'server/data-stream-manager.ts',
  NULL, NULL,
  'L3', 'Registry/Knowledge', 'partial',
  ARRAY['data_streams','governance_log','audit_trail'],
  NULL,
  'Manages data ingestion schedules. cfpb-complaints stream confirmed present and togglable (seqNo=1 in governance validation). Full stream inventory not documented.',
  TRUE, ARRAY['WARNING-05'], TRUE, 0, 0),

-- ─── UNKNOWN ────────────────────────────────────────────────

('system-copilot-sunam',
  'server/system-copilot-sunam.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'unknown',
  NULL, NULL,
  'Conversational AI interface for Sunam. Relationship to intakeRouter unclear.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('admin-sovereign-control',
  'server/admin-sovereign-control.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'unknown',
  ARRAY['sunam_thresholds','signals','governance_log'],
  NULL,
  'Admin interface for system configuration and control.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('export-spine-engine',
  'server/export-spine-engine.ts',
  NULL, NULL,
  'L9', 'Export/Assembly', 'unknown',
  NULL, NULL,
  'Exports entire system state for portability. Distinct from export-streaming.ts (case-level).',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('restore-spine-engine',
  'server/restore-spine-engine.ts',
  NULL, NULL,
  'L9', 'Export/Assembly', 'unknown',
  NULL, NULL,
  'Restores system from exported state.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('entity-intelligence',
  'server/entity-intelligence.ts',
  NULL, NULL,
  'L6', 'Pattern/Signal', 'unknown',
  ARRAY['entities','findings','pattern_signatures','pattern_occurrences'],
  NULL,
  'Analyzes entity behavior patterns and anomalies. Router wiring not confirmed.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('entity-evidence-threshold',
  'server/entity-evidence-threshold.ts',
  NULL, NULL,
  'L5', 'Evidence', 'unknown',
  ARRAY['entities','findings'],
  NULL,
  'Determines evidence sufficiency for entity claims.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('entity-transparency',
  'server/entity-transparency.ts',
  NULL, NULL,
  'L6', 'Pattern/Signal', 'unknown',
  ARRAY['entities','relationships'],
  NULL,
  'Exposes entity relationships and connections.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('litigation-correlation-service',
  'server/litigation-correlation-service.ts',
  NULL, NULL,
  'L6', 'Pattern/Signal', 'unknown',
  ARRAY['entities','findings'],
  NULL,
  'Correlates entities with litigation history.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('problem-interpreter-service',
  'server/problem-interpreter-service.ts',
  NULL, NULL,
  'L0', 'Intake', 'unknown',
  ARRAY['cases'],
  NULL,
  'Interprets user problems into system categories.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('evidence-dossier',
  'server/evidence-dossier.ts',
  NULL, NULL,
  'L5', 'Evidence', 'unknown',
  ARRAY['findings','quotes','entities','claims'],
  NULL,
  'Compiles evidence for each detected pattern.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('investigative-query-engine',
  'server/investigative-query-engine.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  NULL, NULL,
  'Allows complex queries across all data.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('systemic-intelligence-map',
  'server/systemic-intelligence-map.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  ARRAY['pattern_signatures','entities','findings'],
  NULL,
  'Maps systemic patterns and structural issues.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('institutional-accountability',
  'server/institutional-accountability.ts',
  NULL, NULL,
  'L10', 'Oversight', 'unknown',
  ARRAY['entities','pattern_signatures','findings'],
  NULL,
  'Tracks institutional responsibility for patterns.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('regulatory-capture',
  'server/regulatory-capture.ts',
  NULL, NULL,
  'L10', 'Oversight', 'unknown',
  NULL, NULL,
  'Detects regulatory capture and conflicts of interest.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('crisis-prediction',
  'server/crisis-prediction.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  ARRAY['signals','pattern_signatures'],
  NULL,
  'Predicts imminent crises based on patterns.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('harm-index-service',
  'server/harm-index-service.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  NULL, NULL,
  'Quantifies harm to individuals and communities.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('harm-map-service',
  'server/harm-map-service.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  NULL, NULL,
  'Geographic/demographic mapping of harm.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('risk-forecast-service',
  'server/risk-forecast-service.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  NULL, NULL,
  'Forecasts future risk based on current patterns.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('systemic-risk-forecast',
  'server/systemic-risk-forecast.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  NULL, NULL,
  'Forecasts systemic-level risks.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('systemic-simulation',
  'server/systemic-simulation.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  NULL, NULL,
  'Simulates outcomes of policy/intervention changes.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('attorney-match-service',
  'server/attorney-match-service.ts',
  NULL, NULL,
  'L8', 'Procedural/Action', 'unknown',
  NULL, NULL,
  'Matches users with appropriate legal representation.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('case-link-service',
  'server/case-link-service.ts',
  NULL, NULL,
  'L8', 'Procedural/Action', 'unknown',
  ARRAY['cases'],
  NULL,
  'Links user situations to relevant cases.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('intervention-timeline-engine',
  'server/intervention-timeline-engine.ts',
  NULL, NULL,
  'L8', 'Procedural/Action', 'unknown',
  NULL, NULL,
  'Plans intervention timelines and deadlines.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('time-travel-engine',
  'server/time-travel-engine.ts',
  NULL, NULL,
  'L7', 'Interpretation', 'unknown',
  NULL, NULL,
  'Analyzes historical precedent and counterfactuals.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('public-alerting',
  'server/public-alerting.ts',
  NULL, NULL,
  'L10', 'Oversight', 'unknown',
  NULL, NULL,
  'Alerts public about systemic issues.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('public-transparency',
  'server/public-transparency.ts',
  NULL, NULL,
  'L10', 'Oversight', 'unknown',
  NULL, NULL,
  'Exposes findings to public.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('external-collaboration',
  'server/external-collaboration.ts',
  NULL, NULL,
  'L10', 'Oversight', 'unknown',
  NULL, NULL,
  'Coordinates with external organizations.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0),

('executor-service',
  'server/executor-service.ts',
  NULL, NULL,
  'L11', 'Sovereign Control', 'unknown',
  ARRAY['engine_registry','audit_trail'],
  NULL,
  'Generic execution framework. All engines expected to be registered in engineRegistry and wrapped with withEngineTracking(). Per-engine compliance not confirmed.',
  TRUE, ARRAY['WARNING-05'], FALSE, 0, 0);

