-- Restore the runtime stream registry that predates its first checked-in Atlas
-- recovery migration. The deliberately nullable legacy/current column pairs
-- match the production contract while grants remain least-privilege.

create table if not exists public.data_stream_registry (
  id integer generated by default as identity primary key,
  stream_id text,
  stream_name text,
  source_url text,
  mode text,
  status text,
  poll_interval integer,
  last_poll bigint,
  records_ingested integer,
  consecutive_failures integer,
  last_error_message text,
  created_at bigint,
  updated_at bigint,
  stream_id_dsr text,
  stream_name_dsr text,
  stream_type_dsr text,
  source_url_dsr text,
  update_freq_dsr text,
  signal_weight_dsr integer,
  confidence_multiplier_dsr integer,
  enabled_dsr boolean,
  description_dsr text,
  field_mapping_dsr text,
  records_ingested_dsr integer,
  signals_generated_dsr integer,
  last_ingested_at_dsr text,
  source_dsr text,
  api_url_dsr text,
  jurisdiction_dsr text,
  domain_dsr text,
  cron_expression_dsr text,
  last_run_status_dsr text,
  last_success_at_dsr text,
  last_failure_at_dsr bigint,
  last_error_type_dsr text,
  last_error_message_dsr text,
  last_http_status_dsr text,
  failure_count_dsr integer,
  consecutive_failures_dsr integer,
  retry_after_at_dsr bigint,
  auto_disabled_dsr boolean,
  disabled_reason_dsr text,
  last_records_ingested_dsr integer,
  last_signals_generated_dsr integer,
  post_processing_engine_name_dsr text,
  parser_mode_dsr text,
  created_at_dsr integer,
  updated_at_dsr bigint
);

alter table public.data_stream_registry enable row level security;

create policy authenticated_read_data_stream_registry
  on public.data_stream_registry for select to authenticated using (true);
create policy service_all_data_stream_registry
  on public.data_stream_registry for all to service_role
  using (true) with check (true);

revoke all on table public.data_stream_registry
  from public, anon, authenticated;
grant select on table public.data_stream_registry to authenticated;
grant all on table public.data_stream_registry to service_role;

revoke all on sequence public.data_stream_registry_id_seq
  from public, anon, authenticated;
grant usage, select on sequence public.data_stream_registry_id_seq
  to service_role;
