
-- ============================================================
-- MIGRATION 034: Seed claim elements, metadata, statutes
-- From inline JSON — verified against USC/CFR sources
-- ============================================================

-- CLAIM TYPE METADATA
INSERT INTO claim_type_metadata (claim_type, domain, statute, win_probability, avg_timeline_months, appeal_pathway, enforcement_pathways, state_variation) VALUES
('SSDI_Denial','BENEFITS','42 USC § 405',0.48,30,'SSA → Administrative Law Judge (ALJ) → Appeals Council → Federal Court',ARRAY['SSA administrative appeal'],NULL),
('Medicaid_Wrongful_Denial','BENEFITS','42 USC § 1396a',0.65,6,NULL,ARRAY['State Medicaid agency hearing','Federal court review'],'Significant — income limits, categorical eligibility vary by state'),
('SNAP_Wrongful_Denial','BENEFITS','7 USC § 2011 et seq',0.70,3,'State SNAP agency → Administrative hearing → Federal District Court',ARRAY['State SNAP administrative hearing','Federal court'],NULL),
('Housing_Discrimination','CIVIL_RIGHTS','42 USC § 3601',0.80,12,NULL,ARRAY['HUD complaint (100-day investigation)','Private Fair Housing Act lawsuit','State attorney general'],NULL),
('Employment_Discrimination','CIVIL_RIGHTS','42 USC § 2000e',0.70,18,NULL,ARRAY['EEOC charge (180-300 day investigation)','Right to Sue + federal lawsuit','State agency parallel filing'],NULL),
('Wage_Theft_Unpaid_Wages','EMPLOYMENT','29 USC § 201 et seq',0.75,12,NULL,ARRAY['DOL Wage & Hour complaint','State labor board complaint','Private FLSA lawsuit'],NULL),
('Wrongful_Termination_At_Will','EMPLOYMENT','State wrongful termination statutes',0.65,18,NULL,ARRAY['OSHA retaliation complaint (30-day deadline)','NLRB unfair labor practice charge','Private wrongful termination lawsuit'],NULL),
('Insurance_Coverage_Denial','HEALTHCARE','42 USC § 300gg et seq',0.60,12,NULL,ARRAY['Internal insurance appeal','External independent review (state-mandated)','Federal court APA challenge'],NULL),
('FOIA_Wrongful_Withholding','OVERSIGHT','5 USC § 552',0.70,12,NULL,ARRAY['Administrative appeal (internal)','Federal district court action under 5 USC § 552(a)(4)(B)','Attorney General civil action'],NULL);

-- CLAIM ELEMENTS — SSDI
INSERT INTO claim_elements_matrix (element_id, claim_type, domain, statute, element_name, description, evidence_types, confidence_threshold, proof_standard, evidence_examples) VALUES
('ssdi_001','SSDI_Denial','BENEFITS','42 USC § 405','Severe Medical Condition','Applicant has a medical condition severe enough to prevent substantial gainful activity (SGA defined as earnings > $1,550/month in 2024)',ARRAY['medical_records','physician_testimony','functional_capacity_evaluation','imaging_studies'],0.75,'Clear and convincing evidence of impairment severity',ARRAY['Hospital discharge summaries','MRI/CT scans','Doctor''s functional assessment','Pain journals','Treatment records']),
('ssdi_002','SSDI_Denial','BENEFITS','42 USC § 405','Duration of Condition','Medical condition must last or be expected to last at least 12 months or result in death',ARRAY['medical_prognosis','physician_statement','treatment_duration'],0.70,'Physician opinion on prognosis with timeline',ARRAY['Doctor''s letter stating expected duration','Specialist prognosis','Treatment plan showing 12+ month duration']),
('ssdi_003','SSDI_Denial','BENEFITS','42 USC § 405','Work History & Coverage','Applicant worked enough years and recently enough to qualify for SSDI (typically 20 of last 40 quarters)',ARRAY['tax_returns','W2_forms','earnings_record','social_security_statement'],0.95,'SSA earnings record verification (automatic)',ARRAY['SSA statement of earnings','W-2s','Tax returns']),
('ssdi_004','SSDI_Denial','BENEFITS','42 USC § 405','Inability to Work at Substantial Gainful Level','Applicant cannot earn more than $1,550/month (2024 SGA limit) due to impairment',ARRAY['work_history','functional_limitations','medical_evidence','attempt_to_work_documentation'],0.80,'Functional capacity evidence showing inability to reach SGA',ARRAY['Functional capacity evaluation','Doctor''s statement of limitations','Job search attempts + documentation','Layoff/termination due to condition']),

-- CLAIM ELEMENTS — Medicaid
('mcaid_001','Medicaid_Wrongful_Denial','BENEFITS','42 USC § 1396a','Categorical Eligibility','Applicant falls within a covered category: low-income parent, pregnant woman, child, elderly, or disabled',ARRAY['family_documents','medical_documentation','birth_certificate','age_verification'],0.90,'Documentary evidence of categorical status',ARRAY['Birth certificate (child)','Pregnancy test results','SSDI award letter (disabled)']),
('mcaid_002','Medicaid_Wrongful_Denial','BENEFITS','42 USC § 1396a','Income Limit Compliance','Applicant''s income is below state Medicaid income limit (varies by state, typically 138% federal poverty line)',ARRAY['pay_stubs','tax_returns','unemployment_documents','bank_statements'],0.92,'3-month average income documentation',ARRAY['Recent pay stubs (if employed)','Tax return (if self-employed)','UI statement (if unemployed)']),
('mcaid_003','Medicaid_Wrongful_Denial','BENEFITS','42 USC § 1396a','Citizenship / Immigration Status','Applicant is US citizen OR qualified immigrant (varies by state)',ARRAY['birth_certificate','passport','green_card','SSN_documentation'],0.95,'Legal citizenship documentation',ARRAY['US birth certificate','Passport','Green card','REAL ID compliant driver''s license']),
('mcaid_004','Medicaid_Wrongful_Denial','BENEFITS','42 USC § 1396a','Residency','Applicant is state resident (varies by state residency requirement)',ARRAY['address_proof','lease_agreement','utility_bill','voting_registration'],0.85,'Any two forms of address documentation',ARRAY['Lease/mortgage (recent)','Utility bill (recent)','Mail from government agency','Voter registration']),

-- CLAIM ELEMENTS — Housing Discrimination
('housing_001','Housing_Discrimination','CIVIL_RIGHTS','42 USC § 3601','Protected Class Status','Applicant belongs to protected class: race, color, national origin, religion, sex, familial status, disability',ARRAY['visual_identification','self_identification','family_documents'],0.95,'Applicant testimony or documentary evidence',ARRAY['Applicant testimony','Birth certificate showing race/ethnicity','Medical documentation of disability']),
('housing_002','Housing_Discrimination','CIVIL_RIGHTS','42 USC § 3601','Housing Availability','Landlord was advertising or had available housing unit at time of alleged discrimination',ARRAY['listing_screenshots','craigslist_posts','lease_offered_to_others','landlord_testimony'],0.90,'Documentary evidence the unit was available',ARRAY['Listing showing ''Available Now''','Screenshots from Zillow/Craigslist','Lease signed by someone else for same unit']),
('housing_003','Housing_Discrimination','CIVIL_RIGHTS','42 USC § 3601','Adverse Action','Landlord denied application, lease, or facility access based on protected status',ARRAY['denial_letter','applicant_testimony','witness_testimony','landlord_statements'],0.85,'Clear rejection of housing application or access',ARRAY['Denial letter from landlord','Witness testimony of oral rejection','Email/text messages showing denial']),
('housing_004','Housing_Discrimination','CIVIL_RIGHTS','42 USC § 3601','Causal Connection','Adverse action was motivated by protected status (not legitimate reason)',ARRAY['comparative_treatment','landlord_statements','pattern_evidence','testing_evidence'],0.75,'Circumstantial evidence of discriminatory motive',ARRAY['Landlord admitted to race concern','Evidence landlord rented to similar non-protected applicants','Testing: White tester approved, Black tester denied']),

-- CLAIM ELEMENTS — Employment Discrimination
('emp_discrim_001','Employment_Discrimination','CIVIL_RIGHTS','42 USC § 2000e','Protected Class Status','Applicant/employee belongs to protected class: race, color, religion, sex, national origin',ARRAY['visual_identification','self_identification','birth_records'],0.95,'Applicant self-identification or objective record',ARRAY['Employee testimony','Birth certificate','Self-identification on job application']),
('emp_discrim_002','Employment_Discrimination','CIVIL_RIGHTS','42 USC § 2000e','Job Qualification','Applicant was qualified for the job (met minimum job requirements)',ARRAY['resume','job_description','hiring_standards','performance_reviews'],0.80,'Objective qualifications matched job requirements',ARRAY['Resume matching job requirements','Degrees/certifications required','Years of experience required']),
('emp_discrim_003','Employment_Discrimination','CIVIL_RIGHTS','42 USC § 2000e','Adverse Employment Action','Employer took adverse action: non-hire, termination, demotion, reduced pay, harassment',ARRAY['termination_letter','payroll_records','employment_records','witness_testimony'],0.92,'Documentary evidence of adverse action',ARRAY['Termination letter','Payroll showing wage reduction','Email from manager denying promotion']),
('emp_discrim_004','Employment_Discrimination','CIVIL_RIGHTS','42 USC § 2000e','Comparative Treatment','Employer treated similarly situated employee of different protected class more favorably',ARRAY['comparative_employee_records','witness_testimony','payroll_analysis','performance_data'],0.75,'Evidence similarly situated employee received better treatment',ARRAY['Male coworker kept job; female terminated for same conduct','White employee promoted; Black employee with higher ratings not promoted']),

-- CLAIM ELEMENTS — Wage Theft
('wage_001','Wage_Theft_Unpaid_Wages','EMPLOYMENT','29 USC § 201 et seq','Employer-Employee Relationship','Applicant was employee (not independent contractor) of named employer',ARRAY['tax_documents','employment_agreement','payroll_records','work_logs'],0.90,'Control test: employer controlled worker''s schedule, methods, tools',ARRAY['W-2 from employer','Employment agreement','Pay stubs with employer name','Text messages from manager scheduling work']),
('wage_002','Wage_Theft_Unpaid_Wages','EMPLOYMENT','29 USC § 201 et seq','Work Performed','Worker performed work for employer; work was part of employer''s business',ARRAY['testimony','timesheets','email_communications','witness_testimony','work_product'],0.85,'Credible evidence of hours worked',ARRAY['Worker testimony of hours','Timesheet (even informal)','Emails about work assignments','Coworker testimony','Photos of work completed']),
('wage_003','Wage_Theft_Unpaid_Wages','EMPLOYMENT','29 USC § 201 et seq','Unpaid or Underpaid Wages','Worker was paid less than minimum wage or overtime rate, or not paid at all',ARRAY['pay_stubs','bank_records','employer_statements','time_records'],0.88,'Wage calculation showing shortfall vs statutory minimum/overtime',ARRAY['Pay stub showing hours worked vs amount paid','Bank deposits less than hours worked','Employer email confirming unpaid hours']),
('wage_004','Wage_Theft_Unpaid_Wages','EMPLOYMENT','29 USC § 201 et seq','Statutory Minimum Wage / Overtime Rate','Work was covered by FLSA or state wage law; statutory rate applies',ARRAY['statute','agency_determination','work_type_analysis'],0.95,'Federal or state statute applies to work performed',ARRAY['Work falls under FLSA coverage','State minimum wage statute applies']),

-- CLAIM ELEMENTS — Insurance Denial
('ins_001','Insurance_Coverage_Denial','HEALTHCARE','42 USC § 300gg et seq','Valid Insurance Coverage','Claimant had active insurance policy with named insurer at time of service',ARRAY['insurance_card','policy_documentation','premium_payment_proof'],0.95,'Insurance was active on date of service',ARRAY['Insurance card','Policy declaration page','Premium payment receipt dated before service']),
('ins_002','Insurance_Coverage_Denial','HEALTHCARE','42 USC § 300gg et seq','Medical Service Provided','Covered service was provided by in-network provider on covered date',ARRAY['medical_records','provider_documentation','service_records','billing_statement'],0.92,'Provider documentation showing service on specific date',ARRAY['Doctor''s note dated service','Hospital discharge summary','Lab test results with date','Surgery report']),
('ins_003','Insurance_Coverage_Denial','HEALTHCARE','42 USC § 300gg et seq','Service Medically Necessary','Service was medically necessary and appropriate standard of care',ARRAY['medical_records','physician_testimony','clinical_evidence','standard_of_care_expert'],0.80,'Treating physician opinion supported by clinical evidence',ARRAY['Doctor''s note: ''MRI medically necessary for diagnosis''','Specialist testimony on standard of care','Clinical guidelines supporting treatment']),
('ins_004','Insurance_Coverage_Denial','HEALTHCARE','42 USC § 300gg et seq','Denial Was Wrongful','Insurer''s denial violated policy, law, or standard of care review',ARRAY['denial_letter','policy_analysis','expert_review','appeals_documentation'],0.75,'Denial contradicts policy language or violates ACA standards',ARRAY['Denial letter doesn''t match policy exclusions','Insurer applied wrong policy version','Reviewer was not physician despite medical determination required']),

-- CLAIM ELEMENTS — FOIA
('foia_001','FOIA_Wrongful_Withholding','OVERSIGHT','5 USC § 552','Timely FOIA Request','Claimant made FOIA request complying with statutory requirements',ARRAY['foia_request_letter','agency_acknowledgment','request_tracking_number'],0.95,'Request meets statutory specificity and administrative requirements',ARRAY['FOIA request letter naming agency','Tracking number from agency','Email confirmation of receipt']),
('foia_002','FOIA_Wrongful_Withholding','OVERSIGHT','5 USC § 552','Agency Custody of Records','Named agency has or had custody/control of responsive records',ARRAY['agency_statement','record_evidence','testimony'],0.90,'Records exist within agency files or are reasonably locatable',ARRAY['Records referenced in agency decisions','Agency email chains','Internal documents']),
('foia_003','FOIA_Wrongful_Withholding','OVERSIGHT','5 USC § 552','Wrongful Withholding','Agency withheld or delayed responsive records beyond statutory 20-day deadline',ARRAY['agency_correspondence','denial_letters','withholding_justification'],0.92,'Agency failed to respond within FOIA deadline or claimed improper exemption',ARRAY['No response after 20 days','Denial letter after deadline','Improper invocation of exemption']),
('foia_004','FOIA_Wrongful_Withholding','OVERSIGHT','5 USC § 552','No Valid Exemption','Agency''s claimed exemption (if any) does not apply; documents should be released',ARRAY['documents_themselves','exemption_analysis','agency_justification_review'],0.75,'Documents do not contain information covered by valid FOIA exemption',ARRAY['Documents are already public','No genuine national security concern','Exemption invoked for non-sensitive routine administrative records']);

-- STATUTES
INSERT INTO statutes_registry (statute_id, statute_number, statute_title, domain, jurisdiction, enacted, enforcement_agency, application_scope, key_clauses, claim_types_covered, statute_of_limitations, state_variation, website) VALUES
('benefits_001','42 USC § 301 et seq','Old Age, Survivors, and Disability Insurance (Social Security Act)','BENEFITS','federal','1935; amended multiple times through 2024','Social Security Administration (SSA)','Federal; applies nationwide. Covers retirement, survivors, disability insurance (SSDI) and Supplemental Security Income (SSI)','["§ 405: Appeals and judicial review of SSA determinations","§ 406: Attorney fees (capped at $6,000 or 25% of backpay, whichever is lower)","§ 423: Standards for disability determination (severe impairment lasting 12+ months)"]'::jsonb,ARRAY['SSDI_Denial','SSI_Denial','benefits_wrongful_termination'],'60 days for initial filing; no limit for ongoing appeals',NULL,'ssa.gov'),
('benefits_002','42 USC § 1396 et seq','Medicaid (Title XIX of Social Security Act)','BENEFITS','federal','1965; continuously amended','Centers for Medicare & Medicaid Services (CMS); state Medicaid agencies','Federal-state partnership; each state sets income/asset limits within federal minimums','["§ 1396a: Medicaid eligibility requirements","§ 1396d: Medicaid services covered","§ 1396n: Waivers for home and community-based services"]'::jsonb,ARRAY['Medicaid_Denial','Medicaid_Wrongful_Termination'],'No federal limit; state administrative appeals 30-90 days; federal review 2 years','Significant — income limits, asset tests, categorical eligibility vary by state','medicaid.gov'),
('benefits_003','7 USC § 2011 et seq','Supplemental Nutrition Assistance Program (SNAP)','BENEFITS','federal','1964; renamed 2008','USDA Food and Nutrition Service (FNS); state human services departments','Federal-state program. Income limit: 130% federal poverty line; asset limit: $2,500 (most states)','["§ 2015: Eligibility determination","§ 2020: Benefit amounts","§ 2022: Disqualifications"]'::jsonb,ARRAY['SNAP_Denial','SNAP_Wrongful_Termination'],'No federal limit; state appeal 30 days from notice; federal court review available',NULL,'fns.usda.gov/snap'),
('benefits_004','15 USC § 1601 et seq','Fair Debt Collection Practices Act (FDCPA)','BENEFITS','federal','1977','Federal Trade Commission (FTC); private right of action','Federal; applies to debt collectors. Covers phone calls, letters, threats, harassment','["§ 1692d: Prohibition on harassment, abuse, threats","§ 1692e: False or misleading representations","§ 1692g: Required debt verification","§ 1692k: Damages ($1,000 per lawsuit statutory; actual damages; attorney fees)"]'::jsonb,ARRAY['Debt_Collection_Violation'],'1 year from violation',NULL,'ftc.gov/articles/debt-collection'),
('civil_rights_001','42 USC § 2000e et seq','Title VII of the Civil Rights Act of 1964 (Employment Discrimination)','CIVIL_RIGHTS','federal','1964; amended by Civil Rights Act of 1991','Equal Employment Opportunity Commission (EEOC)','Federal; applies to employers with 15+ employees. Prohibits discrimination based on race, color, religion, sex, national origin','["§ 2000e-2: Unlawful employment practices","§ 2000e-5: EEOC charge filing (180 or 300 days)","§ 2000e-5(k): Right to Sue","§ 2000e-5(l): Damages (back pay, compensatory $50K-$300K cap, punitive, attorney fees)"]'::jsonb,ARRAY['Employment_Discrimination','Wrongful_Termination_Retaliation'],'180 or 300 days to file EEOC charge (varies by state)',NULL,'eeoc.gov'),
('civil_rights_002','42 USC § 3601 et seq','Fair Housing Act (FHA)','CIVIL_RIGHTS','federal','1968; amended 1988 (Fair Housing Amendments Act)','HUD Office of Fair Housing and Equal Opportunity (FHEO)','Federal; applies to housing discrimination based on race, color, national origin, religion, sex, familial status, disability','["§ 3603: Prohibited discrimination in housing","§ 3604: Discrimination in sale, rental, financing","§ 3613: Private right of action (damages + attorney fees)","§ 3614: HUD administrative proceedings (damages up to $16,000)"]'::jsonb,ARRAY['Housing_Discrimination','Housing_Denial'],'1 year from violation (for private suit); 1 year for HUD complaint',NULL,'hud.gov/fairhousing'),
('civil_rights_003','42 USC § 1983','Civil Rights Act of 1871 (Section 1983 civil rights action)','CIVIL_RIGHTS','federal','1871 (Ku Klux Klan Act); codified 1994','Private right of action (not government-enforced); federal courts','Federal; applies to government officials acting under color of law. Covers deprivation of constitutional or statutory rights','["§ 1983: Cause of action for deprivation of rights","§ 1988: Attorney fees (mandatory if prevail in civil rights action)","Qualified Immunity doctrine: Officers have immunity unless rights were ''clearly established''"]'::jsonb,ARRAY['Police_Accountability','Government_Misconduct','Civil_Rights_Violation'],'3 years (applies most state longer SOL, whichever is longer)',NULL,'justice.gov/civil-rights'),
('employment_001','29 USC § 201 et seq','Fair Labor Standards Act (FLSA)','EMPLOYMENT','federal','1938; amended multiple times','Department of Labor Wage & Hour Division (WHD)','Federal; applies to employers engaged in interstate commerce. Covers minimum wage, overtime, child labor','["§ 206: Federal minimum wage ($7.25/hour; states may set higher)","§ 207: Maximum hours and overtime (40 hrs/week @ 1.5x pay)","§ 215: Unlawful act (wage withholding)","§ 216: Penalties (back wages + liquidated damages + attorney fees)"]'::jsonb,ARRAY['Wage_Theft','Unpaid_Overtime','Minimum_Wage_Violation'],'3 years for back wages (2 years if non-willful)',NULL,'dol.gov/whd'),
('employment_002','29 USC § 651 et seq','Occupational Safety and Health Act (OSHA)','EMPLOYMENT','federal','1970','Occupational Safety and Health Administration (OSHA); state OSHA programs','Federal (+ state plans in some states). Covers workplace safety hazards; whistleblower protection','["§ 660: OSH Standards","§ 666: Occupational Safety and Health standards","§ 704: Whistleblower protection (retaliation for safety complaint prohibited; 30-day deadline to file)"]'::jsonb,ARRAY['Wrongful_Termination_Retaliation','Workplace_Safety_Violation'],'30 days to file OSHA retaliation complaint (strict deadline)',NULL,'osha.gov'),
('employment_003','29 USC § 2601 et seq','Family and Medical Leave Act (FMLA)','EMPLOYMENT','federal','1993','Department of Labor Wage & Hour Division','Federal; applies to employers with 50+ employees. Requires unpaid, job-protected leave','["§ 2614: FMLA rights (up to 12 weeks unpaid leave/year)","§ 2615: Prohibited acts (employer cannot retaliate for FMLA use)","§ 2617: Damages (back pay, reinstatement, damages)"]'::jsonb,ARRAY['FMLA_Violation','Wrongful_Termination_Retaliation'],'2 years (3 years for willful violation)',NULL,'dol.gov/agencies/whd/fmla'),
('healthcare_001','42 USC § 300gg et seq','Affordable Care Act (ACA) - Health Insurance Coverage Requirements','HEALTHCARE','federal','2010; amended multiple times through 2024','Centers for Medicare & Medicaid Services (CMS); HHS Office for Civil Rights; state insurance commissioners','Federal; applies to health insurance plans. Requires coverage of preventive services, mental health parity, no lifetime limits','["§ 2711: Preventive health services (no cost-sharing)","§ 2712: Dependent coverage (age 26)","§ 300gg-13: Mental Health Parity Act","§ 300gg-19: Prohibition on lifetime limits"]'::jsonb,ARRAY['Healthcare_Coverage_Denial','Mental_Health_Parity_Violation'],'No federal limit; administrative appeals vary (30-90 days)',NULL,'healthcare.gov'),
('oversight_001','5 USC § 552','Freedom of Information Act (FOIA)','OVERSIGHT','federal','1966; amended multiple times through 2024','Agency FOIA officers; federal courts (for enforcement)','Federal; applies to all federal agencies. Requires release of non-exempt records within 20 days','["§ 552(a)(3): FOIA request procedures","§ 552(a)(4): Agency response timeline (20 days + possible 10-day extension)","§ 552(b): Exemptions (9 total: national security, internal deliberations, trade secrets, privacy, etc)","§ 552(a)(4)(B): Judicial review","28 USC § 2412: Attorney fees (if plaintiff substantially prevails)"]'::jsonb,ARRAY['FOIA_Wrongful_Withholding','FOIA_Delay'],'Administrative appeal: 20 days; federal court: 6 years',NULL,'foia.gov'),
('oversight_002','5 USC § 551 et seq','Administrative Procedure Act (APA)','OVERSIGHT','federal','1946','Federal courts (judicial review); agency administrative law judges','Federal; applies to all federal agency rulemaking, adjudication, licensing decisions','["§ 553: Rulemaking (notice-and-comment requirement)","§ 554: Adjudication (hearing rights)","§ 706: Judicial review (arbitrary and capricious, abuse of discretion)"]'::jsonb,ARRAY['Government_Misconduct','Regulatory_Capture','Agency_Abuse'],'6 years',NULL,'justice.gov/atr'),
('oversight_003','41 USC § 4501 et seq','Whistleblower Protection Act','OVERSIGHT','federal','1989; amended 2002 (Sarbanes-Oxley), 2010 (Dodd-Frank)','Occupational Safety and Health Administration (OSHA) whistleblower program','Federal; protects employees who report violations of law, regulation, rule, or unsafe working conditions','["§ 4504: Whistleblower protection (prohibition on retaliation)","§ 4505: Remedy (reinstatement, back pay, damages for retaliation)"]'::jsonb,ARRAY['Whistleblower_Retaliation','Government_Accountability'],'30 days to file with OSHA (strict deadline)',NULL,'osha.gov/whistleblowers');

