
-- ============================================================
-- LUMINARI — MIGRATION 009
-- Seed: 29 Washington Federally Recognized Tribal Nations
-- Separate sovereigns. Not state subdivisions. Equal standing.
-- ============================================================

INSERT INTO tribal_jurisdictions (
  tribe_key, tribe_name, state_code, region, county,
  website_url, phone,
  tribal_court, tribal_social_services, tribal_housing,
  tribal_tanf, tribal_health, tribal_enrollment,
  treaty_rights_in_state, is_federally_recognized,
  created_at, updated_at
) VALUES

('wa-chehalis', 'Chehalis Tribe (Confederated Tribes of Chehalis Reservation)',
  'WA', 'Southwest', 'Grays Harbor/Thurston',
  'https://www.chehalistribe.org', '360-273-5911',
  'Chehalis Tribal Court', 'Chehalis Social Services', 'Chehalis Housing Authority',
  'Chehalis TANF', 'Chehalis Health Department', 'Chehalis Enrollment',
  TRUE, TRUE, 0, 0),

('wa-colville', 'Colville Tribes (Confederated Tribes of Colville Reservation)',
  'WA', 'Northeast', 'Ferry/Okanogan',
  'https://www.colvilletribes.com', '509-634-2200',
  'Colville Tribal Court', 'Colville Social Services', 'Colville Housing Authority',
  'Colville TANF', 'Colville Indian Health', 'Colville Enrollment',
  TRUE, TRUE, 0, 0),

('wa-cowiche', 'Cowiche Band (see Yakama Nation)',
  'WA', 'Central', 'Yakima',
  'https://www.yakamanation-nsn.gov', '509-865-5121',
  NULL, NULL, NULL, NULL, NULL, NULL,
  TRUE, TRUE, 0, 0),

('wa-hoh', 'Hoh Indian Tribe',
  'WA', 'Olympic Peninsula', 'Jefferson',
  'https://www.hohtribe-nsn.gov', '360-374-6582',
  'Hoh Tribal Court', 'Hoh Social Services', 'Hoh Housing',
  NULL, 'Hoh Health', 'Hoh Enrollment',
  TRUE, TRUE, 0, 0),

('wa-jamestown-sklallam', 'Jamestown S''Klallam Tribe',
  'WA', 'Olympic Peninsula', 'Clallam',
  'https://www.jamestowntribe.org', '360-683-1109',
  'Jamestown Tribal Court', 'Jamestown Social Services', 'Jamestown Housing',
  'Jamestown TANF', 'Jamestown Health', 'Jamestown Enrollment',
  TRUE, TRUE, 0, 0),

('wa-kalispel', 'Kalispel Tribe of Indians',
  'WA', 'Northeast', 'Pend Oreille',
  'https://www.kalispeltribe.com', '509-447-7000',
  'Kalispel Tribal Court', 'Kalispel Social Services', 'Kalispel Housing',
  NULL, 'Kalispel Health', 'Kalispel Enrollment',
  TRUE, TRUE, 0, 0),

('wa-lower-elwha', 'Lower Elwha Klallam Tribe',
  'WA', 'Olympic Peninsula', 'Clallam',
  'https://www.elwha.org', '360-452-8471',
  'Lower Elwha Tribal Court', 'Lower Elwha Social Services', 'Lower Elwha Housing',
  NULL, 'Lower Elwha Health', 'Lower Elwha Enrollment',
  TRUE, TRUE, 0, 0),

('wa-lummi', 'Lummi Nation',
  'WA', 'Northwest', 'Whatcom',
  'https://www.lummi-nsn.gov', '360-312-2000',
  'Lummi Tribal Court', 'Lummi Family Services', 'Lummi Housing Authority',
  'Lummi TANF', 'Lummi Health', 'Lummi Enrollment',
  TRUE, TRUE, 0, 0),

('wa-makah', 'Makah Indian Tribe',
  'WA', 'Olympic Peninsula', 'Clallam',
  'https://www.makah.com', '360-645-2201',
  'Makah Tribal Court', 'Makah Social Services', 'Makah Housing',
  NULL, 'Makah Health', 'Makah Enrollment',
  TRUE, TRUE, 0, 0),

('wa-muckleshoot', 'Muckleshoot Indian Tribe',
  'WA', 'Puget Sound', 'King/Pierce',
  'https://www.muckleshoot.nsn.us', '253-939-3311',
  'Muckleshoot Tribal Court', 'Muckleshoot Social Services', 'Muckleshoot Housing',
  'Muckleshoot TANF', 'Muckleshoot Health', 'Muckleshoot Enrollment',
  TRUE, TRUE, 0, 0),

('wa-nisqually', 'Nisqually Indian Tribe',
  'WA', 'South Puget Sound', 'Thurston',
  'https://www.nisqually-nsn.gov', '360-456-5221',
  'Nisqually Tribal Court', 'Nisqually Social Services', 'Nisqually Housing',
  'Nisqually TANF', 'Nisqually Health', 'Nisqually Enrollment',
  TRUE, TRUE, 0, 0),

('wa-nooksack', 'Nooksack Indian Tribe',
  'WA', 'Northwest', 'Whatcom',
  'https://www.nooksacktribe.org', '360-592-5176',
  'Nooksack Tribal Court', 'Nooksack Social Services', 'Nooksack Housing',
  'Nooksack TANF', 'Nooksack Health', 'Nooksack Enrollment',
  TRUE, TRUE, 0, 0),

('wa-port-gamble-sklallam', 'Port Gamble S''Klallam Tribe',
  'WA', 'Kitsap Peninsula', 'Kitsap',
  'https://www.pgst.nsn.us', '360-297-2646',
  'Port Gamble Tribal Court', 'Port Gamble Social Services', 'Port Gamble Housing',
  NULL, 'Port Gamble Health', 'Port Gamble Enrollment',
  TRUE, TRUE, 0, 0),

('wa-puyallup', 'Puyallup Tribe of Indians',
  'WA', 'South Puget Sound', 'Pierce',
  'https://www.puyallup-tribe.com', '253-597-6200',
  'Puyallup Tribal Court', 'Puyallup Social Services', 'Puyallup Housing Authority',
  'Puyallup TANF', 'Puyallup Health', 'Puyallup Enrollment',
  TRUE, TRUE, 0, 0),

('wa-quileute', 'Quileute Tribe',
  'WA', 'Olympic Peninsula', 'Jefferson/Clallam',
  'https://www.quileutenation.org', '360-374-6163',
  'Quileute Tribal Court', 'Quileute Social Services', 'Quileute Housing',
  NULL, 'Quileute Health', 'Quileute Enrollment',
  TRUE, TRUE, 0, 0),

('wa-quinault', 'Quinault Indian Nation',
  'WA', 'Olympic Peninsula', 'Grays Harbor/Jefferson',
  'https://www.quinaultindiannation.com', '360-276-8211',
  'Quinault Tribal Court', 'Quinault Social Services', 'Quinault Housing',
  'Quinault TANF', 'Quinault Health', 'Quinault Enrollment',
  TRUE, TRUE, 0, 0),

('wa-samish', 'Samish Indian Nation',
  'WA', 'San Juan Islands', 'Skagit/San Juan',
  'https://www.samishtribe.nsn.us', '360-293-6404',
  NULL, 'Samish Social Services', 'Samish Housing',
  NULL, 'Samish Health', 'Samish Enrollment',
  TRUE, TRUE, 0, 0),

('wa-sauk-suiattle', 'Sauk-Suiattle Indian Tribe',
  'WA', 'North Cascades', 'Snohomish',
  'https://www.sauk-suiattle.com', '360-436-0132',
  NULL, 'Sauk-Suiattle Social Services', 'Sauk-Suiattle Housing',
  NULL, 'Sauk-Suiattle Health', 'Sauk-Suiattle Enrollment',
  TRUE, TRUE, 0, 0),

('wa-shoalwater-bay', 'Shoalwater Bay Indian Tribe',
  'WA', 'Southwest', 'Pacific',
  'https://www.shoalwaterbay-nsn.gov', '360-267-6766',
  NULL, 'Shoalwater Bay Social Services', 'Shoalwater Bay Housing',
  NULL, 'Shoalwater Bay Health', 'Shoalwater Bay Enrollment',
  TRUE, TRUE, 0, 0),

('wa-skokomish', 'Skokomish Tribe',
  'WA', 'Hood Canal', 'Mason',
  'https://www.skokomish.org', '360-426-4232',
  'Skokomish Tribal Court', 'Skokomish Social Services', 'Skokomish Housing',
  NULL, 'Skokomish Health', 'Skokomish Enrollment',
  TRUE, TRUE, 0, 0),

('wa-snoqualmie', 'Snoqualmie Indian Tribe',
  'WA', 'Puget Sound', 'King/Snohomish',
  'https://www.snoqualmietribe.us', '425-888-6551',
  'Snoqualmie Tribal Court', 'Snoqualmie Social Services', 'Snoqualmie Housing',
  NULL, 'Snoqualmie Health', 'Snoqualmie Enrollment',
  TRUE, TRUE, 0, 0),

('wa-spokane', 'Spokane Tribe of Indians',
  'WA', 'Eastern', 'Stevens',
  'https://www.spokanetribe.com', '509-458-6500',
  'Spokane Tribal Court', 'Spokane Social Services', 'Spokane Housing Authority',
  'Spokane TANF', 'Spokane Health', 'Spokane Enrollment',
  TRUE, TRUE, 0, 0),

('wa-squaxin-island', 'Squaxin Island Tribe',
  'WA', 'South Puget Sound', 'Mason',
  'https://www.squaxinisland.org', '360-432-3800',
  'Squaxin Tribal Court', 'Squaxin Social Services', 'Squaxin Housing',
  'Squaxin TANF', 'Squaxin Health', 'Squaxin Enrollment',
  TRUE, TRUE, 0, 0),

('wa-stillaguamish', 'Stillaguamish Tribe of Indians',
  'WA', 'Puget Sound', 'Snohomish',
  'https://www.stillaguamish.com', '360-652-7362',
  NULL, 'Stillaguamish Social Services', 'Stillaguamish Housing',
  NULL, 'Stillaguamish Health', 'Stillaguamish Enrollment',
  TRUE, TRUE, 0, 0),

('wa-suquamish', 'Suquamish Tribe',
  'WA', 'Kitsap Peninsula', 'Kitsap',
  'https://www.suquamish.nsn.us', '360-598-3311',
  'Suquamish Tribal Court', 'Suquamish Social Services', 'Suquamish Housing',
  'Suquamish TANF', 'Suquamish Health', 'Suquamish Enrollment',
  TRUE, TRUE, 0, 0),

('wa-swinomish', 'Swinomish Indian Tribal Community',
  'WA', 'Puget Sound', 'Skagit',
  'https://www.swinomish.org', '360-466-3163',
  'Swinomish Tribal Court', 'Swinomish Social Services', 'Swinomish Housing',
  NULL, 'Swinomish Health', 'Swinomish Enrollment',
  TRUE, TRUE, 0, 0),

('wa-tulalip', 'Tulalip Tribes',
  'WA', 'Puget Sound', 'Snohomish',
  'https://www.tulaliptribes-nsn.gov', '360-651-4000',
  'Tulalip Tribal Court', 'Tulalip Human Services', 'Tulalip Housing Authority',
  'Tulalip TANF', 'Tulalip Health', 'Tulalip Enrollment',
  TRUE, TRUE, 0, 0),

('wa-upper-skagit', 'Upper Skagit Indian Tribe',
  'WA', 'North Cascades', 'Skagit',
  'https://www.upperskagit.com', '360-854-7000',
  'Upper Skagit Tribal Court', 'Upper Skagit Social Services', 'Upper Skagit Housing',
  NULL, 'Upper Skagit Health', 'Upper Skagit Enrollment',
  TRUE, TRUE, 0, 0),

('wa-yakama', 'Yakama Nation (Confederated Tribes and Bands of the Yakama Nation)',
  'WA', 'Central', 'Yakima/Klickitat',
  'https://www.yakamanation-nsn.gov', '509-865-5121',
  'Yakama Tribal Court', 'Yakama Social Services', 'Yakama Housing Authority',
  'Yakama TANF', 'Yakama Indian Health', 'Yakama Enrollment',
  TRUE, TRUE, 0, 0);

