
-- ============================================================
-- MIGRATION 010: Alabama, Tennessee, South Carolina programs
-- ============================================================

INSERT INTO programs (
  program_key, name, resource_type, provider_type,
  state_code, is_national, situation_tags, population_tags,
  income_threshold, turnaround, is_emergency,
  phone, application_url, website,
  eligibility, cost, languages,
  source_url, last_verified, created_at, updated_at
) VALUES

-- ─── ALABAMA ───────────────────────────────────────────────

('al-snap', 'Alabama SNAP / Food Assistance (DHR)',
  'food', 'state', 'AL', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '334-242-1773', 'https://dhr.alabama.gov', 'https://dhr.alabama.gov',
  'Income < 130% FPL — 67 county DHR offices. Apply online or at county DHR.',
  'Free', ARRAY['English','Spanish'],
  'https://dhr.alabama.gov', '2026-04', 0, 0),

('al-wic', 'WIC Alabama',
  'food', 'state', 'AL', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  '334-206-2942', 'https://adph.org/wic', 'https://adph.org/wic',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL.',
  'Free', ARRAY['English','Spanish'],
  'https://adph.org/wic', '2026-04', 0, 0),

('al-food-bank-north', 'Food Bank of North Alabama (Huntsville)',
  'food', 'nonprofit', 'AL', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '256-539-2256', 'https://foodbanknorthal.org', 'https://foodbanknorthal.org',
  'North Alabama — 11-county service area including Madison County.',
  'Free', ARRAY['English'],
  'https://foodbanknorthal.org', '2026-04', 0, 0),

('al-medicaid', 'Alabama Medicaid (Categorical Only — NOT Expanded)',
  'healthcare', 'state', 'AL', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['children','pregnant','disabled','seniors'],
  TRUE, '1_week', FALSE,
  '334-242-5000', 'https://medicaid.alabama.gov', 'https://medicaid.alabama.gov',
  'Children, pregnant women, parents below ~18% FPL, elderly, disabled. NOT expanded. Categorical only.',
  'Free', ARRAY['English','Spanish'],
  'https://medicaid.alabama.gov', '2026-04', 0, 0),

('al-fqhc-aphca', 'Alabama Primary Health Care Association (FQHCs)',
  'healthcare', 'fqhc', 'AL', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '334-263-0500', 'https://aphca.org', 'https://aphca.org',
  'Anyone regardless of insurance — 18+ FQHCs statewide; sliding scale primary, dental, behavioral health.',
  'Sliding scale', ARRAY['English','Spanish'],
  'https://aphca.org', '2026-04', 0, 0),

('al-legal-services', 'Legal Services Alabama (Statewide)',
  'legal_aid', 'legal_aid_org', 'AL', FALSE,
  ARRAY['any','eviction','housing','benefits','dv'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '866-456-4995', 'https://legalservicesalabama.org', 'https://legalservicesalabama.org',
  'All 67 Alabama counties — housing (eviction triage), family, benefits, DV, consumer. Only statewide legal aid.',
  'Free', ARRAY['English','Spanish'],
  'https://legalservicesalabama.org', '2026-04', 0, 0),

('al-acadv', 'Alabama Coalition Against Domestic Violence (ACADV)',
  'dv_services', 'nonprofit', 'AL', FALSE,
  ARRAY['dv','housing','mental_health','any'], ARRAY['dv_survivors','all'],
  FALSE, 'same_day', TRUE,
  '800-650-6522', 'https://acadv.org', 'https://acadv.org',
  'Statewide 24/7 crisis, shelter referral, safety planning.',
  'Free', ARRAY['English','Spanish'],
  'https://acadv.org', '2026-04', 0, 0),

('al-housing-finance', 'Alabama Housing Finance Authority (AHFA)',
  'rental_assistance', 'state', 'AL', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '334-244-9200', 'https://ahfa.com', 'https://ahfa.com',
  'Low-income AL renters — Section 8/HCV, HOME program, emergency rental assistance.',
  'Free', ARRAY['English'],
  'https://ahfa.com', '2026-04', 0, 0),

-- ─── TENNESSEE ─────────────────────────────────────────────

('tn-snap', 'Tennessee SNAP / Food Stamps (DHS)',
  'food', 'state', 'TN', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '615-313-4700', 'https://accesstn.org', 'https://accesstn.org',
  'Income < 130% FPL — 95 county DHS offices. ABAWD work requirements active.',
  'Free', ARRAY['English','Spanish'],
  'https://accesstn.org', '2026-04', 0, 0),

('tn-wic', 'WIC Tennessee',
  'food', 'state', 'TN', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  '615-741-7218', 'https://tn.gov/health/wic', 'https://tn.gov/health/wic',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL.',
  'Free', ARRAY['English','Spanish'],
  'https://tn.gov/health/wic', '2026-04', 0, 0),

('tn-food-bank-middle', 'Second Harvest Food Bank of Middle Tennessee (Nashville)',
  'food', 'nonprofit', 'TN', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '615-329-3491', 'https://secondharvestmidtn.org', 'https://secondharvestmidtn.org',
  'Middle Tennessee — 46-county service area including Nashville metro.',
  'Free', ARRAY['English','Spanish','Kurdish','Somali'],
  'https://secondharvestmidtn.org', '2026-04', 0, 0),

('tn-tenncare', 'TennCare (Tennessee Medicaid — Section 1115 Waiver)',
  'healthcare', 'state', 'TN', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['children','pregnant','disabled','seniors'],
  TRUE, '1_week', FALSE,
  '800-342-3145', 'https://accesstn.org', 'https://tenncare.gov',
  'Children, pregnant women, parents < 105% FPL, elderly, disabled. NOT standard Medicaid. No coverage for non-disabled childless adults.',
  'Free', ARRAY['English','Spanish'],
  'https://tenncare.gov', '2026-04', 0, 0),

('tn-fqhc-church-health', 'Church Health Memphis (Safety Net for Uninsured Adults)',
  'healthcare', 'fqhc', 'TN', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '901-272-0003', 'https://churchhealth.org', 'https://churchhealth.org',
  'Memphis area uninsured working adults — comprehensive primary care, dental, optical. Largest private non-profit for working uninsured in US.',
  'Sliding scale', ARRAY['English','Spanish'],
  'https://churchhealth.org', '2026-04', 0, 0),

('tn-tnpca', 'Tennessee Primary Care Association (FQHCs Statewide)',
  'healthcare', 'fqhc', 'TN', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '615-782-7400', 'https://tnpca.org', 'https://tnpca.org',
  'Anyone regardless of insurance — 50+ FQHCs statewide; sliding scale.',
  'Sliding scale', ARRAY['English','Spanish','Kurdish','Somali','Burmese'],
  'https://tnpca.org', '2026-04', 0, 0),

('tn-legal-aid-middle', 'Legal Aid Society of Middle Tennessee (Nashville)',
  'legal_aid', 'legal_aid_org', 'TN', FALSE,
  ARRAY['any','eviction','housing','benefits','dv'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '615-244-6610', 'https://las.org', 'https://las.org',
  'Middle Tennessee — housing, family, benefits, DV, consumer.',
  'Free', ARRAY['English','Spanish','Kurdish'],
  'https://las.org', '2026-04', 0, 0),

('tn-legal-aid-memphis', 'Memphis Area Legal Services',
  'legal_aid', 'legal_aid_org', 'TN', FALSE,
  ARRAY['any','eviction','housing','benefits','dv'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '901-523-8822', 'https://malsi.org', 'https://malsi.org',
  'Memphis and Shelby County — housing (eviction triage), family, benefits, DV.',
  'Free', ARRAY['English','Spanish'],
  'https://malsi.org', '2026-04', 0, 0),

('tn-irc-nashville', 'International Rescue Committee Nashville (Refugee Services)',
  'immigration', 'nonprofit', 'TN', FALSE,
  ARRAY['immigration','benefits','housing','employment'], ARRAY['refugees','immigrants'],
  FALSE, '1_week', FALSE,
  '615-341-1090', 'https://rescue.org/united-states/nashville-tn', 'https://rescue.org',
  'Refugees and immigrants in Nashville. Kurdish, Somali, Burmese, Spanish services.',
  'Free', ARRAY['English','Spanish','Kurdish','Somali','Burmese'],
  'https://rescue.org', '2026-04', 0, 0),

('tn-housing-thda', 'Tennessee Housing Development Agency (THDA)',
  'rental_assistance', 'state', 'TN', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '615-815-2200', 'https://thda.org', 'https://thda.org',
  'Low-income TN renters — Section 8/HCV, HOME, emergency rental assistance.',
  'Free', ARRAY['English','Spanish'],
  'https://thda.org', '2026-04', 0, 0),

-- ─── SOUTH CAROLINA ────────────────────────────────────────

('sc-snap', 'South Carolina SNAP / Food Assistance (DSS)',
  'food', 'state', 'SC', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '800-311-7220', 'https://benefitsweb.sc.gov', 'https://benefitsweb.sc.gov',
  'Income < 130% FPL — 46 county DSS offices. ABAWD active statewide.',
  'Free', ARRAY['English','Spanish'],
  'https://benefitsweb.sc.gov', '2026-04', 0, 0),

('sc-wic', 'WIC South Carolina',
  'food', 'state', 'SC', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  '800-868-0404', 'https://scdhec.gov/wic', 'https://scdhec.gov/wic',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL.',
  'Free', ARRAY['English','Spanish'],
  'https://scdhec.gov/wic', '2026-04', 0, 0),

('sc-harvest-hope', 'Harvest Hope Food Bank (Midlands / Statewide)',
  'food', 'nonprofit', 'SC', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '803-254-4432', 'https://harvesthope.org', 'https://harvesthope.org',
  'Midlands and statewide — 20-county service area including Columbia metro.',
  'Free', ARRAY['English','Spanish'],
  'https://harvesthope.org', '2026-04', 0, 0),

('sc-lowcountry-food-bank', 'Lowcountry Food Bank (Charleston / Coastal SC)',
  'food', 'nonprofit', 'SC', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '843-747-8146', 'https://lowcountryfoodbank.org', 'https://lowcountryfoodbank.org',
  '11-county coastal SC service area.',
  'Free', ARRAY['English','Spanish'],
  'https://lowcountryfoodbank.org', '2026-04', 0, 0),

('sc-medicaid', 'SC Medicaid / Healthy Connections (NOT Expanded)',
  'healthcare', 'state', 'SC', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['children','pregnant','disabled','seniors'],
  TRUE, '1_week', FALSE,
  '888-549-0820', 'https://benefitsweb.sc.gov', 'https://scdhhs.gov',
  'Children, pregnant women, parents < 67% FPL, elderly, disabled. NOT expanded. Categorical only.',
  'Free', ARRAY['English','Spanish'],
  'https://scdhhs.gov', '2026-04', 0, 0),

('sc-fqhc-scphca', 'SC Primary Health Care Association (FQHCs)',
  'healthcare', 'fqhc', 'SC', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '803-788-2589', 'https://scphca.org', 'https://scphca.org',
  'Anyone regardless of insurance — 20+ FQHCs statewide; sliding scale.',
  'Sliding scale', ARRAY['English','Spanish'],
  'https://scphca.org', '2026-04', 0, 0),

('sc-sea-island-health', 'Sea Island Comprehensive Health Care (Gullah Geechee FQHC)',
  'healthcare', 'fqhc', 'SC', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '843-522-0790', 'https://sichcc.com', 'https://sichcc.com',
  'Beaufort, Jasper, Hampton, Colleton counties — Gullah Geechee community; culturally competent care.',
  'Sliding scale', ARRAY['English','Gullah'],
  'https://sichcc.com', '2026-04', 0, 0),

('sc-legal-services', 'SC Legal Services (Statewide)',
  'legal_aid', 'legal_aid_org', 'SC', FALSE,
  ARRAY['any','eviction','housing','benefits','dv'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '888-346-5592', 'https://sclegal.org', 'https://sclegal.org',
  'Statewide — housing (eviction triage), family, benefits, DV, consumer, immigration.',
  'Free', ARRAY['English','Spanish'],
  'https://sclegal.org', '2026-04', 0, 0),

('sc-appleseed', 'SC Appleseed Legal Justice Center',
  'legal_aid', 'legal_aid_org', 'SC', FALSE,
  ARRAY['any','housing','benefits','immigration'], ARRAY['low_income','immigrants','farmworkers'],
  TRUE, '1_week', FALSE,
  '803-779-1113', 'https://scjustice.org', 'https://scjustice.org',
  'Statewide — heirs property, immigration, consumer, benefits. Key for Gullah Geechee heirs property.',
  'Free', ARRAY['English','Spanish'],
  'https://scjustice.org', '2026-04', 0, 0),

('sc-housing', 'SC State Housing Finance and Development Authority',
  'rental_assistance', 'state', 'SC', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '803-896-9001', 'https://schousing.com', 'https://schousing.com',
  'Low-income SC renters — Section 8/HCV, HOME, emergency rental assistance.',
  'Free', ARRAY['English','Spanish'],
  'https://schousing.com', '2026-04', 0, 0);

