
-- ============================================================
-- MIGRATION 012: Mississippi, Louisiana, Connecticut programs
-- ============================================================

INSERT INTO programs (
  program_key, name, resource_type, provider_type,
  state_code, is_national, situation_tags, population_tags,
  income_threshold, turnaround, is_emergency,
  phone, application_url, website,
  eligibility, cost, languages,
  source_url, last_verified, created_at, updated_at
) VALUES

-- ─── MISSISSIPPI ───────────────────────────────────────────

('ms-snap', 'Mississippi SNAP / Food Assistance (MDHS)',
  'food', 'state', 'MS', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '601-359-4500', 'https://mdhs.ms.gov', 'https://mdhs.ms.gov',
  'Income < 130% FPL — county DFCS offices statewide. ABAWD active.',
  'Free', ARRAY['English','Spanish'],
  'https://mdhs.ms.gov', '2026-04', 0, 0),

('ms-wic', 'WIC Mississippi',
  'food', 'state', 'MS', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  '601-576-7462', 'https://msdh.ms.gov/wic', 'https://msdh.ms.gov/wic',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL.',
  'Free', ARRAY['English','Spanish'],
  'https://msdh.ms.gov/wic', '2026-04', 0, 0),

('ms-delta-health-center', 'Delta Health Center (Delta FQHC — Oldest Rural FQHC in US)',
  'healthcare', 'fqhc', 'MS', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '662-741-2151', 'https://deltahealthcenter.org', 'https://deltahealthcenter.org',
  'Bolivar, Sunflower, and surrounding Delta counties — oldest rural FQHC in the US, est. 1965. No insurance required.',
  'Sliding scale', ARRAY['English'],
  'https://deltahealthcenter.org', '2026-04', 0, 0),

('ms-food-network', 'Mississippi Food Network (Statewide)',
  'food', 'nonprofit', 'MS', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '601-353-7286', 'https://msfoodnet.org', 'https://msfoodnet.org',
  'Jackson metro and statewide SNAP enrollment assistance.',
  'Free', ARRAY['English'],
  'https://msfoodnet.org', '2026-04', 0, 0),

('ms-medicaid', 'Mississippi Medicaid (NOT Expanded — Most Restrictive in Registry)',
  'healthcare', 'state', 'MS', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['children','pregnant','disabled','seniors'],
  TRUE, '1_week', FALSE,
  '800-421-2408', 'https://medicaid.ms.gov', 'https://medicaid.ms.gov',
  'Children, pregnant women, parents < 29% FPL, elderly, disabled. NOT expanded. Most restrictive categorical thresholds in registry.',
  'Free', ARRAY['English'],
  'https://medicaid.ms.gov', '2026-04', 0, 0),

('ms-fqhc-mphca', 'Mississippi Primary Health Care Association (FQHCs)',
  'healthcare', 'fqhc', 'MS', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','all'],
  TRUE, '1_week', FALSE,
  '601-353-0552', 'https://mphca.com', 'https://mphca.com',
  'Anyone regardless of insurance — 15+ FQHCs statewide; sliding scale. Key: Delta Health Center, Voice of Calvary, Coastal Family Health.',
  'Sliding scale', ARRAY['English','Spanish'],
  'https://mphca.com', '2026-04', 0, 0),

('ms-center-for-justice', 'Mississippi Center for Justice (MCJ)',
  'legal_aid', 'legal_aid_org', 'MS', FALSE,
  ARRAY['any','eviction','housing','benefits','civil_rights'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '601-352-2269', 'https://mscenterforjustice.org', 'https://mscenterforjustice.org',
  'Statewide — civil rights, housing, consumer, benefits, Delta outreach. Essential for Delta and Jackson clients.',
  'Free', ARRAY['English'],
  'https://mscenterforjustice.org', '2026-04', 0, 0),

('ms-coast-legal', 'Coast Legal Services (Gulf Coast)',
  'legal_aid', 'legal_aid_org', 'MS', FALSE,
  ARRAY['any','eviction','housing','benefits','dv'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '228-374-4656', 'https://coastlegal.org', 'https://coastlegal.org',
  'Harrison, Hancock, Jackson, Stone counties — housing, family, benefits, DV.',
  'Free', ARRAY['English','Spanish'],
  'https://coastlegal.org', '2026-04', 0, 0),

('ms-housing-mhc', 'Mississippi Home Corporation (MHC)',
  'rental_assistance', 'state', 'MS', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '601-718-4636', 'https://mshomecorp.com', 'https://mshomecorp.com',
  'Low-income MS renters — Section 8/HCV, HOME, emergency rental assistance.',
  'Free', ARRAY['English'],
  'https://mshomecorp.com', '2026-04', 0, 0),

-- ─── LOUISIANA ─────────────────────────────────────────────

('la-snap', 'Louisiana SNAP (DCFS)',
  'food', 'state', 'LA', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '888-524-3578', 'https://benefitsnow.la.gov', 'https://dcfs.louisiana.gov',
  'Income < 130% FPL — 64 parish offices. Apply online at benefitsnow.la.gov.',
  'Free', ARRAY['English','Spanish','French'],
  'https://dcfs.louisiana.gov', '2026-04', 0, 0),

('la-wic', 'WIC Louisiana',
  'food', 'state', 'LA', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  NULL, 'https://ldh.la.gov/wic', 'https://ldh.la.gov/wic',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL.',
  'Free', ARRAY['English','Spanish','French'],
  'https://ldh.la.gov/wic', '2026-04', 0, 0),

('la-second-harvest', 'Second Harvest Food Bank (New Orleans / South LA)',
  'food', 'nonprofit', 'LA', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '504-734-1322', 'https://no-hunger.org', 'https://no-hunger.org',
  'South Louisiana — primary food bank for New Orleans and Gulf Coast.',
  'Free', ARRAY['English','Spanish','French'],
  'https://no-hunger.org', '2026-04', 0, 0),

('la-medicaid-healthy', 'Healthy Louisiana / Louisiana Medicaid (Expanded 2016)',
  'healthcare', 'state', 'LA', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '888-342-6207', 'https://benefitsnow.la.gov', 'https://ldh.la.gov/medicaid',
  'Adults 19–64 to 138% FPL (expanded July 2016). Managed care — verify plan enrollment.',
  'Free', ARRAY['English','Spanish','French'],
  'https://ldh.la.gov/medicaid', '2026-04', 0, 0),

('la-legal-services-slls', 'Southeast Louisiana Legal Services (SLLS — New Orleans)',
  'legal_aid', 'legal_aid_org', 'LA', FALSE,
  ARRAY['any','eviction','housing','benefits','dv','immigration'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '504-529-1000', 'https://slls.org', 'https://slls.org',
  'Southeast Louisiana — housing (post-Katrina displacement), family, benefits, DV, consumer. Baton Rouge: 225-448-0063.',
  'Free', ARRAY['English','Spanish','French'],
  'https://slls.org', '2026-04', 0, 0),

('la-legal-services-acadiana', 'Acadiana Legal Service Corp (Southwest / South LA)',
  'legal_aid', 'legal_aid_org', 'LA', FALSE,
  ARRAY['any','eviction','housing','benefits','dv'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '337-237-4320', 'https://alsc.org', 'https://alsc.org',
  'Southwest Louisiana — Lafayette, Lake Charles area. Housing, family, benefits, DV, consumer.',
  'Free', ARRAY['English','Spanish','French'],
  'https://alsc.org', '2026-04', 0, 0),

('la-liheap', 'Louisiana LIHEAP (DCFS)',
  'utility_assistance', 'federal', 'LA', FALSE,
  ARRAY['utility_assistance','benefits','any'], ARRAY['low_income','seniors','families'],
  TRUE, '1_week', FALSE,
  '888-524-3578', 'https://dcfs.louisiana.gov/liheap', 'https://dcfs.louisiana.gov',
  'Income < 60% state median — heating, cooling, crisis shutoff prevention.',
  'Free', ARRAY['English','Spanish','French'],
  'https://dcfs.louisiana.gov', '2026-04', 0, 0),

('la-housing-lhc', 'Louisiana Housing Corporation',
  'rental_assistance', 'state', 'LA', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '225-763-8700', 'https://lhc.la.gov', 'https://lhc.la.gov',
  'Low-income LA renters — Section 8/HCV, HOME, emergency rental assistance.',
  'Free', ARRAY['English','Spanish','French'],
  'https://lhc.la.gov', '2026-04', 0, 0),

-- ─── CONNECTICUT ───────────────────────────────────────────

('ct-snap', 'Connecticut SNAP / Supplemental Nutrition (DSS)',
  'food', 'state', 'CT', FALSE,
  ARRAY['food','benefits','any'], ARRAY['low_income','families','all'],
  TRUE, '1_week', FALSE,
  '855-626-6632', 'https://connect.ct.gov', 'https://ct.gov/dss/snap',
  'Income < 130% FPL — 12 DSS offices statewide. Apply online at ConneCT.',
  'Free', ARRAY['English','Spanish','Portuguese','Haitian Creole'],
  'https://ct.gov/dss', '2026-04', 0, 0),

('ct-wic', 'WIC Connecticut',
  'food', 'state', 'CT', FALSE,
  ARRAY['food','healthcare'], ARRAY['pregnant','infants','children','low_income'],
  TRUE, '1_week', FALSE,
  '860-509-8084', 'https://portal.ct.gov/dph/wic', 'https://portal.ct.gov/dph/wic',
  'Pregnant, postpartum women, infants, children under 5 — income < 185% FPL.',
  'Free', ARRAY['English','Spanish','Portuguese'],
  'https://portal.ct.gov/dph/wic', '2026-04', 0, 0),

('ct-food-bank', 'Connecticut Food Bank (Statewide)',
  'food', 'nonprofit', 'CT', FALSE,
  ARRAY['food','any'], ARRAY['all'],
  FALSE, 'same_day', TRUE,
  '203-469-5000', 'https://ctfoodbank.org', 'https://ctfoodbank.org',
  'Statewide — primary CT food bank network. Also Foodshare (Hartford: 860-286-9999).',
  'Free', ARRAY['English','Spanish','Portuguese'],
  'https://ctfoodbank.org', '2026-04', 0, 0),

('ct-husky-health', 'HUSKY Health / Connecticut Medicaid (DSS — Expanded 2014)',
  'healthcare', 'state', 'CT', FALSE,
  ARRAY['healthcare','benefits'], ARRAY['low_income','families','immigrants','all'],
  TRUE, '1_week', FALSE,
  '877-284-8759', 'https://connect.ct.gov', 'https://huskyhealthct.org',
  'Adults 19–64 to 138% FPL (expanded 2014). HUSKY D for undocumented children (state-funded). Verify managed care plan.',
  'Free', ARRAY['English','Spanish','Portuguese','Haitian Creole'],
  'https://huskyhealthct.org', '2026-04', 0, 0),

('ct-fqhc-ctchc', 'CT Community Health Centers (FQHCs)',
  'healthcare', 'fqhc', 'CT', FALSE,
  ARRAY['healthcare','any'], ARRAY['uninsured','low_income','immigrants','all'],
  TRUE, '1_week', FALSE,
  '860-246-0090', 'https://ctchc.com', 'https://ctchc.com',
  'Anyone regardless of insurance — 15+ FQHCs statewide; sliding scale. Key: Charter Oak (Hartford), Fair Haven (New Haven), Optimus (Bridgeport).',
  'Sliding scale', ARRAY['English','Spanish','Portuguese','Haitian Creole'],
  'https://ctchc.com', '2026-04', 0, 0),

('ct-legal-services', 'Connecticut Legal Services (CLS — Statewide)',
  'legal_aid', 'legal_aid_org', 'CT', FALSE,
  ARRAY['any','eviction','housing','benefits','dv','immigration'], ARRAY['low_income','immigrants','all'],
  TRUE, '1_week', FALSE,
  '860-456-1761', 'https://ctlegal.org', 'https://ctlegal.org',
  'Statewide — housing, family, benefits, DV, consumer, immigration. Hartford, New Haven, Bridgeport, Danbury offices.',
  'Free', ARRAY['English','Spanish','Portuguese'],
  'https://ctlegal.org', '2026-04', 0, 0),

('ct-make-the-road', 'Make the Road Connecticut (Danbury — Immigrant Services)',
  'immigration', 'nonprofit', 'CT', FALSE,
  ARRAY['immigration','benefits','housing','employment','any'], ARRAY['immigrants','latinos'],
  FALSE, 'same_day', TRUE,
  '203-553-4340', NULL, 'https://maketheroadct.org',
  'Danbury area — dense Central American immigrant community. Immigration crisis response.',
  'Free', ARRAY['English','Spanish','Portuguese'],
  'https://maketheroadct.org', '2026-04', 0, 0),

('ct-housing-chfa', 'Connecticut Housing Finance Authority (CHFA)',
  'rental_assistance', 'state', 'CT', FALSE,
  ARRAY['eviction','housing','rental_assistance'], ARRAY['low_income','all'],
  TRUE, '1_week', FALSE,
  '860-571-3500', 'https://chfa.org', 'https://chfa.org',
  'Low-income CT renters — Section 8/HCV, HOME, emergency rental assistance.',
  'Free', ARRAY['English','Spanish'],
  'https://chfa.org', '2026-04', 0, 0),

('ct-tanf', 'Connecticut TFA (Temporary Family Assistance / TANF)',
  'emergency_cash', 'state', 'CT', FALSE,
  ARRAY['benefits','any'], ARRAY['low_income','families','children'],
  TRUE, '1_week', FALSE,
  '855-626-6632', 'https://connect.ct.gov', 'https://ct.gov/dss',
  'Families with children — up to $693/month for family of 3. 21-month state limit. Safety Net program after state TFA exhausted.',
  'Free', ARRAY['English','Spanish'],
  'https://ct.gov/dss', '2026-04', 0, 0);
