-- Restore the ingest run ledger that predates its first checked-in sequence
-- repair. Production already has this exact nullable legacy/current contract.

do $block$
begin
  if to_regtype('public.ingest_runs_ingest_status_enum') is null then
    create type public.ingest_runs_ingest_status_enum as enum (
      'running',
      'completed',
      'failed',
      'cancelled',
      'api_unavailable',
      'partial'
    );
  end if;
end
$block$;

create table if not exists public.ingest_runs (
  id integer generated by default as identity primary key,
  run_id text,
  stream_id text,
  started_at bigint,
  completed_at bigint,
  records_processed integer,
  records_failed integer,
  status text,
  error_message text,
  created_at bigint,
  dataset_id_run text,
  start_time bigint,
  end_time bigint,
  records_inserted integer,
  records_updated integer,
  signals_generated integer,
  ingest_status public.ingest_runs_ingest_status_enum,
  errors_run text,
  summary_run text,
  error_classification_run text,
  http_status_run integer,
  content_type_run text,
  endpoint_attempted_run text,
  adapter_used_run text,
  body_preview_run text,
  parse_failure_reason_run text,
  retry_count_run integer,
  failure_classification_run text,
  suggested_remediation_run text,
  signals_processed_run boolean,
  post_processing_engine_run text,
  outcome_classification_run text
);

alter table public.ingest_runs enable row level security;

create policy authenticated_all_access_ingest_runs
  on public.ingest_runs for select to authenticated using (true);
create policy service_role_all_ingest_runs_21b7fe3c
  on public.ingest_runs for all to service_role using (true) with check (true);

revoke all on table public.ingest_runs from public, anon, authenticated;
grant select on table public.ingest_runs to authenticated;
grant all on table public.ingest_runs to service_role;

revoke all on sequence public.ingest_runs_id_seq
  from public, anon, authenticated;
grant usage, select on sequence public.ingest_runs_id_seq to service_role;
