
INSERT INTO engine_warnings (
  warning_code, severity, description, fix,
  affected_engines, resolved, created_at
) VALUES

('WARNING-01', 'critical',
  'Gate 2.5 missing. Three enqueueDocument() calls in routers.ts (~lines 180, 201, 267) do not propagate snapshotId. Audit trail shows snapshotId=0 for these entries.',
  '3-line fix: pass snapshotId to each of the three enqueueDocument() calls in routers.ts.',
  ARRAY['upload-route','analysis-pipeline','gate-helpers / gate-schema'],
  FALSE, 0),

('WARNING-02', 'medium',
  'Risk Zone A: export-streaming.ts line 331 falls back to getLatestSnapshot when no explicit snapshotId passed.',
  'Enforce explicit snapshotId in export route.',
  ARRAY['export-streaming'],
  FALSE, 0),

('WARNING-03', 'medium',
  'Risk Zone B: provenance drill-down resolves snapshot via listSnapshots[0] (implicit binding).',
  'Add explicit snapshotId field to findings table.',
  ARRAY['gate-helpers / gate-schema'],
  FALSE, 0),

('WARNING-04', 'low',
  'Risk Zone C: retryFailedOnly resolves via getOpenSnapshot but asymmetric with other paths.',
  'Collapse to single snapshot resolution pattern.',
  ARRAY['gate-helpers / gate-schema'],
  FALSE, 0),

('WARNING-05', 'high',
  '25 of 31 engines have status unknown — not confirmed wired to routers or registered in engineRegistry.',
  'Full audit per unknown engine: file exists, table usage, withEngineTracking() wrapping, engineRegistry registration.',
  ARRAY['system-copilot-sunam','admin-sovereign-control','export-spine-engine','restore-spine-engine','entity-intelligence','entity-evidence-threshold','entity-transparency','litigation-correlation-service','problem-interpreter-service','evidence-dossier','investigative-query-engine','systemic-intelligence-map','institutional-accountability','regulatory-capture','crisis-prediction','harm-index-service','harm-map-service','risk-forecast-service','systemic-risk-forecast','systemic-simulation','attorney-match-service','case-link-service','intervention-timeline-engine','time-travel-engine','public-alerting','public-transparency','external-collaboration','executor-service'],
  FALSE, 0),

('WARNING-06', 'medium',
  'No-op guard missing in governance layer. Repeat suppression of already-suppressed signal is logged without rejection.',
  'Add no-op guard: if signal already in target state, reject rather than log a no-op.',
  ARRAY['Governance Layer'],
  FALSE, 0),

('WARNING-07', 'high',
  'AKB coverage Washington State only. All other state FOIA lookup paths return no-match.',
  'Expand AKB state by state using state registry files already seeded.',
  ARRAY['akb-lookup','foia-generator','gap-detection'],
  FALSE, 0);

-- Canonical Drizzle schema table registry
INSERT INTO schema_table_registry (table_name, table_group, confirmed, notes) VALUES
('cases', 'core', TRUE, NULL),
('documents', 'core', TRUE, NULL),
('entities', 'core', TRUE, 'Confirmed name — not extracted_entities'),
('quotes', 'core', TRUE, 'Confirmed name — not document_quotes'),
('events', 'core', TRUE, 'Confirmed name — not extracted_events'),
('claims', 'core', TRUE, NULL),
('relationships', 'core', TRUE, NULL),
('signal_flags', 'core', TRUE, NULL),
('findings', 'core', TRUE, NULL),
('document_correlations', 'core', TRUE, NULL),
('missing_records', 'core', TRUE, NULL),
('foia_requests', 'core', TRUE, NULL),
('pattern_signatures', 'core', TRUE, NULL),
('pattern_occurrences', 'core', TRUE, NULL),
('narratives', 'core', TRUE, NULL),
('corpus_snapshots', 'core', TRUE, NULL),
('pipeline_events', 'core', TRUE, NULL),
('audit_trail', 'core', TRUE, NULL),
('notifications', 'core', TRUE, NULL),
('collaborators', 'core', TRUE, NULL),
('share_links', 'core', TRUE, NULL),
('presentations', 'core', TRUE, NULL),
('action_paths', 'core', TRUE, NULL),
('users', 'core', TRUE, NULL),
('user_preferences', 'core', TRUE, NULL),
('feedback', 'core', TRUE, NULL),
('analytics_events', 'core', TRUE, NULL),
('test_scenarios', 'core', TRUE, NULL),
('templates', 'core', TRUE, NULL),
('governance_log', 'core', TRUE, NULL),
('data_streams', 'core', TRUE, NULL),
('sunam_thresholds', 'core', TRUE, NULL),
('signals', 'core', TRUE, NULL),
('engine_registry', 'core', TRUE, 'Original stub — renamed engine_registry_original_stub in new schema'),
('cda_runs', 'cda', TRUE, NULL),
('cda_documents', 'cda', TRUE, NULL),
('cda_quotes', 'cda', TRUE, NULL),
('cda_denial_reasons', 'cda', TRUE, NULL),
('cda_policy_clauses', 'cda', TRUE, NULL),
('cda_claim_ledger', 'cda', TRUE, NULL),
('cda_comparison_matrix', 'cda', TRUE, NULL),
('cda_contradictions', 'cda', TRUE, NULL),
('cda_evidence_gaps', 'cda', TRUE, NULL),
('programs', 'luminari_new', TRUE, 'Promise keeper — fires at intake'),
('tribal_jurisdictions', 'luminari_new', TRUE, '39 sovereign nations seeded'),
('knowledge_documents', 'luminari_new', TRUE, 'Vector backbone'),
('knowledge_upload_sessions', 'luminari_new', TRUE, NULL),
('engine_registry_v3', 'luminari_new', TRUE, 'Canonical engine map'),
('engine_warnings', 'luminari_new', TRUE, 'Integrity warnings'),
('schema_table_registry', 'luminari_new', TRUE, 'Canonical schema map'),
('gap_log', 'luminari_new', TRUE, NULL),
('interpretation_trace_log', 'luminari_new', TRUE, NULL);

