begin;
insert into public.domain_deep_dive_v3_13_stage (source_file, source_hash_raw, source_kind, source_key, table_idx, row_idx, payload) values
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 0, '{"statute___law": "Americans with Disabilities Act (ADA) -- All Titles", "citation": "42 U.S.C. sec. 12101 et seq.", "key_language___note": "Title I (employment, 15+ employees), Title II (state and local government), Title III (public accommodations). Reasonable accommodation required. Interactive process required. No medical exams before conditional offer. | SOL: Title I: 300 days (deferral) / 180 days to EEOC | Title II/III: 180 days to DOJ | 2 years in federal court", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 1, '{"statute___law": "Section 504 -- Disability Rights in Federally Funded Programs", "citation": "29 U.S.C. sec. 794", "key_language___note": "No qualified individual with disability excluded from programs receiving federal financial assistance. Covers schools, hospitals, social services, transportation, and all federally funded programs. OCR complaint: 180 days from discriminatory act. | SOL: OCR complaint: 180 days from discriminatory act", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 2, '{"statute___law": "Rehabilitation Act -- Vocational Rehabilitation and Employment", "citation": "29 U.S.C. sec. 720 et seq.", "key_language___note": "State-federal VR programs providing employment services. Title VII: Independent Living Centers. Section 508: federal technology accessibility. Section 503: federal contractor disability employment requirements (7% utilization goal). | SOL: VR: not applicable | Section 503 complaint: OFCCP within 300 days", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 3, '{"statute___law": "IDEA -- Individuals with Disabilities Education Act", "citation": "20 U.S.C. sec. 1400 et seq.", "key_language___note": "Free appropriate public education (FAPE) in least restrictive environment (LRE) for children with disabilities ages 3-21. IEP required. Part C: early intervention birth through age 2. Part B: school age. Procedural safeguards: prior written notice, IEE, mediation, due process. | SOL: 2 years from knew or should have known of IDEA violation", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 4, '{"statute___law": "Fair Housing Act -- Disability Accommodation and Modification", "citation": "42 U.S.C. sec. 3604(f)", "key_language___note": "Prohibits housing discrimination against persons with disabilities. Requires reasonable accommodations in rules and services. Requires reasonable modifications to premises. New multifamily construction (4+ units post-1991) must meet accessibility design requirements. | SOL: 1 year to HUD FHEO | 2 years in federal court", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 5, '{"statute___law": "SSDI and SSI -- Federal Disability Benefits", "citation": "42 U.S.C. sec. 423 (SSDI) | 42 U.S.C. sec. 1382 (SSI)", "key_language___note": "SSDI: for workers with work history who become disabled (5-month wait, Medicare after 24 months). SSI: needs-based, no work history required. 5-step sequential evaluation. ABLE accounts protect SSI eligibility. Ticket to Work for employment exploration. | SOL: 60 days to appeal each adverse determination -- FATAL if missed", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 6, '{"statute___law": "Medicaid HCBS Waiver Authority -- Community Services", "citation": "42 U.S.C. sec. 1396n(c)", "key_language___note": "Allows states to provide community-based services instead of institutional care through Medicaid waivers. Olmstead (1999) requires states to provide community services when appropriate. Waiting lists common -- apply immediately. | SOL: Not applicable -- apply as soon as possible", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 7, '{"statute___law": "Olmstead v. L.C. -- Integration Mandate", "citation": "527 U.S. 581 (1999) | ADA Title II (42 U.S.C. sec. 12132)", "key_language___note": "Unjustified institutionalization of persons with disabilities is discrimination under ADA Title II. States must provide community-based services when: (1) appropriate; (2) not opposed by individual; (3) can be reasonably accommodated. File with DOJ (800-514-0301). | SOL: File DOJ complaint promptly", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 8, '{"statute___law": "Assistive Technology Act -- State AT Programs", "citation": "29 U.S.C. sec. 3001", "key_language___note": "Every state and territory must have an AT program. State programs provide: device demonstrations, device loans, device reuse/exchange, and financing. Find your state AT program at ataporg.org. | SOL: Not applicable", "official_source": "Source \u2197"}'::jsonb),
('luminari-DISABILITY-SERVICES-DEEP-DIVE-2026.docx', '5932ceaf', 'domain_deep_dive', 'disability-services', 25, 9, '{"statute___law": "Protection and Advocacy (P&A) Authority", "citation": "42 U.S.C. sec. 15043 | 42 U.S.C. sec. 10801 (PAIMI)", "key_language___note": "Every state and territory must have a federally designated P&A organization. P&A organizations have authority to investigate abuse/neglect in institutions, enforce disability rights laws, and provide legal advocacy. Find your P&A at ndrn.org/find-your-pa. | SOL: Varies by matter -- contact P&A promptly", "official_source": "Source \u2197"}'::jsonb)
on conflict (source_row_key) do nothing;
commit;
