
-- ============================================================
-- MIGRATION 035: Filing Templates + Coalition Intelligence
-- From inline JSON in this session
-- ============================================================

-- Filing templates (the actual document generation templates)
INSERT INTO filing_templates_registry (
  template_id, claim_type, statutory_authority, jurisdiction_scope,
  form_required, document_structure, filing_instructions, supporting_docs, jurisdiction_variations
) VALUES

('template_ssdi_001','SSDI Appeal to Administrative Law Judge (ALJ)','42 USC § 405(b); 20 CFR § 404.900 et seq','Federal (SSA); all states','Form SSA-561 (Request for Hearing Before Administrative Law Judge)',
'{"sections":{"section_1":{"title":"Case Information","required_elements":["Claimant name","Social Security number","Claim type","Date of initial denial","Date of reconsideration denial","ALJ request date"]},"section_2":{"title":"Medical Evidence Summary","required_elements":["Diagnoses","Onset date of impairment","Treatment history","Medical test results","Functional limitations","Prognosis"]},"section_3":{"title":"Work History","required_elements":["Employment history (last 15 years)","Dates of work","Job duties","Reason for job loss"]},"section_4":{"title":"Argument","required_elements":["Rebuttal of SSA denial reasons","Evidence showing impairment meets Social Security listing","Explanation of how impairment prevents substantial gainful activity"]}}}'::jsonb,
'{"deadline":"60 days from receipt of reconsideration denial (strict deadline)","agency":"Social Security Administration (regional SSA office or online at ssa.gov)","form_of_delivery":"Mail or online submission"}'::jsonb,
ARRAY['Medical records (last 12 months treatment records)','Functional capacity evaluation (if available)','Physician statement regarding work capacity','Employment records','Birth certificate (if not on file with SSA)'],
'{"note":"SSDI is federal program; no state-level variation"}'::jsonb),

('template_wage_theft_001','DOL Wage & Hour Complaint (Federal)','29 USC § 211 (Fair Labor Standards Act); 29 CFR § 516','Federal (Department of Labor); all states','No government form required; structured complaint letter',
'{"sections":{"section_1":{"title":"Complainant Information","required_elements":["Name","Address","Phone","Email","Social Security number"]},"section_2":{"title":"Employer Information","required_elements":["Employer name","Business address","Phone","Number of employees","Type of business"]},"section_3":{"title":"Employment Relationship","required_elements":["Job title","Date employment began","Date employment ended","Supervisor name","Payment method"]},"section_4":{"title":"Wage Violation Details","required_elements":["Hours worked per day/week","Wages paid per week","Minimum wage rate applicable","Overtime rate applicable","Description of violation","Dates of violation"]},"section_5":{"title":"Calculation of Unpaid Wages","required_elements":["Total hours worked","Minimum wage owed (hours × applicable rate)","Less: wages actually paid","Equals: unpaid wages owed"]},"section_6":{"title":"Evidence & Documentation","required_elements":["List of evidence attached","Witness names","Explanation of how claimant tracked hours"]}}}'::jsonb,
'{"deadline":"No statutory deadline (3-year FLSA statute of limitations applies)","agency":"U.S. Department of Labor, Wage and Hour Division (find office at dol.gov/whd)","form_of_delivery":"Mail, phone intake (toll-free 1-866-4-USDOL), or online form"}'::jsonb,
ARRAY['Pay stubs (all, showing hours worked + wages paid)','Timesheets (if available; even informal/handwritten acceptable)','Employment agreement or offer letter','Tax documents showing employment (W-2, 1099)','Email communications about work/pay','Photographs of work location/performed work','Coworker statement (if willing)'],
'{"note":"Federal FLSA complaint is uniform nationwide. For stronger recovery in certain states (CA, NY, IL), simultaneous state labor board complaint recommended."}'::jsonb),

('template_employment_discrimination_001','EEOC Charge of Discrimination (Title VII)','42 USC § 2000e-5 (Title VII); 29 CFR § 1601.9','Federal (EEOC); all states (dual-filing available in certain states)','Form EEOC-5 (Charge of Discrimination)',
'{"sections":{"section_1":{"title":"Charging Party Information","required_elements":["Name","Address","Phone","Email"]},"section_2":{"title":"Respondent (Employer) Information","required_elements":["Employer name","Business address","Telephone","Type of business"]},"section_3":{"title":"Basis of Discrimination","required_elements":["Protected class status","Date discrimination began","Date discrimination ended","Is discrimination continuing?"]},"section_4":{"title":"Description of Alleged Discriminatory Conduct","required_elements":["Clear narrative describing adverse action","Names of individuals involved","Dates of each incident","Any prior complaints to employer","Related complaints filed elsewhere"]}}}'::jsonb,
'{"deadline":"180 days from discrimination date (or 300 days if filed in dual-filing state with state agency first)","agency":"EEOC (federal); dual-filing with state agency in dual-filing states","form_of_delivery":"Mail or in-person at EEOC field office","note":"Charge can be filed online (eefile.eeoc.gov) or by mail"}'::jsonb,
ARRAY['Evidence of discrimination: pay records, performance reviews, termination letter, email communications, witnesses','Comparative evidence: similarly situated employee of different protected class treated more favorably','Timeline of events (with dates)','Internal complaint documentation (if filed with employer)'],
'{"dual_filing_states":"CA, NY, IL, TX, FL, PA — EEOC charge filed with state agency simultaneously","note":"Dual-filing extends deadline to 300 days in those states"}'::jsonb),

('template_housing_discrimination_001','HUD Fair Housing Complaint','42 USC § 3601 et seq (Fair Housing Act); 42 CFR § 100.300 et seq','Federal (HUD); all states (dual-filing with state FHA available)','Form HUD-903.1 (Complaint of Housing Discrimination)',
'{"sections":{"section_1":{"title":"Complainant Information","required_elements":["Name","Address","Phone","Email"]},"section_2":{"title":"Respondent (Landlord/Agent) Information","required_elements":["Landlord/agent name","Property address","Phone"]},"section_3":{"title":"Protected Class Basis","required_elements":["Protected class: race, color, national origin, religion, sex, familial status, disability","Date discrimination occurred"]},"section_4":{"title":"Description of Alleged Discrimination","required_elements":["Type of discrimination","Specific facts (what was said/done, by whom, on what date)","Names of witnesses","How discrimination was based on protected class"]},"section_5":{"title":"Evidence of Comparative Treatment","required_elements":["How similarly situated person of different protected class was treated more favorably","Housing was available to others with similar qualifications"]}}}'::jsonb,
'{"deadline":"1 year from discrimination date (42 USC § 3614)","agency":"HUD Office of Fair Housing and Equal Opportunity (FHEO)","form_of_delivery":"Online (via FHEO online complaint portal) or mail to HUD FHEO office"}'::jsonb,
ARRAY['Listing showing property was available (Zillow, Craigslist screenshot with dates)','Communications with landlord (email, text messages, letters showing rejection)','Evidence of protected class status','Evidence of comparative treatment','Witness statements'],
'{"note":"Dual-filing with state FHA agency available in many states"}'::jsonb),

('template_foia_001','FOIA Request (Freedom of Information Act)','5 USC § 552 (Freedom of Information Act); 29 CFR § 70','Federal agencies; all 15 departments + 69 independent agencies','No government form; structured request letter',
'{"sections":{"header":{"elements":["Date","To: [Agency FOIA Officer], [Agency Name], [Address]"]},"opening":"Pursuant to the Freedom of Information Act, 5 USC § 552, I request the following records...","section_1":{"title":"Requester Information","required_elements":["Name","Address","Phone","Email","Whether commercial/media/academic requester"]},"section_2":{"title":"Records Requested (Detailed Description)","required_elements":["Specific description of records","Time period","Keywords/search terms","Specific documents if known"]},"section_3":{"title":"FOIA Exemptions Waiver","required_elements":["Statement waiving fees / requesting fee waiver due to public interest"]},"section_4":{"title":"Request for Expedited Processing (if applicable)","required_elements":["If urgent: explanation why expedited processing needed","Supporting facts for expedited claim"]}},"closing":"I request a response within the statutory 20-day deadline. If you determine any records are exempt, please provide a detailed withholding justification. I reserve the right to appeal any partial denial or failure to respond."}'::jsonb,
'{"deadline":"No statutory deadline to file; agency deadline 20 days from receipt (can be extended 10 days)","agency":"[Federal Agency] FOIA Officer (find via agency website or foia.gov)","form_of_delivery":"Mail, email (preferred), or online FOIA portal","follow_up":{"if_no_response_after_20_days":"Send follow-up demand letter; file administrative appeal if partial denial","if_denied":"File administrative appeal with agency (separate office); cite exemption claimed","if_appeal_denied":"File federal court action (5 USC § 552(a)(4)(B) — judicial review available)"}}'::jsonb,
ARRAY['Agency FOIA regulations (available on agency website)'],
NULL);

-- Reform legislators (key coalition intelligence)
INSERT INTO reform_legislators (legislator_id, name, party, state, chamber, committees, jurisdiction_focus, recent_bills, advocacy_stance, contact_office, reform_leverage) VALUES
('leg_001','Virginia Foxx','R','NC','House',ARRAY['House Education and Workforce Committee (Chair)'],'Employment, wage law, OSHA, worker protections',ARRAY['Legislation limiting OSHA enforcement'],'Business-friendly; skeptical of labor regulations','House.gov/representatives/foxx','NEGATIVE - Unlikely supporter of wage theft protections. Coalition: Build pressure through constituent labor unions + business groups supporting wage law.'),
('leg_002','Patty Murray','D','WA','Senate',ARRAY['HELP Committee (Ranking Member)','Appropriations Committee'],'Benefits, employment, healthcare, labor',ARRAY['Bill strengthening wage theft enforcement','Healthcare access expansion'],'Strong labor + benefits advocate','Murray.senate.gov','POSITIVE - Strong potential sponsor for wage theft + benefits reform packages. Coalition: Work with HELP Committee staff.'),
('leg_003','Jim Jordan','R','OH','House',ARRAY['House Judiciary Committee (Ranking Member)'],'Civil rights, constitutional law, regulatory oversight',ARRAY['Legislation limiting agency enforcement authority'],'Anti-regulation; skeptical of federal agency power','House.gov/representatives/jordan','MIXED - Could be ally on regulatory accountability issues (agency misconduct, FOIA enforcement). Frame as government accountability, not labor advocacy.'),
('leg_004','Adam Schiff','D','CA','House',ARRAY['House Judiciary Committee','House Intelligence Committee'],'Civil rights, governmental oversight, investigations',ARRAY['Civil rights enforcement bills'],'Strong civil rights, government accountability focus','House.gov/representatives/schiff','POSITIVE - Potential sponsor for civil rights + oversight reform. Coalition: Coordinate with civil rights orgs.'),
('leg_005','Bernie Sanders','I','VT','Senate',ARRAY['HELP Committee','Budget Committee'],'Labor, benefits, healthcare, economic justice',ARRAY['Wage theft prevention act','Medicare for All proposals','Worker protection bills'],'Labor + benefits champion; strong enforcement advocate','sanders.senate.gov','POSITIVE - Strongest Senate ally for wage + benefits reform. Coalition: Primary target for high-impact bills.');

-- Active reform campaigns
INSERT INTO reform_campaigns (campaign_id, campaign_name, status_stage, primary_sponsor, coalition_leads, demand, legislative_vehicle, target_passage, stage_timeline, supporting_evidence) VALUES
('campaign_001','Wage Theft Prevention Act 2026','Legislative Draft','Senator Bernie Sanders (VT-D)',ARRAY['AFL-CIO','NELP','Legal Aid programs'],'Mandatory liquidated damages (8 hours) + minimum $100/day penalties + attorney fees for all wage theft cases','Amendment to FLSA (29 USC § 216)','End of 2026 or 2027 session','{"current_stage":"Legislative Draft (in progress with committee staff)","next_milestone":"Introduce bill + secure 20+ co-sponsors","advocacy_action":"Coalition testimony at HELP Committee hearings; constituent meetings with key members","pressure_campaigns":["Labor unions activating membership","Legal aid case examples for media"]}'::jsonb,ARRAY['NELP data: wage theft affects 2M+ workers annually','Luminari pattern: same employers repeat violations 3-5x due to low penalties','California model: CA liquidated damages mandate increased recovery 4x']),
('campaign_002','Qualified Immunity Limitation Act','Coalition Building','Rep. Adam Schiff (CA-D), Rep. Barbara Lee (CA-D)',ARRAY['ACLU','NAACP','police accountability orgs'],'Raise ''clearly established'' bar for immunity; shift burden to officers to show good faith; allow damages for negligent violations','Amendment to 42 USC § 1983','2027-2028 session (longer-term campaign)','{"current_stage":"Coalition Building (coordinating civil rights orgs + state-level allies)","next_milestone":"Secure 50+ House co-sponsors; introduce bill next session","advocacy_action":"Media campaign on wrongful conviction + police misconduct cases; state-level qualified immunity limits as model"}'::jsonb,ARRAY['Luminari analysis: 70% of police accountability cases currently dismissed on qualified immunity grounds','Model: Colorado + New York state-level qualified immunity limits (passed 2022-2023)']);

-- Key media outlets for reform pipeline
INSERT INTO reform_media_outlets (outlet_id, outlet_name, outlet_type, coverage, audience, contact, partnership_potential) VALUES
('media_001','ProPublica','Investigative journalism nonprofit','Deep investigations into government + institutional misconduct, inequality, access to justice','500K+ monthly readers; high influence among policymakers + foundations','publiceditor@propublica.org','HIGH - Strong platform for systemic pattern investigations; receptive to civil rights + labor stories'),
('media_002','The Atlantic','National magazine + website','Civil rights, labor, inequality, policy analysis','2M+ monthly readers; educated, policy-interested demographic','pitches@theatlantic.com','HIGH - Reaches policy + educated audience; strong track record on justice + inequality'),
('media_003','Vox','News site + video platform','Policy + inequality explainers, breaking news on social policy','10M+ monthly; younger, digital-native audience','pitches@vox.com','HIGH - Explainer format reaches broad audience; strong explainers on policy gaps'),
('media_004','NPR (National Public Radio)','National broadcast + digital','Labor, civil rights, policy stories','25M+ monthly; wide demographic reach; trusted news brand','pitch@npr.org','MEDIUM-HIGH - Broad reach; editorial standards favor evidence-based stories'),
('media_005','APM Reports (American Public Media)','Radio/podcast investigations','Deep dives on systemic issues, inequality, workplace','2M+ listeners; engaged, policy-interested',NULL,'HIGH - Audio platform effective for narrative investigative pieces');
