-- Restore the queue contract that predates the checked-in secure worker RPCs.
-- This migration is repository-only because production already has this exact
-- table shape. Fresh and preview databases need it before the RPC migrations
-- can compile.

create table if not exists public.coordinate_enrichment_queue_v1 (
  id bigint generated by default as identity primary key,
  entity_domain text not null,
  entity_id text not null,
  entity_name text,
  resource_type text,
  jurisdiction text,
  address_text text,
  city text,
  state text,
  postal_code text,
  country text,
  source_view text not null,
  queue_status text not null default 'pending',
  enqueue_reason text not null default 'missing_coordinates',
  queued_at timestamptz not null default now(),
  last_attempt_at timestamptz,
  attempts integer not null default 0,
  unique (entity_domain, entity_id)
);

create index if not exists idx_coordinate_enrichment_queue_status
  on public.coordinate_enrichment_queue_v1 (queue_status, queued_at);

alter table public.coordinate_enrichment_queue_v1 enable row level security;

drop policy if exists deny_client_eeba353f00
  on public.coordinate_enrichment_queue_v1;
create policy deny_client_eeba353f00
  on public.coordinate_enrichment_queue_v1
  for all
  to anon, authenticated
  using (false)
  with check (false);

revoke all on table public.coordinate_enrichment_queue_v1
  from public, anon, authenticated;
grant all on table public.coordinate_enrichment_queue_v1 to service_role;

revoke all on sequence public.coordinate_enrichment_queue_v1_id_seq
  from public, anon, authenticated;
grant usage, select on sequence public.coordinate_enrichment_queue_v1_id_seq
  to service_role;
