-- Restore the immutable staging shape consumed by the state-directory
-- reassembly migration. Fresh databases start empty; the production row set is
-- imported separately and is not fabricated during schema replay.

create table if not exists public.state_enriched_directory_v3_13 (
  id bigint generated by default as identity primary key,
  source_file text not null,
  source_md5 text,
  source_kind text,
  source_key text,
  table_idx integer,
  row_idx integer,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique (source_md5, table_idx, row_idx)
);

create index if not exists idx_state_enriched_directory_v3_13_payload_gin
  on public.state_enriched_directory_v3_13 using gin (payload);
create index if not exists idx_state_enriched_directory_v3_13_source_key
  on public.state_enriched_directory_v3_13 (source_key);
create index if not exists idx_state_enriched_directory_v3_13_source_kind
  on public.state_enriched_directory_v3_13 (source_kind);

alter table public.state_enriched_directory_v3_13 enable row level security;

revoke all on table public.state_enriched_directory_v3_13
  from public, anon, authenticated;
grant all on table public.state_enriched_directory_v3_13 to service_role;

revoke all on sequence public.state_enriched_directory_v3_13_id_seq
  from public, anon, authenticated;
grant usage, select on sequence public.state_enriched_directory_v3_13_id_seq
  to service_role;
