begin

do $migration$
declare v_definition text;
begin
 select pg_get_functiondef('public.rosetta_v25_canonical_output(integer)'::regprocedure) into v_definition;
 v_definition:=replace(v_definition,'FUNCTION public.rosetta_v25_canonical_output(','FUNCTION public.rosetta_v251_canonical_output('); v_definition:=replace(v_definition,'rosetta-canonical-law-view-v25','rosetta-canonical-law-view-v251'); execute v_definition;
 select pg_get_functiondef('public.run_rosetta_v3_extraction_v25_base(integer,text,text,text,text,text,text,text,date,text,jsonb)'::regprocedure) into v_definition;
 if v_definition not like '%rosetta-v3-deterministic-sql-2.5.0%' or v_definition not like '%rosetta-five-layer-structural-correctness-2.5.0%' then raise exception 'rosetta_v251_expected_v25_base_missing'; end if;
 v_definition:=replace(v_definition,'FUNCTION public.run_rosetta_v3_extraction_v25_base(','FUNCTION public.run_rosetta_v3_extraction_v251_base('); v_definition:=replace(v_definition,'rosetta-v3-deterministic-sql-2.5.0','rosetta-v3-deterministic-sql-2.5.1'); v_definition:=replace(v_definition,'rosetta-five-layer-structural-correctness-2.5.0','rosetta-five-layer-structural-correctness-2.5.1'); v_definition:=replace(v_definition,'-v25-','-v251-'); execute v_definition;
 select pg_get_functiondef('public.rosetta_v25_finalize_extraction(integer,text,jsonb,jsonb)'::regprocedure) into v_definition;
 if v_definition not like '%rosetta-v3-deterministic-sql-2.5.0%' then raise exception 'rosetta_v251_expected_v25_finalizer_missing'; end if;
 v_definition:=replace(v_definition,'FUNCTION public.rosetta_v25_finalize_extraction(','FUNCTION public.rosetta_v251_finalize_extraction('); v_definition:=replace(v_definition,'rosetta-v3-deterministic-sql-2.5.0','rosetta-v3-deterministic-sql-2.5.1'); v_definition:=replace(v_definition,'rosetta-five-layer-structural-correctness-2.5.0','rosetta-five-layer-structural-correctness-2.5.1'); v_definition:=replace(v_definition,'-v25-','-v251-'); v_definition:=replace(v_definition,'public.rosetta_v25_canonical_output','public.rosetta_v251_canonical_output'); v_definition:=replace(v_definition,'rosetta-structural-correctness-v25','rosetta-structural-correctness-v251'); v_definition:=replace(v_definition,'exact_source_structure_v25','exact_source_structure_v251'); v_definition:=replace(v_definition,'rosetta_v25_canonical_output_unavailable','rosetta_v251_canonical_output_unavailable'); execute v_definition;
end;$migration$

with canonical_manifest as (select jsonb_build_object('contract','S -> {HELP, WORKFLOW, ACCOUNTABILITY, OVERRIDES, DEFINITIONS}','engine_version','rosetta-v3-deterministic-sql-2.5.1','rule_set_version','rosetta-five-layer-structural-correctness-2.5.1','inherits',jsonb_build_object('engine_version','rosetta-v3-deterministic-sql-2.5.0','rule_set_version','rosetta-five-layer-structural-correctness-2.5.0'),'accountability',jsonb_build_object('classification_basis','operative action precedence rather than incidental vocabulary','precedence',jsonb_build_array('penalty','reporting','licensing enforcement','investigation','procedure'),'penalty_actor','subject text preceding the guilty/penalty predicate','validation','expected action class and penalty actor are independently audited'),'source_projection','rosetta-layout-projection-v25','provenance','Rosetta 2.5.1 is a new immutable generation. 2.5.0 and all earlier receipts remain unchanged.') manifest_json), receipt as (select manifest_json,encode(digest(convert_to(manifest_json::text,'UTF8'),'sha256'),'hex') manifest_hash from canonical_manifest)
insert into public.extraction_rule_manifest(engine_version,rule_set_version,manifest_hash,manifest_json,is_active) select 'rosetta-v3-deterministic-sql-2.5.1','rosetta-five-layer-structural-correctness-2.5.1',manifest_hash,manifest_json,true from receipt on conflict(engine_version,rule_set_version) do update set manifest_hash=excluded.manifest_hash,manifest_json=excluded.manifest_json,is_active=true

create or replace function public.run_rosetta_v3_extraction(p_source_document_id integer,p_source_text text,p_expected_source_content_hash text,p_source_url text,p_source_version text,p_media_type text default 'text/plain',p_source_byte_hash text default null,p_source_provider_hash text default null,p_reference_date date default null,p_text_extractor_version text default 'plain-text-1',p_source_metadata jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set statement_timeout='120s' set search_path=pg_catalog,public,extensions as $$
declare v_receipt jsonb; v_run_id integer; v_reconciliation jsonb; v_span_receipt jsonb; v_span_repairs jsonb; v_validation jsonb; v_output jsonb; v_output_hash text; v_pass boolean; v_run_status text; v_admissibility text; v_failure_code text;
begin
 v_receipt:=public.run_rosetta_v3_extraction_v251_base(p_source_document_id,p_source_text,p_expected_source_content_hash,p_source_url,p_source_version,p_media_type,p_source_byte_hash,p_source_provider_hash,p_reference_date,p_text_extractor_version,p_source_metadata); if coalesce(v_receipt->>'run_status','')<>'completed' or coalesce(v_receipt->>'admissibility_state','')<>'admissible' then return v_receipt; end if;
 v_run_id:=nullif(v_receipt->>'extraction_run_id','')::integer; if v_run_id is null then return v_receipt; end if;
 v_receipt:=public.rosetta_v251_finalize_extraction(v_run_id,p_source_text,coalesce(p_source_metadata,'{}'::jsonb),v_receipt); v_reconciliation:=public.rosetta_v251_reconcile_structural_correctness(v_run_id); v_span_receipt:=public.rosetta_v25_refresh_object_source_spans(v_run_id,p_source_text); v_span_repairs:=public.rosetta_v25_register_span_repairs(v_run_id); v_validation:=public.rosetta_v251_validate_independent_structure(v_run_id,p_source_text); v_pass:=coalesce(v_validation->>'status','fail')='pass';
 insert into public.validation_result(id,extraction_run_id,test_name,test_result,failure_count,details) values('vr-v251-'||(select source_identity_hash from public.extraction_run where id=v_run_id)||'-'||(select configuration_hash from public.extraction_run where id=v_run_id)||'-independent-structure',v_run_id,'independent_structure_v251',case when v_pass then 'pass' else 'fail' end,case when v_pass then 0 else 1 end,v_validation) on conflict(extraction_run_id,test_name) do update set test_result=excluded.test_result,failure_count=excluded.failure_count,details=excluded.details,executed_at=now();
 v_run_status:=case when v_pass then 'completed' else 'failed' end; v_admissibility:=case when v_pass then 'admissible' else 'rejected' end; v_failure_code:=case when v_pass then null else 'rosetta_v251_independent_structural_validation_failed' end;
 update public.extraction_run set run_status=v_run_status,admissibility_state=v_admissibility,failure_code=v_failure_code,completed_at=coalesce(completed_at,clock_timestamp()) where id=v_run_id;
 update public.extraction_manifest set status=case when v_pass then 'clean' else 'failed' end,admissibility_state=v_admissibility,validation_results=coalesce(validation_results,'{}'::jsonb)||jsonb_build_object('structural_reconciliation_v251',v_reconciliation,'object_source_spans_v25',v_span_receipt,'span_repair_registration_v25',v_span_repairs,'independent_structure_v251',v_validation) where extraction_run_id=v_run_id;
 v_output:=public.rosetta_v251_canonical_output(v_run_id); if v_output is null then raise exception 'rosetta_v251_canonical_output_unavailable_after_validation'; end if; v_output_hash:=encode(digest(convert_to(v_output::text,'UTF8'),'sha256'),'hex'); update public.extraction_run set output_content_hash=v_output_hash where id=v_run_id; update public.extraction_manifest set output_hash=v_output_hash where extraction_run_id=v_run_id; update public.validation_result set test_result='pass',failure_count=0,details=jsonb_build_object('output_content_hash',v_output_hash),executed_at=now() where extraction_run_id=v_run_id and test_name='output_hash_verified';
 return v_receipt||jsonb_build_object('engine_version','rosetta-v3-deterministic-sql-2.5.1','rule_set_version','rosetta-five-layer-structural-correctness-2.5.1','run_status',v_run_status,'admissibility_state',v_admissibility,'failure_code',v_failure_code,'output_content_hash',v_output_hash,'structural_reconciliation',v_reconciliation,'object_source_spans',v_span_receipt,'independent_structure_v251',v_validation);
end;$$

revoke all on function public.rosetta_v251_canonical_output(integer) from public,anon,authenticated

revoke all on function public.run_rosetta_v3_extraction_v251_base(integer,text,text,text,text,text,text,text,date,text,jsonb) from public,anon,authenticated

revoke all on function public.rosetta_v251_finalize_extraction(integer,text,jsonb,jsonb) from public,anon,authenticated

revoke all on function public.run_rosetta_v3_extraction(integer,text,text,text,text,text,text,text,date,text,jsonb) from public,anon,authenticated

grant execute on function public.run_rosetta_v3_extraction(integer,text,text,text,text,text,text,text,date,text,jsonb) to service_role

comment on function public.run_rosetta_v3_extraction(integer,text,text,text,text,text,text,text,date,text,jsonb) is 'Rosetta 2.5.1 canonical decomposition. Inherits the 2.5 offset-preserving source projection and exact spans; accountability semantics are classified by operative-action precedence and audited before publication.'

commit
