-- Complete the predecessor pattern write boundary before the runtime contract.
-- Original UUID identities and foreign keys remain on source_pattern_id; the
-- active runtime receives a deterministic numeric ID without inventing links.
set lock_timeout = '5s';
set statement_timeout = '120s';

do $$
declare
  mapping record;
begin
  for mapping in select * from (values
    ('pattern_types','patternType','pattern_type'),
    ('pattern_types','createdAt','created_at'),
    ('pattern_occurrences','patternId','pattern_id'),
    ('pattern_occurrences','caseId','case_id'),
    ('pattern_occurrences','entityId','entity_id'),
    ('pattern_occurrences','agencyId','agency_id'),
    ('pattern_occurrences','evidenceReferenceId','evidence_reference_id'),
    ('pattern_occurrences','evidenceReferenceType','evidence_reference_type'),
    ('pattern_occurrences','createdAt','created_at')
  ) as mappings(relation_name, legacy_name, canonical_name)
  loop
    if exists (select 1 from information_schema.columns where table_schema='public'
      and table_name=mapping.relation_name and column_name=mapping.legacy_name) then
      if exists (select 1 from information_schema.columns where table_schema='public'
        and table_name=mapping.relation_name and column_name=mapping.canonical_name) then
        raise exception 'Ambiguous pattern columns: %.% and % both exist',
          mapping.relation_name,mapping.legacy_name,mapping.canonical_name;
      end if;
      execute format('alter table public.%I rename column %I to %I',
        mapping.relation_name,mapping.legacy_name,mapping.canonical_name);
    end if;
  end loop;

  -- The following runtime migration seeds pattern types without a timestamp.
  -- The predecessor column exists but has no database default.
  if exists (select 1 from information_schema.columns where table_schema='public'
    and table_name='pattern_types' and column_name='created_at' and udt_name='int8') then
    alter table public.pattern_types alter column created_at
      set default ((extract(epoch from clock_timestamp())*1000)::bigint);
  end if;
end;
$$;

do $$
declare
  numeric_floor bigint := 0;
  field_name text;
begin
  if not exists (select 1 from information_schema.columns where table_schema='public'
    and table_name='patterns' and column_name='id' and udt_name='uuid') then
    return;
  end if;

  -- Integer occurrences cannot identify a UUID parent. Preserve their original
  -- values and allocate above them so no accidental relationship is invented.
  if exists (select 1 from information_schema.columns where table_schema='public'
    and table_name='pattern_occurrences' and column_name='pattern_id'
    and udt_name in ('int2','int4','int8')) then
    select greatest(coalesce(max(pattern_id),0),0) into numeric_floor
      from public.pattern_occurrences;
  end if;
  if numeric_floor + (select count(*) from public.patterns) >= 2147483647 then
    raise exception 'Predecessor pattern IDs exceed the integer occurrence contract';
  end if;

  alter table public.patterns rename column id to source_pattern_id;
  alter table public.patterns add column id bigint;
  with ordered_ids as (
    select source_pattern_id,numeric_floor + row_number() over (order by source_pattern_id) as runtime_id
    from public.patterns
  )
  update public.patterns p set id=m.runtime_id
    from ordered_ids m where m.source_pattern_id=p.source_pattern_id;
  alter table public.patterns alter column id set not null;
  alter table public.patterns alter column id add generated by default as identity;
  create unique index uq_patterns_runtime_numeric_id on public.patterns(id);
  perform setval(pg_get_serial_sequence('public.patterns','id'),
    greatest(coalesce((select max(id) from public.patterns),numeric_floor),1),true);

  -- Keep the original primary key and all inbound UUID references intact.
  -- New canonical rows also need a value for that preserved identity column.
  if not exists (select 1 from information_schema.columns where table_schema='public'
    and table_name='patterns' and column_name='source_pattern_id' and column_default is not null) then
    alter table public.patterns alter column source_pattern_id set default gen_random_uuid();
  end if;

  -- UUID case provenance has no authoritative integer-case mapping. Preserve
  -- it beside the optional canonical case link instead of coercing its value.
  if exists (select 1 from information_schema.columns where table_schema='public'
    and table_name='patterns' and column_name='case_id' and udt_name='uuid') then
    alter table public.patterns rename column case_id to source_case_id;
    alter table public.patterns add column case_id integer;
  end if;
  foreach field_name in array array['case_id','source_case_id','snapshot_id','pipeline_run_id'] loop
    if exists (select 1 from information_schema.columns where table_schema='public'
      and table_name='patterns' and column_name=field_name) then
      execute format('alter table public.patterns alter column %I drop not null',field_name);
    end if;
  end loop;

  -- UUID occurrence links have an exact mapping. Renaming preserves their
  -- original foreign key while a numeric link serves the active runtime.
  if exists (select 1 from information_schema.columns where table_schema='public'
    and table_name='pattern_occurrences' and column_name='pattern_id' and udt_name='uuid') then
    alter table public.pattern_occurrences rename column pattern_id to source_pattern_id;
    alter table public.pattern_occurrences alter column source_pattern_id drop not null;
    alter table public.pattern_occurrences add column pattern_id integer;
    update public.pattern_occurrences o set pattern_id=p.id
      from public.patterns p where p.source_pattern_id=o.source_pattern_id;
    if exists (select 1 from public.pattern_occurrences where pattern_id is null) then
      raise exception 'An original UUID occurrence has no pattern identity mapping';
    end if;
    alter table public.pattern_occurrences alter column pattern_id set not null;
    alter table public.pattern_occurrences add constraint pattern_occurrences_runtime_pattern_fk
      foreign key (pattern_id) references public.patterns(id);
  end if;
end;
$$;
